.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel __osDequeueThread
    /* 85310 800CAB10 00803025 */  or         $a2, $a0, $zero
    /* 85314 800CAB14 8CC70000 */  lw         $a3, 0x0($a2)
    /* 85318 800CAB18 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 8531C 800CAB1C 10E0000A */  beqz       $a3, .L800CAB48
    /* 85320 800CAB20 00000000 */   nop
  .L800CAB24:
    /* 85324 800CAB24 14E50004 */  bne        $a3, $a1, .L800CAB38
    /* 85328 800CAB28 00000000 */   nop
    /* 8532C 800CAB2C 8CAE0000 */  lw         $t6, 0x0($a1)
    /* 85330 800CAB30 10000005 */  b          .L800CAB48
    /* 85334 800CAB34 ACCE0000 */   sw        $t6, 0x0($a2)
  .L800CAB38:
    /* 85338 800CAB38 00E03025 */  or         $a2, $a3, $zero
    /* 8533C 800CAB3C 8CC70000 */  lw         $a3, 0x0($a2)
    /* 85340 800CAB40 14E0FFF8 */  bnez       $a3, .L800CAB24
    /* 85344 800CAB44 00000000 */   nop
  .L800CAB48:
    /* 85348 800CAB48 03E00008 */  jr         $ra
    /* 8534C 800CAB4C 27BD0008 */   addiu     $sp, $sp, 0x8

/* Handwritten function */
glabel func_800CAB50
    /* 85350 800CAB50 3C1A800D */  lui        $k0, %hi(D_800CAB60) /* handwritten instruction */
    /* 85354 800CAB54 275AAB60 */  addiu      $k0, $k0, %lo(D_800CAB60) /* handwritten instruction */
    /* 85358 800CAB58 03400008 */  jr         $k0
    /* 8535C 800CAB5C 00000000 */   nop
  glabel D_800CAB60
    /* 85360 800CAB60 3C1A801E */  lui        $k0, %hi(D_801DADF0) /* handwritten instruction */
    /* 85364 800CAB64 275AADF0 */  addiu      $k0, $k0, %lo(D_801DADF0) /* handwritten instruction */
    /* 85368 800CAB68 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* 8536C 800CAB6C 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* 85370 800CAB70 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 85374 800CAB74 2401FFFC */  addiu      $at, $zero, -0x4
    /* 85378 800CAB78 0361D824 */  and        $k1, $k1, $at
    /* 8537C 800CAB7C 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 85380 800CAB80 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* 85384 800CAB84 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 85388 800CAB88 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* 8538C 800CAB8C AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* 85390 800CAB90 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 85394 800CAB94 3109007C */  andi       $t1, $t0, 0x7C
    /* 85398 800CAB98 240A0000 */  addiu      $t2, $zero, 0x0
    /* 8539C 800CAB9C 152A0010 */  bne        $t1, $t2, .L800CABE0
    /* 853A0 800CABA0 00000000 */   nop
    /* 853A4 800CABA4 03684824 */  and        $t1, $k1, $t0
    /* 853A8 800CABA8 312A4000 */  andi       $t2, $t1, 0x4000
    /* 853AC 800CABAC 11400005 */  beqz       $t2, .L800CABC4
    /* 853B0 800CABB0 00000000 */   nop
    /* 853B4 800CABB4 24090001 */  addiu      $t1, $zero, 0x1
    /* 853B8 800CABB8 3C01800F */  lui        $at, %hi(D_800E9034)
    /* 853BC 800CABBC 10000019 */  b          .L800CAC24
    /* 853C0 800CABC0 AC299034 */   sw        $t1, %lo(D_800E9034)($at)
  .L800CABC4:
    /* 853C4 800CABC4 312A2000 */  andi       $t2, $t1, 0x2000
    /* 853C8 800CABC8 11400005 */  beqz       $t2, .L800CABE0
    /* 853CC 800CABCC 00000000 */   nop
    /* 853D0 800CABD0 24090001 */  addiu      $t1, $zero, 0x1
    /* 853D4 800CABD4 3C01800F */  lui        $at, %hi(D_800E9038)
    /* 853D8 800CABD8 10000012 */  b          .L800CAC24
    /* 853DC 800CABDC AC299038 */   sw        $t1, %lo(D_800E9038)($at)
  .L800CABE0:
    /* 853E0 800CABE0 3C01800F */  lui        $at, %hi(D_800E9034)
    /* 853E4 800CABE4 AC209034 */  sw         $zero, %lo(D_800E9034)($at)
    /* 853E8 800CABE8 3C01800F */  lui        $at, %hi(D_800E9038)
    /* 853EC 800CABEC 03404025 */  or         $t0, $k0, $zero
    /* 853F0 800CABF0 AC209038 */  sw         $zero, %lo(D_800E9038)($at)
    /* 853F4 800CABF4 3C1A800F */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* 853F8 800CABF8 8F5A9010 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* 853FC 800CABFC DD090020 */  ld         $t1, 0x20($t0)
    /* 85400 800CAC00 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* 85404 800CAC04 DD090118 */  ld         $t1, 0x118($t0)
    /* 85408 800CAC08 FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* 8540C 800CAC0C DD090058 */  ld         $t1, 0x58($t0)
    /* 85410 800CAC10 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* 85414 800CAC14 DD090060 */  ld         $t1, 0x60($t0)
    /* 85418 800CAC18 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 8541C 800CAC1C DD090068 */  ld         $t1, 0x68($t0)
    /* 85420 800CAC20 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
  .L800CAC24:
    /* 85424 800CAC24 00004012 */  mflo       $t0
    /* 85428 800CAC28 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* 8542C 800CAC2C 00004010 */  mfhi       $t0
    /* 85430 800CAC30 FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* 85434 800CAC34 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* 85438 800CAC38 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* 8543C 800CAC3C FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* 85440 800CAC40 FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* 85444 800CAC44 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* 85448 800CAC48 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* 8544C 800CAC4C FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* 85450 800CAC50 FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* 85454 800CAC54 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* 85458 800CAC58 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* 8545C 800CAC5C FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* 85460 800CAC60 FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* 85464 800CAC64 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* 85468 800CAC68 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* 8546C 800CAC6C FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* 85470 800CAC70 FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* 85474 800CAC74 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* 85478 800CAC78 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* 8547C 800CAC7C FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* 85480 800CAC80 FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* 85484 800CAC84 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* 85488 800CAC88 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* 8548C 800CAC8C FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* 85490 800CAC90 FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* 85494 800CAC94 FF480110 */  sd         $t0, 0x110($k0) /* handwritten instruction */
    /* 85498 800CAC98 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* 8549C 800CAC9C AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* 854A0 800CACA0 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* 854A4 800CACA4 11000014 */  beqz       $t0, .L800CACF8
    /* 854A8 800CACA8 00000000 */   nop
    /* 854AC 800CACAC 4448F800 */  cfc1       $t0, $31
    /* 854B0 800CACB0 00000000 */  nop
    /* 854B4 800CACB4 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* 854B8 800CACB8 F7400130 */  sdc1       $f0, 0x130($k0)
    /* 854BC 800CACBC F7420138 */  sdc1       $f2, 0x138($k0)
    /* 854C0 800CACC0 F7440140 */  sdc1       $f4, 0x140($k0)
    /* 854C4 800CACC4 F7460148 */  sdc1       $f6, 0x148($k0)
    /* 854C8 800CACC8 F7480150 */  sdc1       $f8, 0x150($k0)
    /* 854CC 800CACCC F74A0158 */  sdc1       $f10, 0x158($k0)
    /* 854D0 800CACD0 F74C0160 */  sdc1       $f12, 0x160($k0)
    /* 854D4 800CACD4 F74E0168 */  sdc1       $f14, 0x168($k0)
    /* 854D8 800CACD8 F7500170 */  sdc1       $f16, 0x170($k0)
    /* 854DC 800CACDC F7520178 */  sdc1       $f18, 0x178($k0)
    /* 854E0 800CACE0 F7540180 */  sdc1       $f20, 0x180($k0)
    /* 854E4 800CACE4 F7560188 */  sdc1       $f22, 0x188($k0)
    /* 854E8 800CACE8 F7580190 */  sdc1       $f24, 0x190($k0)
    /* 854EC 800CACEC F75A0198 */  sdc1       $f26, 0x198($k0)
    /* 854F0 800CACF0 F75C01A0 */  sdc1       $f28, 0x1A0($k0)
    /* 854F4 800CACF4 F75E01A8 */  sdc1       $f30, 0x1A8($k0)
  .L800CACF8:
    /* 854F8 800CACF8 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 854FC 800CACFC AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* 85500 800CAD00 3C09A430 */  lui        $t1, %hi(D_A430000C)
    /* 85504 800CAD04 8D29000C */  lw         $t1, %lo(D_A430000C)($t1)
    /* 85508 800CAD08 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
    /* 8550C 800CAD0C 24090002 */  addiu      $t1, $zero, 0x2
    /* 85510 800CAD10 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 85514 800CAD14 3C09800F */  lui        $t1, %hi(D_800E9034)
    /* 85518 800CAD18 8D299034 */  lw         $t1, %lo(D_800E9034)($t1)
    /* 8551C 800CAD1C 11200009 */  beqz       $t1, .L800CAD44
    /* 85520 800CAD20 00000000 */   nop
    /* 85524 800CAD24 3C0AC000 */  lui        $t2, (0xC0000008 >> 16)
    /* 85528 800CAD28 AD400008 */  sw         $zero, (0xC0000008 & 0xFFFF)($t2)
    /* 8552C 800CAD2C 3C04C000 */  lui        $a0, (0xC0000000 >> 16)
    /* 85530 800CAD30 254A0008 */  addiu      $t2, $t2, %lo(D_C0000008)
    /* 85534 800CAD34 0C03426A */  jal        func_800D09A8
    /* 85538 800CAD38 8C840000 */   lw        $a0, (0xC0000000 & 0xFFFF)($a0)
    /* 8553C 800CAD3C 10000156 */  b          .L800CB298
    /* 85540 800CAD40 00000000 */   nop
  .L800CAD44:
    /* 85544 800CAD44 3C09800F */  lui        $t1, %hi(D_800E9038)
    /* 85548 800CAD48 8D299038 */  lw         $t1, %lo(D_800E9038)($t1)
    /* 8554C 800CAD4C 11200010 */  beqz       $t1, .L800CAD90
    /* 85550 800CAD50 00000000 */   nop
    /* 85554 800CAD54 3C0AC000 */  lui        $t2, (0xC000000C >> 16)
    /* 85558 800CAD58 AD40000C */  sw         $zero, (0xC000000C & 0xFFFF)($t2)
    /* 8555C 800CAD5C 3C09800F */  lui        $t1, %hi(D_800E9140)
    /* 85560 800CAD60 8D299140 */  lw         $t1, %lo(D_800E9140)($t1)
    /* 85564 800CAD64 254A000C */  addiu      $t2, $t2, %lo(D_C000000C)
    /* 85568 800CAD68 11200003 */  beqz       $t1, .L800CAD78
    /* 8556C 800CAD6C 00000000 */   nop
    /* 85570 800CAD70 0C032C2A */  jal        func_800CB0A8
    /* 85574 800CAD74 24040078 */   addiu     $a0, $zero, 0x78
  .L800CAD78:
    /* 85578 800CAD78 3C09800F */  lui        $t1, %hi(D_800E9144)
    /* 8557C 800CAD7C 8D299144 */  lw         $t1, %lo(D_800E9144)($t1)
    /* 85580 800CAD80 3C01800F */  lui        $at, %hi(D_800E9144)
    /* 85584 800CAD84 21290001 */  addi       $t1, $t1, 0x1 /* handwritten instruction */
    /* 85588 800CAD88 10000143 */  b          .L800CB298
    /* 8558C 800CAD8C AC299144 */   sw        $t1, %lo(D_800E9144)($at)
  .L800CAD90:
    /* 85590 800CAD90 3109007C */  andi       $t1, $t0, 0x7C
    /* 85594 800CAD94 240A0024 */  addiu      $t2, $zero, 0x24
    /* 85598 800CAD98 112A009E */  beq        $t1, $t2, .L800CB014
    /* 8559C 800CAD9C 00000000 */   nop
    /* 855A0 800CADA0 240A002C */  addiu      $t2, $zero, 0x2C
    /* 855A4 800CADA4 112A00ED */  beq        $t1, $t2, .L800CB15C
    /* 855A8 800CADA8 00000000 */   nop
    /* 855AC 800CADAC 240A0000 */  addiu      $t2, $zero, 0x0
    /* 855B0 800CADB0 152A00B1 */  bne        $t1, $t2, .L800CB078
    /* 855B4 800CADB4 00000000 */   nop
    /* 855B8 800CADB8 03688024 */  and        $s0, $k1, $t0
  .L800CADBC:
    /* 855BC 800CADBC 3209FF00 */  andi       $t1, $s0, 0xFF00
    /* 855C0 800CADC0 00095302 */  srl        $t2, $t1, 12
    /* 855C4 800CADC4 15400003 */  bnez       $t2, .L800CADD4
    /* 855C8 800CADC8 00000000 */   nop
    /* 855CC 800CADCC 00095202 */  srl        $t2, $t1, 8
    /* 855D0 800CADD0 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .L800CADD4:
    /* 855D4 800CADD4 3C01800F */  lui        $at, %hi(D_800EC600)
    /* 855D8 800CADD8 002A0821 */  addu       $at, $at, $t2
    /* 855DC 800CADDC 902AC600 */  lbu        $t2, %lo(D_800EC600)($at)
    /* 855E0 800CADE0 3C01800F */  lui        $at, %hi(jtbl_800EC620_main_segment)
    /* 855E4 800CADE4 002A0821 */  addu       $at, $at, $t2
    /* 855E8 800CADE8 8C2AC620 */  lw         $t2, %lo(jtbl_800EC620_main_segment)($at)
    /* 855EC 800CADEC 01400008 */  jr         $t2
    /* 855F0 800CADF0 00000000 */   nop
    /* 855F4 800CADF4 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* 855F8 800CADF8 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* 855FC 800CADFC 0C032C2A */  jal        func_800CB0A8
    /* 85600 800CAE00 24040018 */   addiu     $a0, $zero, 0x18
    /* 85604 800CAE04 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* 85608 800CAE08 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* 8560C 800CAE0C 1000FFEB */  b          .L800CADBC
    /* 85610 800CAE10 02018024 */   and       $s0, $s0, $at
    /* 85614 800CAE14 240A0004 */  addiu      $t2, $zero, 0x4
    /* 85618 800CAE18 3C01800F */  lui        $at, %hi(D_800E9020)
    /* 8561C 800CAE1C 002A0821 */  addu       $at, $at, $t2
    /* 85620 800CAE20 8C2A9020 */  lw         $t2, %lo(D_800E9020)($at)
    /* 85624 800CAE24 11400003 */  beqz       $t2, .L800CAE34
    /* 85628 800CAE28 00000000 */   nop
    /* 8562C 800CAE2C 0140F809 */  jalr       $t2
    /* 85630 800CAE30 00000000 */   nop
  .L800CAE34:
    /* 85634 800CAE34 0C032C2A */  jal        func_800CB0A8
    /* 85638 800CAE38 24040010 */   addiu     $a0, $zero, 0x10
    /* 8563C 800CAE3C 2401F7FF */  addiu      $at, $zero, -0x801
    /* 85640 800CAE40 1000FFDE */  b          .L800CADBC
    /* 85644 800CAE44 02018024 */   and       $s0, $s0, $at
    /* 85648 800CAE48 3C11A430 */  lui        $s1, %hi(D_A4300008)
    /* 8564C 800CAE4C 8E310008 */  lw         $s1, %lo(D_A4300008)($s1)
    /* 85650 800CAE50 3231003F */  andi       $s1, $s1, 0x3F
    /* 85654 800CAE54 32290001 */  andi       $t1, $s1, 0x1
    /* 85658 800CAE58 11200013 */  beqz       $t1, .L800CAEA8
    /* 8565C 800CAE5C 00000000 */   nop
    /* 85660 800CAE60 3C0CA404 */  lui        $t4, %hi(D_A4040010)
    /* 85664 800CAE64 8D8C0010 */  lw         $t4, %lo(D_A4040010)($t4)
    /* 85668 800CAE68 24090008 */  addiu      $t1, $zero, 0x8
    /* 8566C 800CAE6C 3C01A404 */  lui        $at, %hi(D_A4040010)
    /* 85670 800CAE70 318C0300 */  andi       $t4, $t4, 0x300
    /* 85674 800CAE74 3231003E */  andi       $s1, $s1, 0x3E
    /* 85678 800CAE78 11800007 */  beqz       $t4, .L800CAE98
    /* 8567C 800CAE7C AC290010 */   sw        $t1, %lo(D_A4040010)($at)
    /* 85680 800CAE80 0C032C2A */  jal        func_800CB0A8
    /* 85684 800CAE84 24040020 */   addiu     $a0, $zero, 0x20
    /* 85688 800CAE88 12200038 */  beqz       $s1, .L800CAF6C
    /* 8568C 800CAE8C 00000000 */   nop
    /* 85690 800CAE90 10000005 */  b          .L800CAEA8
    /* 85694 800CAE94 00000000 */   nop
  .L800CAE98:
    /* 85698 800CAE98 0C032C2A */  jal        func_800CB0A8
    /* 8569C 800CAE9C 24040058 */   addiu     $a0, $zero, 0x58
    /* 856A0 800CAEA0 12200032 */  beqz       $s1, .L800CAF6C
    /* 856A4 800CAEA4 00000000 */   nop
  .L800CAEA8:
    /* 856A8 800CAEA8 32290008 */  andi       $t1, $s1, 0x8
    /* 856AC 800CAEAC 11200007 */  beqz       $t1, .L800CAECC
    /* 856B0 800CAEB0 3C01A440 */   lui       $at, %hi(D_A4400010)
    /* 856B4 800CAEB4 32310037 */  andi       $s1, $s1, 0x37
    /* 856B8 800CAEB8 AC200010 */  sw         $zero, %lo(D_A4400010)($at)
    /* 856BC 800CAEBC 0C032C2A */  jal        func_800CB0A8
    /* 856C0 800CAEC0 24040038 */   addiu     $a0, $zero, 0x38
    /* 856C4 800CAEC4 12200029 */  beqz       $s1, .L800CAF6C
    /* 856C8 800CAEC8 00000000 */   nop
  .L800CAECC:
    /* 856CC 800CAECC 32290004 */  andi       $t1, $s1, 0x4
    /* 856D0 800CAED0 11200009 */  beqz       $t1, .L800CAEF8
    /* 856D4 800CAED4 00000000 */   nop
    /* 856D8 800CAED8 24090001 */  addiu      $t1, $zero, 0x1
    /* 856DC 800CAEDC 3C01A450 */  lui        $at, %hi(D_A450000C)
    /* 856E0 800CAEE0 3231003B */  andi       $s1, $s1, 0x3B
    /* 856E4 800CAEE4 AC29000C */  sw         $t1, %lo(D_A450000C)($at)
    /* 856E8 800CAEE8 0C032C2A */  jal        func_800CB0A8
    /* 856EC 800CAEEC 24040030 */   addiu     $a0, $zero, 0x30
    /* 856F0 800CAEF0 1220001E */  beqz       $s1, .L800CAF6C
    /* 856F4 800CAEF4 00000000 */   nop
  .L800CAEF8:
    /* 856F8 800CAEF8 32290002 */  andi       $t1, $s1, 0x2
    /* 856FC 800CAEFC 11200007 */  beqz       $t1, .L800CAF1C
    /* 85700 800CAF00 3C01A480 */   lui       $at, %hi(D_A4800018)
    /* 85704 800CAF04 3231003D */  andi       $s1, $s1, 0x3D
    /* 85708 800CAF08 AC200018 */  sw         $zero, %lo(D_A4800018)($at)
    /* 8570C 800CAF0C 0C032C2A */  jal        func_800CB0A8
    /* 85710 800CAF10 24040028 */   addiu     $a0, $zero, 0x28
    /* 85714 800CAF14 12200015 */  beqz       $s1, .L800CAF6C
    /* 85718 800CAF18 00000000 */   nop
  .L800CAF1C:
    /* 8571C 800CAF1C 32290010 */  andi       $t1, $s1, 0x10
    /* 85720 800CAF20 11200009 */  beqz       $t1, .L800CAF48
    /* 85724 800CAF24 00000000 */   nop
    /* 85728 800CAF28 24090002 */  addiu      $t1, $zero, 0x2
    /* 8572C 800CAF2C 3C01A460 */  lui        $at, %hi(D_A4600010)
    /* 85730 800CAF30 3231002F */  andi       $s1, $s1, 0x2F
    /* 85734 800CAF34 AC290010 */  sw         $t1, %lo(D_A4600010)($at)
    /* 85738 800CAF38 0C032C2A */  jal        func_800CB0A8
    /* 8573C 800CAF3C 24040040 */   addiu     $a0, $zero, 0x40
    /* 85740 800CAF40 1220000A */  beqz       $s1, .L800CAF6C
    /* 85744 800CAF44 00000000 */   nop
  .L800CAF48:
    /* 85748 800CAF48 32290020 */  andi       $t1, $s1, 0x20
    /* 8574C 800CAF4C 11200007 */  beqz       $t1, .L800CAF6C
    /* 85750 800CAF50 00000000 */   nop
    /* 85754 800CAF54 24090800 */  addiu      $t1, $zero, 0x800
    /* 85758 800CAF58 3C01A430 */  lui        $at, %hi(D_A4300000)
    /* 8575C 800CAF5C 3231001F */  andi       $s1, $s1, 0x1F
    /* 85760 800CAF60 AC290000 */  sw         $t1, %lo(D_A4300000)($at)
    /* 85764 800CAF64 0C032C2A */  jal        func_800CB0A8
    /* 85768 800CAF68 24040048 */   addiu     $a0, $zero, 0x48
  .L800CAF6C:
    /* 8576C 800CAF6C 2401FBFF */  addiu      $at, $zero, -0x401
    /* 85770 800CAF70 1000FF92 */  b          .L800CADBC
    /* 85774 800CAF74 02018024 */   and       $s0, $s0, $at
    /* 85778 800CAF78 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 8577C 800CAF7C 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 85780 800CAF80 3C09800F */  lui        $t1, %hi(D_800E8FD8)
    /* 85784 800CAF84 0361D824 */  and        $k1, $k1, $at
    /* 85788 800CAF88 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 8578C 800CAF8C 25298FD8 */  addiu      $t1, $t1, %lo(D_800E8FD8)
    /* 85790 800CAF90 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 85794 800CAF94 11400003 */  beqz       $t2, .L800CAFA4
    /* 85798 800CAF98 2401EFFF */   addiu     $at, $zero, -0x1001
    /* 8579C 800CAF9C 10000023 */  b          .L800CB02C
    /* 857A0 800CAFA0 02018024 */   and       $s0, $s0, $at
  .L800CAFA4:
    /* 857A4 800CAFA4 240A0001 */  addiu      $t2, $zero, 0x1
    /* 857A8 800CAFA8 AD2A0000 */  sw         $t2, 0x0($t1)
    /* 857AC 800CAFAC 0C032C2A */  jal        func_800CB0A8
    /* 857B0 800CAFB0 24040070 */   addiu     $a0, $zero, 0x70
    /* 857B4 800CAFB4 3C0A800F */  lui        $t2, %hi(__osRunQueue)
    /* 857B8 800CAFB8 8D4A9008 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 857BC 800CAFBC 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 857C0 800CAFC0 02018024 */  and        $s0, $s0, $at
    /* 857C4 800CAFC4 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* 857C8 800CAFC8 0361D824 */  and        $k1, $k1, $at
    /* 857CC 800CAFCC 10000017 */  b          .L800CB02C
    /* 857D0 800CAFD0 AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
    /* 857D4 800CAFD4 2401FDFF */  addiu      $at, $zero, -0x201
    /* 857D8 800CAFD8 01014024 */  and        $t0, $t0, $at
    /* 857DC 800CAFDC 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 857E0 800CAFE0 0C032C2A */  jal        func_800CB0A8
    /* 857E4 800CAFE4 24040008 */   addiu     $a0, $zero, 0x8
    /* 857E8 800CAFE8 2401FDFF */  addiu      $at, $zero, -0x201
    /* 857EC 800CAFEC 1000FF73 */  b          .L800CADBC
    /* 857F0 800CAFF0 02018024 */   and       $s0, $s0, $at
    /* 857F4 800CAFF4 2401FEFF */  addiu      $at, $zero, -0x101
    /* 857F8 800CAFF8 01014024 */  and        $t0, $t0, $at
    /* 857FC 800CAFFC 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 85800 800CB000 0C032C2A */  jal        func_800CB0A8
    /* 85804 800CB004 24040000 */   addiu     $a0, $zero, 0x0
    /* 85808 800CB008 2401FEFF */  addiu      $at, $zero, -0x101
    /* 8580C 800CB00C 1000FF6B */  b          .L800CADBC
    /* 85810 800CB010 02018024 */   and       $s0, $s0, $at
  .L800CB014:
    /* 85814 800CB014 24090001 */  addiu      $t1, $zero, 0x1
    /* 85818 800CB018 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 8581C 800CB01C 0C032C2A */  jal        func_800CB0A8
    /* 85820 800CB020 24040050 */   addiu     $a0, $zero, 0x50
    /* 85824 800CB024 10000001 */  b          .L800CB02C
    /* 85828 800CB028 00000000 */   nop
  .L800CB02C:
    /* 8582C 800CB02C 3C0A800F */  lui        $t2, %hi(__osRunQueue)
    /* 85830 800CB030 8D4A9008 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 85834 800CB034 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* 85838 800CB038 8D4B0004 */  lw         $t3, 0x4($t2)
    /* 8583C 800CB03C 012B082A */  slt        $at, $t1, $t3
    /* 85840 800CB040 10200007 */  beqz       $at, .L800CB060
    /* 85844 800CB044 00000000 */   nop
    /* 85848 800CB048 3C04800F */  lui        $a0, %hi(__osRunQueue)
    /* 8584C 800CB04C 03402825 */  or         $a1, $k0, $zero
    /* 85850 800CB050 0C032C88 */  jal        __osEnqueueThread
    /* 85854 800CB054 24849008 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 85858 800CB058 08032C9E */  j          __osDispatchThread
    /* 8585C 800CB05C 00000000 */   nop
  .L800CB060:
    /* 85860 800CB060 3C09800F */  lui        $t1, %hi(__osRunQueue)
    /* 85864 800CB064 25299008 */  addiu      $t1, $t1, %lo(__osRunQueue)
    /* 85868 800CB068 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 8586C 800CB06C AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* 85870 800CB070 08032C9E */  j          __osDispatchThread
    /* 85874 800CB074 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .L800CB078:
    /* 85878 800CB078 3C01800F */  lui        $at, %hi(D_800E9014)
    /* 8587C 800CB07C AC3A9014 */  sw         $k0, %lo(D_800E9014)($at) /* handwritten instruction */
    /* 85880 800CB080 24090001 */  addiu      $t1, $zero, 0x1
    /* 85884 800CB084 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 85888 800CB088 24090002 */  addiu      $t1, $zero, 0x2
    /* 8588C 800CB08C A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 85890 800CB090 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* 85894 800CB094 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* 85898 800CB098 0C032C2A */  jal        func_800CB0A8
    /* 8589C 800CB09C 24040060 */   addiu     $a0, $zero, 0x60
    /* 858A0 800CB0A0 08032C9E */  j          __osDispatchThread
    /* 858A4 800CB0A4 00000000 */   nop

/* Handwritten function */
glabel func_800CB0A8
    /* 858A8 800CB0A8 3C0A801E */  lui        $t2, %hi(__osEventStateTab)
    /* 858AC 800CB0AC 254A86F0 */  addiu      $t2, $t2, %lo(__osEventStateTab)
    /* 858B0 800CB0B0 01445021 */  addu       $t2, $t2, $a0
    /* 858B4 800CB0B4 8D490000 */  lw         $t1, 0x0($t2)
    /* 858B8 800CB0B8 03E09025 */  or         $s2, $ra, $zero
    /* 858BC 800CB0BC 11200025 */  beqz       $t1, .L800CB154
    /* 858C0 800CB0C0 00000000 */   nop
    /* 858C4 800CB0C4 8D2B0008 */  lw         $t3, 0x8($t1)
    /* 858C8 800CB0C8 8D2C0010 */  lw         $t4, 0x10($t1)
    /* 858CC 800CB0CC 016C082A */  slt        $at, $t3, $t4
    /* 858D0 800CB0D0 10200020 */  beqz       $at, .L800CB154
    /* 858D4 800CB0D4 00000000 */   nop
    /* 858D8 800CB0D8 8D2D000C */  lw         $t5, 0xC($t1)
    /* 858DC 800CB0DC 01AB6821 */  addu       $t5, $t5, $t3
    /* 858E0 800CB0E0 01AC001A */  div        $zero, $t5, $t4
    /* 858E4 800CB0E4 15800002 */  bnez       $t4, .L800CB0F0
    /* 858E8 800CB0E8 00000000 */   nop
    /* 858EC 800CB0EC 0007000D */  break      7
  .L800CB0F0:
    /* 858F0 800CB0F0 2401FFFF */  addiu      $at, $zero, -0x1
    /* 858F4 800CB0F4 15810004 */  bne        $t4, $at, .L800CB108
    /* 858F8 800CB0F8 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 858FC 800CB0FC 15A10002 */  bne        $t5, $at, .L800CB108
    /* 85900 800CB100 00000000 */   nop
    /* 85904 800CB104 0006000D */  break      6
  .L800CB108:
    /* 85908 800CB108 8D2C0014 */  lw         $t4, 0x14($t1)
    /* 8590C 800CB10C 00006810 */  mfhi       $t5
    /* 85910 800CB110 000D6880 */  sll        $t5, $t5, 2
    /* 85914 800CB114 018D6021 */  addu       $t4, $t4, $t5
    /* 85918 800CB118 8D4D0004 */  lw         $t5, 0x4($t2)
    /* 8591C 800CB11C 256A0001 */  addiu      $t2, $t3, 0x1
    /* 85920 800CB120 AD8D0000 */  sw         $t5, 0x0($t4)
    /* 85924 800CB124 AD2A0008 */  sw         $t2, 0x8($t1)
    /* 85928 800CB128 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 8592C 800CB12C 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 85930 800CB130 11600008 */  beqz       $t3, .L800CB154
    /* 85934 800CB134 00000000 */   nop
    /* 85938 800CB138 0C032C9A */  jal        __osPopThread
    /* 8593C 800CB13C 01202025 */   or        $a0, $t1, $zero
    /* 85940 800CB140 00405025 */  or         $t2, $v0, $zero
    /* 85944 800CB144 3C04800F */  lui        $a0, %hi(__osRunQueue)
    /* 85948 800CB148 01402825 */  or         $a1, $t2, $zero
    /* 8594C 800CB14C 0C032C88 */  jal        __osEnqueueThread
    /* 85950 800CB150 24849008 */   addiu     $a0, $a0, %lo(__osRunQueue)
  .L800CB154:
    /* 85954 800CB154 02400008 */  jr         $s2
    /* 85958 800CB158 00000000 */   nop
  .L800CB15C:
    /* 8595C 800CB15C 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* 85960 800CB160 01014824 */  and        $t1, $t0, $at
    /* 85964 800CB164 00094F02 */  srl        $t1, $t1, 28
    /* 85968 800CB168 240A0001 */  addiu      $t2, $zero, 0x1
    /* 8596C 800CB16C 152AFFC2 */  bne        $t1, $t2, .L800CB078
    /* 85970 800CB170 00000000 */   nop
    /* 85974 800CB174 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 85978 800CB178 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* 8597C 800CB17C 24090001 */  addiu      $t1, $zero, 0x1
    /* 85980 800CB180 0361D825 */  or         $k1, $k1, $at
    /* 85984 800CB184 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* 85988 800CB188 1000FFB5 */  b          .L800CB060
    /* 8598C 800CB18C AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */

/* Handwritten function */
glabel __osEnqueueAndYield
    /* 85990 800CB190 3C05800F */  lui        $a1, %hi(__osRunningThread)
    /* 85994 800CB194 8CA59010 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* 85998 800CB198 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 8599C 800CB19C 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* 859A0 800CB1A0 35080002 */  ori        $t0, $t0, 0x2
    /* 859A4 800CB1A4 ACA80118 */  sw         $t0, 0x118($a1)
    /* 859A8 800CB1A8 FCB00098 */  sd         $s0, 0x98($a1)
    /* 859AC 800CB1AC FCB100A0 */  sd         $s1, 0xA0($a1)
    /* 859B0 800CB1B0 FCB200A8 */  sd         $s2, 0xA8($a1)
    /* 859B4 800CB1B4 FCB300B0 */  sd         $s3, 0xB0($a1)
    /* 859B8 800CB1B8 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* 859BC 800CB1BC FCB500C0 */  sd         $s5, 0xC0($a1)
    /* 859C0 800CB1C0 FCB600C8 */  sd         $s6, 0xC8($a1)
    /* 859C4 800CB1C4 FCB700D0 */  sd         $s7, 0xD0($a1)
    /* 859C8 800CB1C8 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* 859CC 800CB1CC FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* 859D0 800CB1D0 FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* 859D4 800CB1D4 FCBF0100 */  sd         $ra, 0x100($a1)
    /* 859D8 800CB1D8 13600009 */  beqz       $k1, .L800CB200 /* handwritten instruction */
    /* 859DC 800CB1DC ACBF011C */   sw        $ra, 0x11C($a1)
    /* 859E0 800CB1E0 445BF800 */  cfc1       $k1, $31
    /* 859E4 800CB1E4 F4B40180 */  sdc1       $f20, 0x180($a1)
    /* 859E8 800CB1E8 F4B60188 */  sdc1       $f22, 0x188($a1)
    /* 859EC 800CB1EC F4B80190 */  sdc1       $f24, 0x190($a1)
    /* 859F0 800CB1F0 F4BA0198 */  sdc1       $f26, 0x198($a1)
    /* 859F4 800CB1F4 F4BC01A0 */  sdc1       $f28, 0x1A0($a1)
    /* 859F8 800CB1F8 F4BE01A8 */  sdc1       $f30, 0x1A8($a1)
    /* 859FC 800CB1FC ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
  .L800CB200:
    /* 85A00 800CB200 3C1BA430 */  lui        $k1, %hi(D_A430000C) /* handwritten instruction */
    /* 85A04 800CB204 8F7B000C */  lw         $k1, %lo(D_A430000C)($k1) /* handwritten instruction */
    /* 85A08 800CB208 10800003 */  beqz       $a0, .L800CB218
    /* 85A0C 800CB20C ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* 85A10 800CB210 0C032C88 */  jal        __osEnqueueThread
    /* 85A14 800CB214 00000000 */   nop
  .L800CB218:
    /* 85A18 800CB218 08032C9E */  j          __osDispatchThread
    /* 85A1C 800CB21C 00000000 */   nop

glabel __osEnqueueThread
    /* 85A20 800CB220 8C980000 */  lw         $t8, 0x0($a0)
    /* 85A24 800CB224 8CAF0004 */  lw         $t7, 0x4($a1)
    /* 85A28 800CB228 0080C825 */  or         $t9, $a0, $zero
    /* 85A2C 800CB22C 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 85A30 800CB230 01CF082A */  slt        $at, $t6, $t7
    /* 85A34 800CB234 14200007 */  bnez       $at, .L800CB254
    /* 85A38 800CB238 00000000 */   nop
  .L800CB23C:
    /* 85A3C 800CB23C 0300C825 */  or         $t9, $t8, $zero
    /* 85A40 800CB240 8F180000 */  lw         $t8, 0x0($t8)
    /* 85A44 800CB244 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 85A48 800CB248 01CF082A */  slt        $at, $t6, $t7
    /* 85A4C 800CB24C 1020FFFB */  beqz       $at, .L800CB23C
    /* 85A50 800CB250 00000000 */   nop
  .L800CB254:
    /* 85A54 800CB254 8F380000 */  lw         $t8, 0x0($t9)
    /* 85A58 800CB258 ACB80000 */  sw         $t8, 0x0($a1)
    /* 85A5C 800CB25C AF250000 */  sw         $a1, 0x0($t9)
    /* 85A60 800CB260 03E00008 */  jr         $ra
    /* 85A64 800CB264 ACA40008 */   sw        $a0, 0x8($a1)

glabel __osPopThread
    /* 85A68 800CB268 8C820000 */  lw         $v0, 0x0($a0)
    /* 85A6C 800CB26C 8C590000 */  lw         $t9, 0x0($v0)
    /* 85A70 800CB270 03E00008 */  jr         $ra
    /* 85A74 800CB274 AC990000 */   sw        $t9, 0x0($a0)

/* Handwritten function */
glabel __osDispatchThread
    /* 85A78 800CB278 3C04800F */  lui        $a0, %hi(__osRunQueue)
    /* 85A7C 800CB27C 0C032C9A */  jal        __osPopThread
    /* 85A80 800CB280 24849008 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 85A84 800CB284 3C01800F */  lui        $at, %hi(__osRunningThread)
    /* 85A88 800CB288 AC229010 */  sw         $v0, %lo(__osRunningThread)($at)
    /* 85A8C 800CB28C 24080004 */  addiu      $t0, $zero, 0x4
    /* 85A90 800CB290 A4480010 */  sh         $t0, 0x10($v0)
    /* 85A94 800CB294 0040D025 */  or         $k0, $v0, $zero
  .L800CB298:
    /* 85A98 800CB298 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* 85A9C 800CB29C DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* 85AA0 800CB2A0 DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* 85AA4 800CB2A4 03600013 */  mtlo       $k1
    /* 85AA8 800CB2A8 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* 85AAC 800CB2AC DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* 85AB0 800CB2B0 DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* 85AB4 800CB2B4 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* 85AB8 800CB2B8 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* 85ABC 800CB2BC DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* 85AC0 800CB2C0 DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* 85AC4 800CB2C4 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* 85AC8 800CB2C8 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* 85ACC 800CB2CC DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* 85AD0 800CB2D0 DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* 85AD4 800CB2D4 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* 85AD8 800CB2D8 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* 85ADC 800CB2DC DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* 85AE0 800CB2E0 DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* 85AE4 800CB2E4 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* 85AE8 800CB2E8 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* 85AEC 800CB2EC DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* 85AF0 800CB2F0 DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* 85AF4 800CB2F4 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* 85AF8 800CB2F8 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* 85AFC 800CB2FC DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* 85B00 800CB300 DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* 85B04 800CB304 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* 85B08 800CB308 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* 85B0C 800CB30C 03600011 */  mthi       $k1
    /* 85B10 800CB310 DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* 85B14 800CB314 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* 85B18 800CB318 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* 85B1C 800CB31C 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* 85B20 800CB320 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* 85B24 800CB324 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 85B28 800CB328 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 85B2C 800CB32C 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* 85B30 800CB330 13600013 */  beqz       $k1, .L800CB380 /* handwritten instruction */
    /* 85B34 800CB334 00000000 */   nop
    /* 85B38 800CB338 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* 85B3C 800CB33C 44DBF800 */  ctc1       $k1, $31
    /* 85B40 800CB340 D7400130 */  ldc1       $f0, 0x130($k0)
    /* 85B44 800CB344 D7420138 */  ldc1       $f2, 0x138($k0)
    /* 85B48 800CB348 D7440140 */  ldc1       $f4, 0x140($k0)
    /* 85B4C 800CB34C D7460148 */  ldc1       $f6, 0x148($k0)
    /* 85B50 800CB350 D7480150 */  ldc1       $f8, 0x150($k0)
    /* 85B54 800CB354 D74A0158 */  ldc1       $f10, 0x158($k0)
    /* 85B58 800CB358 D74C0160 */  ldc1       $f12, 0x160($k0)
    /* 85B5C 800CB35C D74E0168 */  ldc1       $f14, 0x168($k0)
    /* 85B60 800CB360 D7500170 */  ldc1       $f16, 0x170($k0)
    /* 85B64 800CB364 D7520178 */  ldc1       $f18, 0x178($k0)
    /* 85B68 800CB368 D7540180 */  ldc1       $f20, 0x180($k0)
    /* 85B6C 800CB36C D7560188 */  ldc1       $f22, 0x188($k0)
    /* 85B70 800CB370 D7580190 */  ldc1       $f24, 0x190($k0)
    /* 85B74 800CB374 D75A0198 */  ldc1       $f26, 0x198($k0)
    /* 85B78 800CB378 D75C01A0 */  ldc1       $f28, 0x1A0($k0)
    /* 85B7C 800CB37C D75E01A8 */  ldc1       $f30, 0x1A8($k0)
  .L800CB380:
    /* 85B80 800CB380 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* 85B84 800CB384 001BD840 */  sll        $k1, $k1, 1
    /* 85B88 800CB388 3C1A800F */  lui        $k0, %hi(D_800EC750) /* handwritten instruction */
    /* 85B8C 800CB38C 275AC750 */  addiu      $k0, $k0, %lo(D_800EC750) /* handwritten instruction */
    /* 85B90 800CB390 037AD821 */  addu       $k1, $k1, $k0
    /* 85B94 800CB394 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* 85B98 800CB398 3C1AA430 */  lui        $k0, %hi(D_A430000C) /* handwritten instruction */
    /* 85B9C 800CB39C 275A000C */  addiu      $k0, $k0, %lo(D_A430000C) /* handwritten instruction */
    /* 85BA0 800CB3A0 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* 85BA4 800CB3A4 00000000 */  nop
    /* 85BA8 800CB3A8 00000000 */  nop
    /* 85BAC 800CB3AC 00000000 */  nop
    /* 85BB0 800CB3B0 00000000 */  nop
    /* 85BB4 800CB3B4 42000018 */  eret /* handwritten instruction */

glabel __osCleanupThread
    /* 85BB8 800CB3B8 0C034348 */  jal        osDestroyThread
    /* 85BBC 800CB3BC 00002025 */   or        $a0, $zero, $zero
