.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel __osSpSetStatus
    /* 86270 800CBA70 3C0EA404 */  lui        $t6, %hi(D_A4040010)
    /* 86274 800CBA74 03E00008 */  jr         $ra
    /* 86278 800CBA78 ADC40010 */   sw        $a0, %lo(D_A4040010)($t6)
    /* 8627C 800CBA7C 00000000 */  nop
