.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_800CBA80
    /* 86280 800CBA80 10C0001A */  beqz       $a2, .L800CBAEC
    /* 86284 800CBA84 00A03825 */   or        $a3, $a1, $zero
    /* 86288 800CBA88 10850018 */  beq        $a0, $a1, .L800CBAEC
    /* 8628C 800CBA8C 00A4082A */   slt       $at, $a1, $a0
    /* 86290 800CBA90 54200008 */  bnel       $at, $zero, .L800CBAB4
    /* 86294 800CBA94 28C10010 */   slti      $at, $a2, 0x10
    /* 86298 800CBA98 00861020 */  add        $v0, $a0, $a2 /* handwritten instruction */
    /* 8629C 800CBA9C 00A2082A */  slt        $at, $a1, $v0
    /* 862A0 800CBAA0 50200004 */  beql       $at, $zero, .L800CBAB4
    /* 862A4 800CBAA4 28C10010 */   slti      $at, $a2, 0x10
    /* 862A8 800CBAA8 1000005B */  b          .L800CBC18
    /* 862AC 800CBAAC 28C10010 */   slti      $at, $a2, 0x10
    /* 862B0 800CBAB0 28C10010 */  slti       $at, $a2, 0x10
  .L800CBAB4:
    /* 862B4 800CBAB4 14200005 */  bnez       $at, .L800CBACC
    /* 862B8 800CBAB8 00000000 */   nop
    /* 862BC 800CBABC 30820003 */  andi       $v0, $a0, 0x3
    /* 862C0 800CBAC0 30A30003 */  andi       $v1, $a1, 0x3
    /* 862C4 800CBAC4 1043000B */  beq        $v0, $v1, .L800CBAF4
    /* 862C8 800CBAC8 00000000 */   nop
  .L800CBACC:
    /* 862CC 800CBACC 10C00007 */  beqz       $a2, .L800CBAEC
    /* 862D0 800CBAD0 00000000 */   nop
    /* 862D4 800CBAD4 00861821 */  addu       $v1, $a0, $a2
  .L800CBAD8:
    /* 862D8 800CBAD8 80820000 */  lb         $v0, 0x0($a0)
    /* 862DC 800CBADC 24840001 */  addiu      $a0, $a0, 0x1
    /* 862E0 800CBAE0 24A50001 */  addiu      $a1, $a1, 0x1
    /* 862E4 800CBAE4 1483FFFC */  bne        $a0, $v1, .L800CBAD8
    /* 862E8 800CBAE8 A0A2FFFF */   sb        $v0, -0x1($a1)
  .L800CBAEC:
    /* 862EC 800CBAEC 03E00008 */  jr         $ra
    /* 862F0 800CBAF0 00E01025 */   or        $v0, $a3, $zero
  .L800CBAF4:
    /* 862F4 800CBAF4 10400018 */  beqz       $v0, .L800CBB58
    /* 862F8 800CBAF8 24010001 */   addiu     $at, $zero, 0x1
    /* 862FC 800CBAFC 1041000F */  beq        $v0, $at, .L800CBB3C
    /* 86300 800CBB00 24010002 */   addiu     $at, $zero, 0x2
    /* 86304 800CBB04 50410008 */  beql       $v0, $at, .L800CBB28
    /* 86308 800CBB08 84820000 */   lh        $v0, 0x0($a0)
    /* 8630C 800CBB0C 80820000 */  lb         $v0, 0x0($a0)
    /* 86310 800CBB10 24840001 */  addiu      $a0, $a0, 0x1
    /* 86314 800CBB14 24A50001 */  addiu      $a1, $a1, 0x1
    /* 86318 800CBB18 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 8631C 800CBB1C 1000000E */  b          .L800CBB58
    /* 86320 800CBB20 A0A2FFFF */   sb        $v0, -0x1($a1)
    /* 86324 800CBB24 84820000 */  lh         $v0, 0x0($a0)
  .L800CBB28:
    /* 86328 800CBB28 24840002 */  addiu      $a0, $a0, 0x2
    /* 8632C 800CBB2C 24A50002 */  addiu      $a1, $a1, 0x2
    /* 86330 800CBB30 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* 86334 800CBB34 10000008 */  b          .L800CBB58
    /* 86338 800CBB38 A4A2FFFE */   sh        $v0, -0x2($a1)
  .L800CBB3C:
    /* 8633C 800CBB3C 80820000 */  lb         $v0, 0x0($a0)
    /* 86340 800CBB40 84830001 */  lh         $v1, 0x1($a0)
    /* 86344 800CBB44 24840003 */  addiu      $a0, $a0, 0x3
    /* 86348 800CBB48 24A50003 */  addiu      $a1, $a1, 0x3
    /* 8634C 800CBB4C 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* 86350 800CBB50 A0A2FFFD */  sb         $v0, -0x3($a1)
    /* 86354 800CBB54 A4A3FFFE */  sh         $v1, -0x2($a1)
  .L800CBB58:
    /* 86358 800CBB58 28C10020 */  slti       $at, $a2, 0x20
    /* 8635C 800CBB5C 54200016 */  bnel       $at, $zero, .L800CBBB8
    /* 86360 800CBB60 28C10010 */   slti      $at, $a2, 0x10
    /* 86364 800CBB64 8C820000 */  lw         $v0, 0x0($a0)
    /* 86368 800CBB68 8C830004 */  lw         $v1, 0x4($a0)
    /* 8636C 800CBB6C 8C880008 */  lw         $t0, 0x8($a0)
    /* 86370 800CBB70 8C89000C */  lw         $t1, 0xC($a0)
    /* 86374 800CBB74 8C8A0010 */  lw         $t2, 0x10($a0)
    /* 86378 800CBB78 8C8B0014 */  lw         $t3, 0x14($a0)
    /* 8637C 800CBB7C 8C8C0018 */  lw         $t4, 0x18($a0)
    /* 86380 800CBB80 8C8D001C */  lw         $t5, 0x1C($a0)
    /* 86384 800CBB84 24840020 */  addiu      $a0, $a0, 0x20
    /* 86388 800CBB88 24A50020 */  addiu      $a1, $a1, 0x20
    /* 8638C 800CBB8C 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* 86390 800CBB90 ACA2FFE0 */  sw         $v0, -0x20($a1)
    /* 86394 800CBB94 ACA3FFE4 */  sw         $v1, -0x1C($a1)
    /* 86398 800CBB98 ACA8FFE8 */  sw         $t0, -0x18($a1)
    /* 8639C 800CBB9C ACA9FFEC */  sw         $t1, -0x14($a1)
    /* 863A0 800CBBA0 ACAAFFF0 */  sw         $t2, -0x10($a1)
    /* 863A4 800CBBA4 ACABFFF4 */  sw         $t3, -0xC($a1)
    /* 863A8 800CBBA8 ACACFFF8 */  sw         $t4, -0x8($a1)
    /* 863AC 800CBBAC 1000FFEA */  b          .L800CBB58
    /* 863B0 800CBBB0 ACADFFFC */   sw        $t5, -0x4($a1)
  .L800CBBB4:
    /* 863B4 800CBBB4 28C10010 */  slti       $at, $a2, 0x10
  .L800CBBB8:
    /* 863B8 800CBBB8 5420000E */  bnel       $at, $zero, .L800CBBF4
    /* 863BC 800CBBBC 28C10004 */   slti      $at, $a2, 0x4
    /* 863C0 800CBBC0 8C820000 */  lw         $v0, 0x0($a0)
    /* 863C4 800CBBC4 8C830004 */  lw         $v1, 0x4($a0)
    /* 863C8 800CBBC8 8C880008 */  lw         $t0, 0x8($a0)
    /* 863CC 800CBBCC 8C89000C */  lw         $t1, 0xC($a0)
    /* 863D0 800CBBD0 24840010 */  addiu      $a0, $a0, 0x10
    /* 863D4 800CBBD4 24A50010 */  addiu      $a1, $a1, 0x10
    /* 863D8 800CBBD8 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* 863DC 800CBBDC ACA2FFF0 */  sw         $v0, -0x10($a1)
    /* 863E0 800CBBE0 ACA3FFF4 */  sw         $v1, -0xC($a1)
    /* 863E4 800CBBE4 ACA8FFF8 */  sw         $t0, -0x8($a1)
    /* 863E8 800CBBE8 1000FFF2 */  b          .L800CBBB4
    /* 863EC 800CBBEC ACA9FFFC */   sw        $t1, -0x4($a1)
  .L800CBBF0:
    /* 863F0 800CBBF0 28C10004 */  slti       $at, $a2, 0x4
  .L800CBBF4:
    /* 863F4 800CBBF4 1420FFB5 */  bnez       $at, .L800CBACC
    /* 863F8 800CBBF8 00000000 */   nop
    /* 863FC 800CBBFC 8C820000 */  lw         $v0, 0x0($a0)
    /* 86400 800CBC00 24840004 */  addiu      $a0, $a0, 0x4
    /* 86404 800CBC04 24A50004 */  addiu      $a1, $a1, 0x4
    /* 86408 800CBC08 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* 8640C 800CBC0C 1000FFF8 */  b          .L800CBBF0
    /* 86410 800CBC10 ACA2FFFC */   sw        $v0, -0x4($a1)
    /* 86414 800CBC14 28C10010 */  slti       $at, $a2, 0x10
  .L800CBC18:
    /* 86418 800CBC18 00862020 */  add        $a0, $a0, $a2 /* handwritten instruction */
    /* 8641C 800CBC1C 14200005 */  bnez       $at, .L800CBC34
    /* 86420 800CBC20 00A62820 */   add       $a1, $a1, $a2 /* handwritten instruction */
    /* 86424 800CBC24 30820003 */  andi       $v0, $a0, 0x3
    /* 86428 800CBC28 30A30003 */  andi       $v1, $a1, 0x3
    /* 8642C 800CBC2C 1043000D */  beq        $v0, $v1, .L800CBC64
    /* 86430 800CBC30 00000000 */   nop
  .L800CBC34:
    /* 86434 800CBC34 10C0FFAD */  beqz       $a2, .L800CBAEC
    /* 86438 800CBC38 00000000 */   nop
    /* 8643C 800CBC3C 2484FFFF */  addiu      $a0, $a0, -0x1
    /* 86440 800CBC40 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 86444 800CBC44 00861823 */  subu       $v1, $a0, $a2
  .L800CBC48:
    /* 86448 800CBC48 80820000 */  lb         $v0, 0x0($a0)
    /* 8644C 800CBC4C 2484FFFF */  addiu      $a0, $a0, -0x1
    /* 86450 800CBC50 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 86454 800CBC54 1483FFFC */  bne        $a0, $v1, .L800CBC48
    /* 86458 800CBC58 A0A20001 */   sb        $v0, 0x1($a1)
    /* 8645C 800CBC5C 03E00008 */  jr         $ra
    /* 86460 800CBC60 00E01025 */   or        $v0, $a3, $zero
  .L800CBC64:
    /* 86464 800CBC64 10400018 */  beqz       $v0, .L800CBCC8
    /* 86468 800CBC68 24010003 */   addiu     $at, $zero, 0x3
    /* 8646C 800CBC6C 1041000F */  beq        $v0, $at, .L800CBCAC
    /* 86470 800CBC70 24010002 */   addiu     $at, $zero, 0x2
    /* 86474 800CBC74 50410008 */  beql       $v0, $at, .L800CBC98
    /* 86478 800CBC78 8482FFFE */   lh        $v0, -0x2($a0)
    /* 8647C 800CBC7C 8082FFFF */  lb         $v0, -0x1($a0)
    /* 86480 800CBC80 2484FFFF */  addiu      $a0, $a0, -0x1
    /* 86484 800CBC84 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 86488 800CBC88 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 8648C 800CBC8C 1000000E */  b          .L800CBCC8
    /* 86490 800CBC90 A0A20000 */   sb        $v0, 0x0($a1)
    /* 86494 800CBC94 8482FFFE */  lh         $v0, -0x2($a0)
  .L800CBC98:
    /* 86498 800CBC98 2484FFFE */  addiu      $a0, $a0, -0x2
    /* 8649C 800CBC9C 24A5FFFE */  addiu      $a1, $a1, -0x2
    /* 864A0 800CBCA0 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* 864A4 800CBCA4 10000008 */  b          .L800CBCC8
    /* 864A8 800CBCA8 A4A20000 */   sh        $v0, 0x0($a1)
  .L800CBCAC:
    /* 864AC 800CBCAC 8082FFFF */  lb         $v0, -0x1($a0)
    /* 864B0 800CBCB0 8483FFFD */  lh         $v1, -0x3($a0)
    /* 864B4 800CBCB4 2484FFFD */  addiu      $a0, $a0, -0x3
    /* 864B8 800CBCB8 24A5FFFD */  addiu      $a1, $a1, -0x3
    /* 864BC 800CBCBC 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* 864C0 800CBCC0 A0A20002 */  sb         $v0, 0x2($a1)
    /* 864C4 800CBCC4 A4A30000 */  sh         $v1, 0x0($a1)
  .L800CBCC8:
    /* 864C8 800CBCC8 28C10020 */  slti       $at, $a2, 0x20
    /* 864CC 800CBCCC 54200016 */  bnel       $at, $zero, .L800CBD28
    /* 864D0 800CBCD0 28C10010 */   slti      $at, $a2, 0x10
    /* 864D4 800CBCD4 8C82FFFC */  lw         $v0, -0x4($a0)
    /* 864D8 800CBCD8 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* 864DC 800CBCDC 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* 864E0 800CBCE0 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* 864E4 800CBCE4 8C8AFFEC */  lw         $t2, -0x14($a0)
    /* 864E8 800CBCE8 8C8BFFE8 */  lw         $t3, -0x18($a0)
    /* 864EC 800CBCEC 8C8CFFE4 */  lw         $t4, -0x1C($a0)
    /* 864F0 800CBCF0 8C8DFFE0 */  lw         $t5, -0x20($a0)
    /* 864F4 800CBCF4 2484FFE0 */  addiu      $a0, $a0, -0x20
    /* 864F8 800CBCF8 24A5FFE0 */  addiu      $a1, $a1, -0x20
    /* 864FC 800CBCFC 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* 86500 800CBD00 ACA2001C */  sw         $v0, 0x1C($a1)
    /* 86504 800CBD04 ACA30018 */  sw         $v1, 0x18($a1)
    /* 86508 800CBD08 ACA80014 */  sw         $t0, 0x14($a1)
    /* 8650C 800CBD0C ACA90010 */  sw         $t1, 0x10($a1)
    /* 86510 800CBD10 ACAA000C */  sw         $t2, 0xC($a1)
    /* 86514 800CBD14 ACAB0008 */  sw         $t3, 0x8($a1)
    /* 86518 800CBD18 ACAC0004 */  sw         $t4, 0x4($a1)
    /* 8651C 800CBD1C 1000FFEA */  b          .L800CBCC8
    /* 86520 800CBD20 ACAD0000 */   sw        $t5, 0x0($a1)
  .L800CBD24:
    /* 86524 800CBD24 28C10010 */  slti       $at, $a2, 0x10
  .L800CBD28:
    /* 86528 800CBD28 5420000E */  bnel       $at, $zero, .L800CBD64
    /* 8652C 800CBD2C 28C10004 */   slti      $at, $a2, 0x4
    /* 86530 800CBD30 8C82FFFC */  lw         $v0, -0x4($a0)
    /* 86534 800CBD34 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* 86538 800CBD38 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* 8653C 800CBD3C 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* 86540 800CBD40 2484FFF0 */  addiu      $a0, $a0, -0x10
    /* 86544 800CBD44 24A5FFF0 */  addiu      $a1, $a1, -0x10
    /* 86548 800CBD48 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* 8654C 800CBD4C ACA2000C */  sw         $v0, 0xC($a1)
    /* 86550 800CBD50 ACA30008 */  sw         $v1, 0x8($a1)
    /* 86554 800CBD54 ACA80004 */  sw         $t0, 0x4($a1)
    /* 86558 800CBD58 1000FFF2 */  b          .L800CBD24
    /* 8655C 800CBD5C ACA90000 */   sw        $t1, 0x0($a1)
  .L800CBD60:
    /* 86560 800CBD60 28C10004 */  slti       $at, $a2, 0x4
  .L800CBD64:
    /* 86564 800CBD64 1420FFB3 */  bnez       $at, .L800CBC34
    /* 86568 800CBD68 00000000 */   nop
    /* 8656C 800CBD6C 8C82FFFC */  lw         $v0, -0x4($a0)
    /* 86570 800CBD70 2484FFFC */  addiu      $a0, $a0, -0x4
    /* 86574 800CBD74 24A5FFFC */  addiu      $a1, $a1, -0x4
    /* 86578 800CBD78 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* 8657C 800CBD7C 1000FFF8 */  b          .L800CBD60
    /* 86580 800CBD80 ACA20000 */   sw        $v0, 0x0($a1)
    /* 86584 800CBD84 00000000 */  nop
    /* 86588 800CBD88 00000000 */  nop
    /* 8658C 800CBD8C 00000000 */  nop

/* Handwritten function */
glabel osWritebackDCache
    /* 86590 800CBD90 18A00011 */  blez       $a1, .L800CBDD8
    /* 86594 800CBD94 00000000 */   nop
    /* 86598 800CBD98 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 8659C 800CBD9C 00AB082B */  sltu       $at, $a1, $t3
    /* 865A0 800CBDA0 1020000F */  beqz       $at, .L800CBDE0
    /* 865A4 800CBDA4 00000000 */   nop
    /* 865A8 800CBDA8 00804025 */  or         $t0, $a0, $zero
    /* 865AC 800CBDAC 00854821 */  addu       $t1, $a0, $a1
    /* 865B0 800CBDB0 0109082B */  sltu       $at, $t0, $t1
    /* 865B4 800CBDB4 10200008 */  beqz       $at, .L800CBDD8
    /* 865B8 800CBDB8 00000000 */   nop
    /* 865BC 800CBDBC 310A000F */  andi       $t2, $t0, 0xF
    /* 865C0 800CBDC0 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 865C4 800CBDC4 010A4023 */  subu       $t0, $t0, $t2
  .L800CBDC8:
    /* 865C8 800CBDC8 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* 865CC 800CBDCC 0109082B */  sltu       $at, $t0, $t1
    /* 865D0 800CBDD0 1420FFFD */  bnez       $at, .L800CBDC8
    /* 865D4 800CBDD4 25080010 */   addiu     $t0, $t0, 0x10
  .L800CBDD8:
    /* 865D8 800CBDD8 03E00008 */  jr         $ra
    /* 865DC 800CBDDC 00000000 */   nop
  .L800CBDE0:
    /* 865E0 800CBDE0 3C088000 */  lui        $t0, 0x8000
    /* 865E4 800CBDE4 010B4821 */  addu       $t1, $t0, $t3
    /* 865E8 800CBDE8 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800CBDEC:
    /* 865EC 800CBDEC BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 865F0 800CBDF0 0109082B */  sltu       $at, $t0, $t1
    /* 865F4 800CBDF4 1420FFFD */  bnez       $at, .L800CBDEC
    /* 865F8 800CBDF8 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 865FC 800CBDFC 03E00008 */  jr         $ra
    /* 86600 800CBE00 00000000 */   nop
    /* 86604 800CBE04 00000000 */  nop
    /* 86608 800CBE08 00000000 */  nop
    /* 8660C 800CBE0C 00000000 */  nop
