.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800CBE10
    /* 86610 800CBE10 3C0EA404 */  lui        $t6, %hi(D_A4040010)
    /* 86614 800CBE14 8DC50010 */  lw         $a1, %lo(D_A4040010)($t6)
    /* 86618 800CBE18 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 8661C 800CBE1C 30AF0001 */  andi       $t7, $a1, 0x1
    /* 86620 800CBE20 15E00003 */  bnez       $t7, .L800CBE30
    /* 86624 800CBE24 00000000 */   nop
    /* 86628 800CBE28 10000004 */  b          .L800CBE3C
    /* 8662C 800CBE2C 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800CBE30:
    /* 86630 800CBE30 3C18A408 */  lui        $t8, %hi(D_A4080000)
    /* 86634 800CBE34 AF040000 */  sw         $a0, %lo(D_A4080000)($t8)
    /* 86638 800CBE38 00001025 */  or         $v0, $zero, $zero
  .L800CBE3C:
    /* 8663C 800CBE3C 03E00008 */  jr         $ra
    /* 86640 800CBE40 27BD0008 */   addiu     $sp, $sp, 0x8
    /* 86644 800CBE44 00000000 */  nop
    /* 86648 800CBE48 00000000 */  nop
    /* 8664C 800CBE4C 00000000 */  nop
