.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800CBE50
    /* 86650 800CBE50 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 86654 800CBE54 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 86658 800CBE58 AFA40018 */  sw         $a0, 0x18($sp)
    /* 8665C 800CBE5C AFA5001C */  sw         $a1, 0x1C($sp)
    /* 86660 800CBE60 AFA60020 */  sw         $a2, 0x20($sp)
    /* 86664 800CBE64 0C032FB8 */  jal        __osSpDeviceBusy
    /* 86668 800CBE68 AFA70024 */   sw        $a3, 0x24($sp)
    /* 8666C 800CBE6C 10400003 */  beqz       $v0, .L800CBE7C
    /* 86670 800CBE70 00000000 */   nop
    /* 86674 800CBE74 10000015 */  b          .L800CBECC
    /* 86678 800CBE78 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800CBE7C:
    /* 8667C 800CBE7C 8FAE001C */  lw         $t6, 0x1C($sp)
    /* 86680 800CBE80 3C0FA404 */  lui        $t7, %hi(D_A4040000)
    /* 86684 800CBE84 ADEE0000 */  sw         $t6, %lo(D_A4040000)($t7)
    /* 86688 800CBE88 0C0315C8 */  jal        osVirtualToPhysical
    /* 8668C 800CBE8C 8FA40020 */   lw        $a0, 0x20($sp)
    /* 86690 800CBE90 3C18A404 */  lui        $t8, %hi(D_A4040004)
    /* 86694 800CBE94 AF020004 */  sw         $v0, %lo(D_A4040004)($t8)
    /* 86698 800CBE98 8FB90018 */  lw         $t9, 0x18($sp)
    /* 8669C 800CBE9C 17200006 */  bnez       $t9, .L800CBEB8
    /* 866A0 800CBEA0 00000000 */   nop
    /* 866A4 800CBEA4 8FA80024 */  lw         $t0, 0x24($sp)
    /* 866A8 800CBEA8 3C0AA404 */  lui        $t2, %hi(D_A404000C)
    /* 866AC 800CBEAC 2509FFFF */  addiu      $t1, $t0, -0x1
    /* 866B0 800CBEB0 10000005 */  b          .L800CBEC8
    /* 866B4 800CBEB4 AD49000C */   sw        $t1, %lo(D_A404000C)($t2)
  .L800CBEB8:
    /* 866B8 800CBEB8 8FAB0024 */  lw         $t3, 0x24($sp)
    /* 866BC 800CBEBC 3C0DA404 */  lui        $t5, %hi(D_A4040008)
    /* 866C0 800CBEC0 256CFFFF */  addiu      $t4, $t3, -0x1
    /* 866C4 800CBEC4 ADAC0008 */  sw         $t4, %lo(D_A4040008)($t5)
  .L800CBEC8:
    /* 866C8 800CBEC8 00001025 */  or         $v0, $zero, $zero
  .L800CBECC:
    /* 866CC 800CBECC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 866D0 800CBED0 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 866D4 800CBED4 03E00008 */  jr         $ra
    /* 866D8 800CBED8 00000000 */   nop
    /* 866DC 800CBEDC 00000000 */  nop
