.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800CBF10
    /* 86710 800CBF10 3C0EA404 */  lui        $t6, %hi(D_A4040010)
    /* 86714 800CBF14 03E00008 */  jr         $ra
    /* 86718 800CBF18 8DC20010 */   lw        $v0, %lo(D_A4040010)($t6)
    /* 8671C 800CBF1C 00000000 */  nop
