.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel osGetThreadPri
    /* 86720 800CBF20 14800003 */  bnez       $a0, .L800CBF30
    /* 86724 800CBF24 00000000 */   nop
    /* 86728 800CBF28 3C04800F */  lui        $a0, %hi(__osRunningThread)
    /* 8672C 800CBF2C 8C849010 */  lw         $a0, %lo(__osRunningThread)($a0)
  .L800CBF30:
    /* 86730 800CBF30 03E00008 */  jr         $ra
    /* 86734 800CBF34 8C820004 */   lw        $v0, 0x4($a0)
    /* 86738 800CBF38 00000000 */  nop
    /* 8673C 800CBF3C 00000000 */  nop
