.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800CBF50
    /* 86750 800CBF50 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 86754 800CBF54 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 86758 800CBF58 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 8675C 800CBF5C AFB20020 */  sw         $s2, 0x20($sp)
    /* 86760 800CBF60 AFB00018 */  sw         $s0, 0x18($sp)
    /* 86764 800CBF64 AFA00030 */  sw         $zero, 0x30($sp)
    /* 86768 800CBF68 3C11800F */  lui        $s1, %hi(__osViNext)
    /* 8676C 800CBF6C 3C0EA440 */  lui        $t6, %hi(D_A4400010)
    /* 86770 800CBF70 8E3190B4 */  lw         $s1, %lo(__osViNext)($s1)
    /* 86774 800CBF74 8DCF0010 */  lw         $t7, %lo(D_A4400010)($t6)
    /* 86778 800CBF78 8E300008 */  lw         $s0, 0x8($s1)
    /* 8677C 800CBF7C 31F80001 */  andi       $t8, $t7, 0x1
    /* 86780 800CBF80 AFB80030 */  sw         $t8, 0x30($sp)
    /* 86784 800CBF84 0C0315C8 */  jal        osVirtualToPhysical
    /* 86788 800CBF88 8E240004 */   lw        $a0, 0x4($s1)
    /* 8678C 800CBF8C 8FB90030 */  lw         $t9, 0x30($sp)
    /* 86790 800CBF90 00409025 */  or         $s2, $v0, $zero
    /* 86794 800CBF94 00194080 */  sll        $t0, $t9, 2
    /* 86798 800CBF98 01194021 */  addu       $t0, $t0, $t9
    /* 8679C 800CBF9C 00084080 */  sll        $t0, $t0, 2
    /* 867A0 800CBFA0 02084821 */  addu       $t1, $s0, $t0
    /* 867A4 800CBFA4 8D2A0028 */  lw         $t2, 0x28($t1)
    /* 867A8 800CBFA8 01525821 */  addu       $t3, $t2, $s2
    /* 867AC 800CBFAC AFAB003C */  sw         $t3, 0x3C($sp)
    /* 867B0 800CBFB0 962C0000 */  lhu        $t4, 0x0($s1)
    /* 867B4 800CBFB4 318D0002 */  andi       $t5, $t4, 0x2
    /* 867B8 800CBFB8 11A00008 */  beqz       $t5, .L800CBFDC
    /* 867BC 800CBFBC 00000000 */   nop
    /* 867C0 800CBFC0 8E0F0020 */  lw         $t7, 0x20($s0)
    /* 867C4 800CBFC4 8E2E0020 */  lw         $t6, 0x20($s1)
    /* 867C8 800CBFC8 2401F000 */  addiu      $at, $zero, -0x1000
    /* 867CC 800CBFCC 01E1C024 */  and        $t8, $t7, $at
    /* 867D0 800CBFD0 01D8C825 */  or         $t9, $t6, $t8
    /* 867D4 800CBFD4 10000003 */  b          .L800CBFE4
    /* 867D8 800CBFD8 AE390020 */   sw        $t9, 0x20($s1)
  .L800CBFDC:
    /* 867DC 800CBFDC 8E080020 */  lw         $t0, 0x20($s0)
    /* 867E0 800CBFE0 AE280020 */  sw         $t0, 0x20($s1)
  .L800CBFE4:
    /* 867E4 800CBFE4 96290000 */  lhu        $t1, 0x0($s1)
    /* 867E8 800CBFE8 312A0004 */  andi       $t2, $t1, 0x4
    /* 867EC 800CBFEC 11400041 */  beqz       $t2, .L800CC0F4
    /* 867F0 800CBFF0 00000000 */   nop
    /* 867F4 800CBFF4 8FAB0030 */  lw         $t3, 0x30($sp)
    /* 867F8 800CBFF8 000B6080 */  sll        $t4, $t3, 2
    /* 867FC 800CBFFC 018B6021 */  addu       $t4, $t4, $t3
    /* 86800 800CC000 000C6080 */  sll        $t4, $t4, 2
    /* 86804 800CC004 020C6821 */  addu       $t5, $s0, $t4
    /* 86808 800CC008 8DAF002C */  lw         $t7, 0x2C($t5)
    /* 8680C 800CC00C 31EE0FFF */  andi       $t6, $t7, 0xFFF
    /* 86810 800CC010 448E3000 */  mtc1       $t6, $f6
    /* 86814 800CC014 AFAE0034 */  sw         $t6, 0x34($sp)
    /* 86818 800CC018 C6240024 */  lwc1       $f4, 0x24($s1)
    /* 8681C 800CC01C 05C10005 */  bgez       $t6, .L800CC034
    /* 86820 800CC020 46803220 */   cvt.s.w   $f8, $f6
    /* 86824 800CC024 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 86828 800CC028 44815000 */  mtc1       $at, $f10
    /* 8682C 800CC02C 00000000 */  nop
    /* 86830 800CC030 460A4200 */  add.s      $f8, $f8, $f10
  .L800CC034:
    /* 86834 800CC034 46082402 */  mul.s      $f16, $f4, $f8
    /* 86838 800CC038 24190001 */  addiu      $t9, $zero, 0x1
    /* 8683C 800CC03C 4458F800 */  cfc1       $t8, $31
    /* 86840 800CC040 44D9F800 */  ctc1       $t9, $31
    /* 86844 800CC044 00000000 */  nop
    /* 86848 800CC048 460084A4 */  cvt.w.s    $f18, $f16
    /* 8684C 800CC04C 4459F800 */  cfc1       $t9, $31
    /* 86850 800CC050 00000000 */  nop
    /* 86854 800CC054 33210004 */  andi       $at, $t9, 0x4
    /* 86858 800CC058 33390078 */  andi       $t9, $t9, 0x78
    /* 8685C 800CC05C 13200013 */  beqz       $t9, .L800CC0AC
    /* 86860 800CC060 3C014F00 */   lui       $at, (0x4F000000 >> 16)
    /* 86864 800CC064 44819000 */  mtc1       $at, $f18
    /* 86868 800CC068 24190001 */  addiu      $t9, $zero, 0x1
    /* 8686C 800CC06C 46128481 */  sub.s      $f18, $f16, $f18
    /* 86870 800CC070 44D9F800 */  ctc1       $t9, $31
    /* 86874 800CC074 00000000 */  nop
    /* 86878 800CC078 460094A4 */  cvt.w.s    $f18, $f18
    /* 8687C 800CC07C 4459F800 */  cfc1       $t9, $31
    /* 86880 800CC080 00000000 */  nop
    /* 86884 800CC084 33210004 */  andi       $at, $t9, 0x4
    /* 86888 800CC088 33390078 */  andi       $t9, $t9, 0x78
    /* 8688C 800CC08C 17200005 */  bnez       $t9, .L800CC0A4
    /* 86890 800CC090 00000000 */   nop
    /* 86894 800CC094 44199000 */  mfc1       $t9, $f18
    /* 86898 800CC098 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 8689C 800CC09C 10000007 */  b          .L800CC0BC
    /* 868A0 800CC0A0 0321C825 */   or        $t9, $t9, $at
  .L800CC0A4:
    /* 868A4 800CC0A4 10000005 */  b          .L800CC0BC
    /* 868A8 800CC0A8 2419FFFF */   addiu     $t9, $zero, -0x1
  .L800CC0AC:
    /* 868AC 800CC0AC 44199000 */  mfc1       $t9, $f18
    /* 868B0 800CC0B0 00000000 */  nop
    /* 868B4 800CC0B4 0720FFFB */  bltz       $t9, .L800CC0A4
    /* 868B8 800CC0B8 00000000 */   nop
  .L800CC0BC:
    /* 868BC 800CC0BC AE39002C */  sw         $t9, 0x2C($s1)
    /* 868C0 800CC0C0 8FA90030 */  lw         $t1, 0x30($sp)
    /* 868C4 800CC0C4 8E28002C */  lw         $t0, 0x2C($s1)
    /* 868C8 800CC0C8 2401F000 */  addiu      $at, $zero, -0x1000
    /* 868CC 800CC0CC 00095080 */  sll        $t2, $t1, 2
    /* 868D0 800CC0D0 01495021 */  addu       $t2, $t2, $t1
    /* 868D4 800CC0D4 000A5080 */  sll        $t2, $t2, 2
    /* 868D8 800CC0D8 020A5821 */  addu       $t3, $s0, $t2
    /* 868DC 800CC0DC 8D6C002C */  lw         $t4, 0x2C($t3)
    /* 868E0 800CC0E0 44D8F800 */  ctc1       $t8, $31
    /* 868E4 800CC0E4 01816824 */  and        $t5, $t4, $at
    /* 868E8 800CC0E8 010D7825 */  or         $t7, $t0, $t5
    /* 868EC 800CC0EC 10000008 */  b          .L800CC110
    /* 868F0 800CC0F0 AE2F002C */   sw        $t7, 0x2C($s1)
  .L800CC0F4:
    /* 868F4 800CC0F4 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 868F8 800CC0F8 000EC080 */  sll        $t8, $t6, 2
    /* 868FC 800CC0FC 030EC021 */  addu       $t8, $t8, $t6
    /* 86900 800CC100 0018C080 */  sll        $t8, $t8, 2
    /* 86904 800CC104 0218C821 */  addu       $t9, $s0, $t8
    /* 86908 800CC108 8F29002C */  lw         $t1, 0x2C($t9)
    /* 8690C 800CC10C AE29002C */  sw         $t1, 0x2C($s1)
  .L800CC110:
    /* 86910 800CC110 8E0A001C */  lw         $t2, 0x1C($s0)
    /* 86914 800CC114 AFAA0038 */  sw         $t2, 0x38($sp)
    /* 86918 800CC118 962B0000 */  lhu        $t3, 0x0($s1)
    /* 8691C 800CC11C 316C0020 */  andi       $t4, $t3, 0x20
    /* 86920 800CC120 11800002 */  beqz       $t4, .L800CC12C
    /* 86924 800CC124 00000000 */   nop
    /* 86928 800CC128 AFA00038 */  sw         $zero, 0x38($sp)
  .L800CC12C:
    /* 8692C 800CC12C 96280000 */  lhu        $t0, 0x0($s1)
    /* 86930 800CC130 310D0040 */  andi       $t5, $t0, 0x40
    /* 86934 800CC134 11A00005 */  beqz       $t5, .L800CC14C
    /* 86938 800CC138 00000000 */   nop
    /* 8693C 800CC13C AE20002C */  sw         $zero, 0x2C($s1)
    /* 86940 800CC140 0C0315C8 */  jal        osVirtualToPhysical
    /* 86944 800CC144 8E240004 */   lw        $a0, 0x4($s1)
    /* 86948 800CC148 AFA2003C */  sw         $v0, 0x3C($sp)
  .L800CC14C:
    /* 8694C 800CC14C 962F0000 */  lhu        $t7, 0x0($s1)
    /* 86950 800CC150 31EE0080 */  andi       $t6, $t7, 0x80
    /* 86954 800CC154 11C00009 */  beqz       $t6, .L800CC17C
    /* 86958 800CC158 00000000 */   nop
    /* 8695C 800CC15C 96380028 */  lhu        $t8, 0x28($s1)
    /* 86960 800CC160 3C0103FF */  lui        $at, (0x3FF0000 >> 16)
    /* 86964 800CC164 8E240004 */  lw         $a0, 0x4($s1)
    /* 86968 800CC168 0018CC00 */  sll        $t9, $t8, 16
    /* 8696C 800CC16C 03214824 */  and        $t1, $t9, $at
    /* 86970 800CC170 0C0315C8 */  jal        osVirtualToPhysical
    /* 86974 800CC174 AE29002C */   sw        $t1, 0x2C($s1)
    /* 86978 800CC178 AFA2003C */  sw         $v0, 0x3C($sp)
  .L800CC17C:
    /* 8697C 800CC17C 8FAA003C */  lw         $t2, 0x3C($sp)
    /* 86980 800CC180 3C0BA440 */  lui        $t3, %hi(D_A4400004)
    /* 86984 800CC184 3C08A440 */  lui        $t0, %hi(D_A4400008)
    /* 86988 800CC188 AD6A0004 */  sw         $t2, %lo(D_A4400004)($t3)
    /* 8698C 800CC18C 8E0C0008 */  lw         $t4, 0x8($s0)
    /* 86990 800CC190 3C0FA440 */  lui        $t7, %hi(D_A4400014)
    /* 86994 800CC194 3C18A440 */  lui        $t8, %hi(D_A4400018)
    /* 86998 800CC198 AD0C0008 */  sw         $t4, %lo(D_A4400008)($t0)
    /* 8699C 800CC19C 8E0D000C */  lw         $t5, 0xC($s0)
    /* 869A0 800CC1A0 3C09A440 */  lui        $t1, %hi(D_A440001C)
    /* 869A4 800CC1A4 3C01800F */  lui        $at, %hi(__osViNext)
    /* 869A8 800CC1A8 ADED0014 */  sw         $t5, %lo(D_A4400014)($t7)
    /* 869AC 800CC1AC 8E0E0010 */  lw         $t6, 0x10($s0)
    /* 869B0 800CC1B0 AF0E0018 */  sw         $t6, %lo(D_A4400018)($t8)
    /* 869B4 800CC1B4 8E190014 */  lw         $t9, 0x14($s0)
    /* 869B8 800CC1B8 AD39001C */  sw         $t9, %lo(D_A440001C)($t1)
    /* 869BC 800CC1BC 8E0A0018 */  lw         $t2, 0x18($s0)
    /* 869C0 800CC1C0 3C19A440 */  lui        $t9, %hi(D_A4400028)
    /* 869C4 800CC1C4 AD6A0020 */  sw         $t2, %lo(D_A4400020)($t3)
    /* 869C8 800CC1C8 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 869CC 800CC1CC AD0C0024 */  sw         $t4, %lo(D_A4400024)($t0)
    /* 869D0 800CC1D0 8FAD0030 */  lw         $t5, 0x30($sp)
    /* 869D4 800CC1D4 000D7880 */  sll        $t7, $t5, 2
    /* 869D8 800CC1D8 01ED7821 */  addu       $t7, $t7, $t5
    /* 869DC 800CC1DC 000F7880 */  sll        $t7, $t7, 2
    /* 869E0 800CC1E0 020F7021 */  addu       $t6, $s0, $t7
    /* 869E4 800CC1E4 8DD80030 */  lw         $t8, 0x30($t6)
    /* 869E8 800CC1E8 AF380028 */  sw         $t8, %lo(D_A4400028)($t9)
    /* 869EC 800CC1EC 8FA90030 */  lw         $t1, 0x30($sp)
    /* 869F0 800CC1F0 00095080 */  sll        $t2, $t1, 2
    /* 869F4 800CC1F4 01495021 */  addu       $t2, $t2, $t1
    /* 869F8 800CC1F8 000A5080 */  sll        $t2, $t2, 2
    /* 869FC 800CC1FC 020A5821 */  addu       $t3, $s0, $t2
    /* 86A00 800CC200 8D6C0034 */  lw         $t4, 0x34($t3)
    /* 86A04 800CC204 3C0AA440 */  lui        $t2, %hi(D_A4400030)
    /* 86A08 800CC208 AD0C002C */  sw         $t4, %lo(D_A440002C)($t0)
    /* 86A0C 800CC20C 8FAD0030 */  lw         $t5, 0x30($sp)
    /* 86A10 800CC210 3C0CA440 */  lui        $t4, %hi(D_A4400034)
    /* 86A14 800CC214 000D7880 */  sll        $t7, $t5, 2
    /* 86A18 800CC218 01ED7821 */  addu       $t7, $t7, $t5
    /* 86A1C 800CC21C 000F7880 */  sll        $t7, $t7, 2
    /* 86A20 800CC220 020F7021 */  addu       $t6, $s0, $t7
    /* 86A24 800CC224 8DD80038 */  lw         $t8, 0x38($t6)
    /* 86A28 800CC228 3C0DA440 */  lui        $t5, %hi(D_A4400000)
    /* 86A2C 800CC22C 3C0F800F */  lui        $t7, %hi(osRomType)
    /* 86A30 800CC230 AF38000C */  sw         $t8, %lo(D_A440000C)($t9)
    /* 86A34 800CC234 8E290020 */  lw         $t1, 0x20($s1)
    /* 86A38 800CC238 3C18800F */  lui        $t8, %hi(osRomType)
    /* 86A3C 800CC23C 3C0E800F */  lui        $t6, %hi(__osViNext)
    /* 86A40 800CC240 AD490030 */  sw         $t1, %lo(D_A4400030)($t2)
    /* 86A44 800CC244 8E2B002C */  lw         $t3, 0x2C($s1)
    /* 86A48 800CC248 AD8B0034 */  sw         $t3, %lo(D_A4400034)($t4)
    /* 86A4C 800CC24C 8E28000C */  lw         $t0, 0xC($s1)
    /* 86A50 800CC250 ADA80000 */  sw         $t0, %lo(D_A4400000)($t5)
    /* 86A54 800CC254 8DEF90B0 */  lw         $t7, %lo(osRomType)($t7)
    /* 86A58 800CC258 AC2F90B4 */  sw         $t7, %lo(__osViNext)($at)
    /* 86A5C 800CC25C 3C01800F */  lui        $at, %hi(osRomType)
    /* 86A60 800CC260 AC3190B0 */  sw         $s1, %lo(osRomType)($at)
    /* 86A64 800CC264 8F1890B0 */  lw         $t8, %lo(osRomType)($t8)
    /* 86A68 800CC268 8DCE90B4 */  lw         $t6, %lo(__osViNext)($t6)
    /* 86A6C 800CC26C 270A0030 */  addiu      $t2, $t8, 0x30
  .L800CC270:
    /* 86A70 800CC270 8F010000 */  lw         $at, 0x0($t8)
    /* 86A74 800CC274 2718000C */  addiu      $t8, $t8, 0xC
    /* 86A78 800CC278 25CE000C */  addiu      $t6, $t6, 0xC
    /* 86A7C 800CC27C ADC1FFF4 */  sw         $at, -0xC($t6)
    /* 86A80 800CC280 8F01FFF8 */  lw         $at, -0x8($t8)
    /* 86A84 800CC284 ADC1FFF8 */  sw         $at, -0x8($t6)
    /* 86A88 800CC288 8F01FFFC */  lw         $at, -0x4($t8)
    /* 86A8C 800CC28C 170AFFF8 */  bne        $t8, $t2, .L800CC270
    /* 86A90 800CC290 ADC1FFFC */   sw        $at, -0x4($t6)
    /* 86A94 800CC294 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 86A98 800CC298 8FB00018 */  lw         $s0, 0x18($sp)
    /* 86A9C 800CC29C 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 86AA0 800CC2A0 8FB20020 */  lw         $s2, 0x20($sp)
    /* 86AA4 800CC2A4 03E00008 */  jr         $ra
    /* 86AA8 800CC2A8 27BD0048 */   addiu     $sp, $sp, 0x48
    /* 86AAC 800CC2AC 00000000 */  nop
