.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel __osPiCreateAccessQueue
    /* 86AB0 800CC2B0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 86AB4 800CC2B4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 86AB8 800CC2B8 240E0001 */  addiu      $t6, $zero, 0x1
    /* 86ABC 800CC2BC 3C01800F */  lui        $at, %hi(gOsPiAccessQueueCreated)
    /* 86AC0 800CC2C0 3C04801E */  lui        $a0, %hi(__osPiAccessQueue)
    /* 86AC4 800CC2C4 3C05801E */  lui        $a1, %hi(D_801DAC90)
    /* 86AC8 800CC2C8 AC2E90D0 */  sw         $t6, %lo(gOsPiAccessQueueCreated)($at)
    /* 86ACC 800CC2CC 24A5AC90 */  addiu      $a1, $a1, %lo(D_801DAC90)
    /* 86AD0 800CC2D0 2484AC98 */  addiu      $a0, $a0, %lo(__osPiAccessQueue)
    /* 86AD4 800CC2D4 0C0318C4 */  jal        osCreateMesgQueue
    /* 86AD8 800CC2D8 24060001 */   addiu     $a2, $zero, 0x1
    /* 86ADC 800CC2DC 3C04801E */  lui        $a0, %hi(__osPiAccessQueue)
    /* 86AE0 800CC2E0 2484AC98 */  addiu      $a0, $a0, %lo(__osPiAccessQueue)
    /* 86AE4 800CC2E4 00002825 */  or         $a1, $zero, $zero
    /* 86AE8 800CC2E8 0C0315E8 */  jal        osSendMesg
    /* 86AEC 800CC2EC 00003025 */   or        $a2, $zero, $zero
    /* 86AF0 800CC2F0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 86AF4 800CC2F4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 86AF8 800CC2F8 03E00008 */  jr         $ra
    /* 86AFC 800CC2FC 00000000 */   nop

glabel func_800CC300
    /* 86B00 800CC300 3C0E800F */  lui        $t6, %hi(gOsPiAccessQueueCreated)
    /* 86B04 800CC304 8DCE90D0 */  lw         $t6, %lo(gOsPiAccessQueueCreated)($t6)
    /* 86B08 800CC308 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 86B0C 800CC30C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 86B10 800CC310 15C00003 */  bnez       $t6, .L800CC320
    /* 86B14 800CC314 00000000 */   nop
    /* 86B18 800CC318 0C0330AC */  jal        __osPiCreateAccessQueue
    /* 86B1C 800CC31C 00000000 */   nop
  .L800CC320:
    /* 86B20 800CC320 3C04801E */  lui        $a0, %hi(__osPiAccessQueue)
    /* 86B24 800CC324 2484AC98 */  addiu      $a0, $a0, %lo(__osPiAccessQueue)
    /* 86B28 800CC328 27A5001C */  addiu      $a1, $sp, 0x1C
    /* 86B2C 800CC32C 0C031718 */  jal        osRecvMesg
    /* 86B30 800CC330 24060001 */   addiu     $a2, $zero, 0x1
    /* 86B34 800CC334 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 86B38 800CC338 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 86B3C 800CC33C 03E00008 */  jr         $ra
    /* 86B40 800CC340 00000000 */   nop

glabel func_800CC344
    /* 86B44 800CC344 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 86B48 800CC348 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 86B4C 800CC34C 3C04801E */  lui        $a0, %hi(__osPiAccessQueue)
    /* 86B50 800CC350 2484AC98 */  addiu      $a0, $a0, %lo(__osPiAccessQueue)
    /* 86B54 800CC354 00002825 */  or         $a1, $zero, $zero
    /* 86B58 800CC358 0C0315E8 */  jal        osSendMesg
    /* 86B5C 800CC35C 00003025 */   or        $a2, $zero, $zero
    /* 86B60 800CC360 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 86B64 800CC364 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 86B68 800CC368 03E00008 */  jr         $ra
    /* 86B6C 800CC36C 00000000 */   nop
