.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800CC5F0
    /* 86DF0 800CC5F0 4442F800 */  cfc1       $v0, $31
    /* 86DF4 800CC5F4 44C4F800 */  ctc1       $a0, $31
    /* 86DF8 800CC5F8 03E00008 */  jr         $ra
    /* 86DFC 800CC5FC 00000000 */   nop

glabel func_800CC600
    /* 86E00 800CC600 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 86E04 800CC604 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 86E08 800CC608 AFA40018 */  sw         $a0, 0x18($sp)
    /* 86E0C 800CC60C 0C03438C */  jal        __osSiDeviceBusy
    /* 86E10 800CC610 AFA5001C */   sw        $a1, 0x1C($sp)
    /* 86E14 800CC614 10400003 */  beqz       $v0, .L800CC624
    /* 86E18 800CC618 00000000 */   nop
    /* 86E1C 800CC61C 10000008 */  b          .L800CC640
    /* 86E20 800CC620 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800CC624:
    /* 86E24 800CC624 8FAE0018 */  lw         $t6, 0x18($sp)
    /* 86E28 800CC628 3C01A000 */  lui        $at, %hi(D_A0000000)
    /* 86E2C 800CC62C 8FB9001C */  lw         $t9, 0x1C($sp)
    /* 86E30 800CC630 01C17825 */  or         $t7, $t6, $at
    /* 86E34 800CC634 8DF80000 */  lw         $t8, %lo(D_A0000000)($t7)
    /* 86E38 800CC638 00001025 */  or         $v0, $zero, $zero
    /* 86E3C 800CC63C AF380000 */  sw         $t8, 0x0($t9)
  .L800CC640:
    /* 86E40 800CC640 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 86E44 800CC644 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 86E48 800CC648 03E00008 */  jr         $ra
    /* 86E4C 800CC64C 00000000 */   nop

glabel func_800CC650
    /* 86E50 800CC650 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 86E54 800CC654 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 86E58 800CC658 AFA40018 */  sw         $a0, 0x18($sp)
    /* 86E5C 800CC65C 0C03438C */  jal        __osSiDeviceBusy
    /* 86E60 800CC660 AFA5001C */   sw        $a1, 0x1C($sp)
    /* 86E64 800CC664 10400003 */  beqz       $v0, .L800CC674
    /* 86E68 800CC668 00000000 */   nop
    /* 86E6C 800CC66C 10000007 */  b          .L800CC68C
    /* 86E70 800CC670 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800CC674:
    /* 86E74 800CC674 8FAF0018 */  lw         $t7, 0x18($sp)
    /* 86E78 800CC678 8FAE001C */  lw         $t6, 0x1C($sp)
    /* 86E7C 800CC67C 3C01A000 */  lui        $at, %hi(D_A0000000)
    /* 86E80 800CC680 01E1C025 */  or         $t8, $t7, $at
    /* 86E84 800CC684 00001025 */  or         $v0, $zero, $zero
    /* 86E88 800CC688 AF0E0000 */  sw         $t6, %lo(D_A0000000)($t8)
  .L800CC68C:
    /* 86E8C 800CC68C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 86E90 800CC690 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 86E94 800CC694 03E00008 */  jr         $ra
    /* 86E98 800CC698 00000000 */   nop
    /* 86E9C 800CC69C 00000000 */  nop
