.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800CC700
    /* 86F00 800CC700 3C0EA460 */  lui        $t6, %hi(D_A4600010)
    /* 86F04 800CC704 8DC60010 */  lw         $a2, %lo(D_A4600010)($t6)
    /* 86F08 800CC708 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 86F0C 800CC70C 30CF0003 */  andi       $t7, $a2, 0x3
    /* 86F10 800CC710 11E00006 */  beqz       $t7, .L800CC72C
    /* 86F14 800CC714 00000000 */   nop
  .L800CC718:
    /* 86F18 800CC718 3C18A460 */  lui        $t8, %hi(D_A4600010)
    /* 86F1C 800CC71C 8F060010 */  lw         $a2, %lo(D_A4600010)($t8)
    /* 86F20 800CC720 30D90003 */  andi       $t9, $a2, 0x3
    /* 86F24 800CC724 1720FFFC */  bnez       $t9, .L800CC718
    /* 86F28 800CC728 00000000 */   nop
  .L800CC72C:
    /* 86F2C 800CC72C 3C088000 */  lui        $t0, %hi(osRomBase)
    /* 86F30 800CC730 8D080308 */  lw         $t0, %lo(osRomBase)($t0)
    /* 86F34 800CC734 3C01A000 */  lui        $at, (0xA0000000 >> 16)
    /* 86F38 800CC738 00001025 */  or         $v0, $zero, $zero
    /* 86F3C 800CC73C 01044825 */  or         $t1, $t0, $a0
    /* 86F40 800CC740 01215025 */  or         $t2, $t1, $at
    /* 86F44 800CC744 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 86F48 800CC748 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 86F4C 800CC74C 03E00008 */  jr         $ra
    /* 86F50 800CC750 ACAB0000 */   sw        $t3, 0x0($a1)
    /* 86F54 800CC754 00000000 */  nop
    /* 86F58 800CC758 00000000 */  nop
    /* 86F5C 800CC75C 00000000 */  nop
