.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800CCB00
    /* 87300 800CCB00 3C014780 */  lui        $at, (0x47800000 >> 16)
    /* 87304 800CCB04 44810000 */  mtc1       $at, $f0
    /* 87308 800CCB08 00A01025 */  or         $v0, $a1, $zero
    /* 8730C 800CCB0C 24A30020 */  addiu      $v1, $a1, 0x20
    /* 87310 800CCB10 00003025 */  or         $a2, $zero, $zero
    /* 87314 800CCB14 00803825 */  or         $a3, $a0, $zero
    /* 87318 800CCB18 240C0004 */  addiu      $t4, $zero, 0x4
    /* 8731C 800CCB1C 240B0002 */  addiu      $t3, $zero, 0x2
    /* 87320 800CCB20 3C0AFFFF */  lui        $t2, (0xFFFF0000 >> 16)
  .L800CCB24:
    /* 87324 800CCB24 00002025 */  or         $a0, $zero, $zero
    /* 87328 800CCB28 00E04025 */  or         $t0, $a3, $zero
    /* 8732C 800CCB2C C50E0004 */  lwc1       $f14, 0x4($t0)
    /* 87330 800CCB30 24840001 */  addiu      $a0, $a0, 0x1
    /* 87334 800CCB34 C5120000 */  lwc1       $f18, 0x0($t0)
    /* 87338 800CCB38 46007402 */  mul.s      $f16, $f14, $f0
    /* 8733C 800CCB3C 108B0019 */  beq        $a0, $t3, .L800CCBA4
    /* 87340 800CCB40 00000000 */   nop
  .L800CCB44:
    /* 87344 800CCB44 46009382 */  mul.s      $f14, $f18, $f0
    /* 87348 800CCB48 24840001 */  addiu      $a0, $a0, 0x1
    /* 8734C 800CCB4C 24420004 */  addiu      $v0, $v0, 0x4
    /* 87350 800CCB50 24630004 */  addiu      $v1, $v1, 0x4
    /* 87354 800CCB54 25080008 */  addiu      $t0, $t0, 0x8
    /* 87358 800CCB58 4600830D */  trunc.w.s  $f12, $f16
    /* 8735C 800CCB5C 4600738D */  trunc.w.s  $f14, $f14
    /* 87360 800CCB60 44096000 */  mfc1       $t1, $f12
    /* 87364 800CCB64 44057000 */  mfc1       $a1, $f14
    /* 87368 800CCB68 0009CC03 */  sra        $t9, $t1, 16
    /* 8736C 800CCB6C 332DFFFF */  andi       $t5, $t9, 0xFFFF
    /* 87370 800CCB70 00AAC024 */  and        $t8, $a1, $t2
    /* 87374 800CCB74 030D7025 */  or         $t6, $t8, $t5
    /* 87378 800CCB78 00057C00 */  sll        $t7, $a1, 16
    /* 8737C 800CCB7C 01EAC824 */  and        $t9, $t7, $t2
    /* 87380 800CCB80 AC4EFFFC */  sw         $t6, -0x4($v0)
    /* 87384 800CCB84 3138FFFF */  andi       $t8, $t1, 0xFFFF
    /* 87388 800CCB88 03386825 */  or         $t5, $t9, $t8
    /* 8738C 800CCB8C AC6DFFFC */  sw         $t5, -0x4($v1)
    /* 87390 800CCB90 C50E0004 */  lwc1       $f14, 0x4($t0)
    /* 87394 800CCB94 C5120000 */  lwc1       $f18, 0x0($t0)
    /* 87398 800CCB98 46007402 */  mul.s      $f16, $f14, $f0
    /* 8739C 800CCB9C 148BFFE9 */  bne        $a0, $t3, .L800CCB44
    /* 873A0 800CCBA0 00000000 */   nop
  .L800CCBA4:
    /* 873A4 800CCBA4 46009382 */  mul.s      $f14, $f18, $f0
    /* 873A8 800CCBA8 25080008 */  addiu      $t0, $t0, 0x8
    /* 873AC 800CCBAC 24420004 */  addiu      $v0, $v0, 0x4
    /* 873B0 800CCBB0 24630004 */  addiu      $v1, $v1, 0x4
    /* 873B4 800CCBB4 4600830D */  trunc.w.s  $f12, $f16
    /* 873B8 800CCBB8 4600738D */  trunc.w.s  $f14, $f14
    /* 873BC 800CCBBC 44096000 */  mfc1       $t1, $f12
    /* 873C0 800CCBC0 44057000 */  mfc1       $a1, $f14
    /* 873C4 800CCBC4 0009CC03 */  sra        $t9, $t1, 16
    /* 873C8 800CCBC8 332DFFFF */  andi       $t5, $t9, 0xFFFF
    /* 873CC 800CCBCC 00AAC024 */  and        $t8, $a1, $t2
    /* 873D0 800CCBD0 030D7025 */  or         $t6, $t8, $t5
    /* 873D4 800CCBD4 00057C00 */  sll        $t7, $a1, 16
    /* 873D8 800CCBD8 01EAC824 */  and        $t9, $t7, $t2
    /* 873DC 800CCBDC 3138FFFF */  andi       $t8, $t1, 0xFFFF
    /* 873E0 800CCBE0 AC4EFFFC */  sw         $t6, -0x4($v0)
    /* 873E4 800CCBE4 03386825 */  or         $t5, $t9, $t8
    /* 873E8 800CCBE8 AC6DFFFC */  sw         $t5, -0x4($v1)
    /* 873EC 800CCBEC 24C60001 */  addiu      $a2, $a2, 0x1
    /* 873F0 800CCBF0 14CCFFCC */  bne        $a2, $t4, .L800CCB24
    /* 873F4 800CCBF4 24E70010 */   addiu     $a3, $a3, 0x10
    /* 873F8 800CCBF8 03E00008 */  jr         $ra
    /* 873FC 800CCBFC 00000000 */   nop

glabel guMtxIdentF
    /* 87400 800CCC00 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 87404 800CCC04 00801825 */  or         $v1, $a0, $zero
    /* 87408 800CCC08 44810000 */  mtc1       $at, $f0
    /* 8740C 800CCC0C 44801000 */  mtc1       $zero, $f2
    /* 87410 800CCC10 24040001 */  addiu      $a0, $zero, 0x1
    /* 87414 800CCC14 00001025 */  or         $v0, $zero, $zero
    /* 87418 800CCC18 24070004 */  addiu      $a3, $zero, 0x4
    /* 8741C 800CCC1C 24060003 */  addiu      $a2, $zero, 0x3
    /* 87420 800CCC20 24050002 */  addiu      $a1, $zero, 0x2
  .L800CCC24:
    /* 87424 800CCC24 54400004 */  bnel       $v0, $zero, .L800CCC38
    /* 87428 800CCC28 E4620000 */   swc1      $f2, 0x0($v1)
    /* 8742C 800CCC2C 10000002 */  b          .L800CCC38
    /* 87430 800CCC30 E4600000 */   swc1      $f0, 0x0($v1)
    /* 87434 800CCC34 E4620000 */  swc1       $f2, 0x0($v1)
  .L800CCC38:
    /* 87438 800CCC38 54440004 */  bnel       $v0, $a0, .L800CCC4C
    /* 8743C 800CCC3C E4620004 */   swc1      $f2, 0x4($v1)
    /* 87440 800CCC40 10000002 */  b          .L800CCC4C
    /* 87444 800CCC44 E4600004 */   swc1      $f0, 0x4($v1)
    /* 87448 800CCC48 E4620004 */  swc1       $f2, 0x4($v1)
  .L800CCC4C:
    /* 8744C 800CCC4C 54450004 */  bnel       $v0, $a1, .L800CCC60
    /* 87450 800CCC50 E4620008 */   swc1      $f2, 0x8($v1)
    /* 87454 800CCC54 10000002 */  b          .L800CCC60
    /* 87458 800CCC58 E4600008 */   swc1      $f0, 0x8($v1)
    /* 8745C 800CCC5C E4620008 */  swc1       $f2, 0x8($v1)
  .L800CCC60:
    /* 87460 800CCC60 54460004 */  bnel       $v0, $a2, .L800CCC74
    /* 87464 800CCC64 E462000C */   swc1      $f2, 0xC($v1)
    /* 87468 800CCC68 10000002 */  b          .L800CCC74
    /* 8746C 800CCC6C E460000C */   swc1      $f0, 0xC($v1)
    /* 87470 800CCC70 E462000C */  swc1       $f2, 0xC($v1)
  .L800CCC74:
    /* 87474 800CCC74 24420001 */  addiu      $v0, $v0, 0x1
    /* 87478 800CCC78 1447FFEA */  bne        $v0, $a3, .L800CCC24
    /* 8747C 800CCC7C 24630010 */   addiu     $v1, $v1, 0x10
    /* 87480 800CCC80 03E00008 */  jr         $ra
    /* 87484 800CCC84 00000000 */   nop

glabel func_800CCC88
    /* 87488 800CCC88 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* 8748C 800CCC8C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 87490 800CCC90 AFA40058 */  sw         $a0, 0x58($sp)
    /* 87494 800CCC94 0C033300 */  jal        guMtxIdentF
    /* 87498 800CCC98 27A40018 */   addiu     $a0, $sp, 0x18
    /* 8749C 800CCC9C 27A40018 */  addiu      $a0, $sp, 0x18
    /* 874A0 800CCCA0 0C0332C0 */  jal        func_800CCB00
    /* 874A4 800CCCA4 8FA50058 */   lw        $a1, 0x58($sp)
    /* 874A8 800CCCA8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 874AC 800CCCAC 27BD0058 */  addiu      $sp, $sp, 0x58
    /* 874B0 800CCCB0 03E00008 */  jr         $ra
    /* 874B4 800CCCB4 00000000 */   nop

glabel func_800CCCB8
    /* 874B8 800CCCB8 3C014780 */  lui        $at, (0x47800000 >> 16)
    /* 874BC 800CCCBC 44810000 */  mtc1       $at, $f0
    /* 874C0 800CCCC0 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 874C4 800CCCC4 00A01025 */  or         $v0, $a1, $zero
    /* 874C8 800CCCC8 24A30020 */  addiu      $v1, $a1, 0x20
    /* 874CC 800CCCCC 00003025 */  or         $a2, $zero, $zero
    /* 874D0 800CCCD0 00804025 */  or         $t0, $a0, $zero
    /* 874D4 800CCCD4 240C0004 */  addiu      $t4, $zero, 0x4
    /* 874D8 800CCCD8 240B0002 */  addiu      $t3, $zero, 0x2
    /* 874DC 800CCCDC 3C0AFFFF */  lui        $t2, (0xFFFF0000 >> 16)
  .L800CCCE0:
    /* 874E0 800CCCE0 00002025 */  or         $a0, $zero, $zero
    /* 874E4 800CCCE4 01004825 */  or         $t1, $t0, $zero
  .L800CCCE8:
    /* 874E8 800CCCE8 8C6E0000 */  lw         $t6, 0x0($v1)
    /* 874EC 800CCCEC 8C590000 */  lw         $t9, 0x0($v0)
    /* 874F0 800CCCF0 24840001 */  addiu      $a0, $a0, 0x1
    /* 874F4 800CCCF4 000E7C02 */  srl        $t7, $t6, 16
    /* 874F8 800CCCF8 31F8FFFF */  andi       $t8, $t7, 0xFFFF
    /* 874FC 800CCCFC 032A6824 */  and        $t5, $t9, $t2
    /* 87500 800CCD00 030D7025 */  or         $t6, $t8, $t5
    /* 87504 800CCD04 AFAE0004 */  sw         $t6, 0x4($sp)
    /* 87508 800CCD08 8C6F0000 */  lw         $t7, 0x0($v1)
    /* 8750C 800CCD0C 8C580000 */  lw         $t8, 0x0($v0)
    /* 87510 800CCD10 8FA50004 */  lw         $a1, 0x4($sp)
    /* 87514 800CCD14 31F9FFFF */  andi       $t9, $t7, 0xFFFF
    /* 87518 800CCD18 00186C00 */  sll        $t5, $t8, 16
    /* 8751C 800CCD1C 44859000 */  mtc1       $a1, $f18
    /* 87520 800CCD20 01AA7024 */  and        $t6, $t5, $t2
    /* 87524 800CCD24 032E3825 */  or         $a3, $t9, $t6
    /* 87528 800CCD28 468094A0 */  cvt.s.w    $f18, $f18
    /* 8752C 800CCD2C 44878000 */  mtc1       $a3, $f16
    /* 87530 800CCD30 AFA70000 */  sw         $a3, 0x0($sp)
    /* 87534 800CCD34 24420004 */  addiu      $v0, $v0, 0x4
    /* 87538 800CCD38 24630004 */  addiu      $v1, $v1, 0x4
    /* 8753C 800CCD3C 46808420 */  cvt.s.w    $f16, $f16
    /* 87540 800CCD40 25290008 */  addiu      $t1, $t1, 0x8
    /* 87544 800CCD44 46009483 */  div.s      $f18, $f18, $f0
    /* 87548 800CCD48 46008403 */  div.s      $f16, $f16, $f0
    /* 8754C 800CCD4C E532FFF8 */  swc1       $f18, -0x8($t1)
    /* 87550 800CCD50 148BFFE5 */  bne        $a0, $t3, .L800CCCE8
    /* 87554 800CCD54 E530FFFC */   swc1      $f16, -0x4($t1)
    /* 87558 800CCD58 24C60001 */  addiu      $a2, $a2, 0x1
    /* 8755C 800CCD5C 14CCFFE0 */  bne        $a2, $t4, .L800CCCE0
    /* 87560 800CCD60 25080010 */   addiu     $t0, $t0, 0x10
    /* 87564 800CCD64 03E00008 */  jr         $ra
    /* 87568 800CCD68 27BD0010 */   addiu     $sp, $sp, 0x10
    /* 8756C 800CCD6C 00000000 */  nop
