.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800CEFA0
    /* 897A0 800CEFA0 27BDFF78 */  addiu      $sp, $sp, -0x88
    /* 897A4 800CEFA4 8FAE0098 */  lw         $t6, 0x98($sp)
    /* 897A8 800CEFA8 AFB70034 */  sw         $s7, 0x34($sp)
    /* 897AC 800CEFAC AFB5002C */  sw         $s5, 0x2C($sp)
    /* 897B0 800CEFB0 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 897B4 800CEFB4 AFB00018 */  sw         $s0, 0x18($sp)
    /* 897B8 800CEFB8 24010001 */  addiu      $at, $zero, 0x1
    /* 897BC 800CEFBC 30D0FFFF */  andi       $s0, $a2, 0xFFFF
    /* 897C0 800CEFC0 00A08825 */  or         $s1, $a1, $zero
    /* 897C4 800CEFC4 0080B825 */  or         $s7, $a0, $zero
    /* 897C8 800CEFC8 AFBF003C */  sw         $ra, 0x3C($sp)
    /* 897CC 800CEFCC AFBE0038 */  sw         $fp, 0x38($sp)
    /* 897D0 800CEFD0 AFB60030 */  sw         $s6, 0x30($sp)
    /* 897D4 800CEFD4 AFB40028 */  sw         $s4, 0x28($sp)
    /* 897D8 800CEFD8 AFB30024 */  sw         $s3, 0x24($sp)
    /* 897DC 800CEFDC AFB20020 */  sw         $s2, 0x20($sp)
    /* 897E0 800CEFE0 AFA60090 */  sw         $a2, 0x90($sp)
    /* 897E4 800CEFE4 AFA70094 */  sw         $a3, 0x94($sp)
    /* 897E8 800CEFE8 11C10008 */  beq        $t6, $at, .L800CF00C
    /* 897EC 800CEFEC 24150002 */   addiu     $s5, $zero, 0x2
    /* 897F0 800CEFF0 2A010007 */  slti       $at, $s0, 0x7
    /* 897F4 800CEFF4 10200005 */  beqz       $at, .L800CF00C
    /* 897F8 800CEFF8 02001025 */   or        $v0, $s0, $zero
    /* 897FC 800CEFFC 10400003 */  beqz       $v0, .L800CF00C
    /* 89800 800CF000 00000000 */   nop
    /* 89804 800CF004 10000063 */  b          .L800CF194
    /* 89808 800CF008 00001025 */   or        $v0, $zero, $zero
  .L800CF00C:
    /* 8980C 800CF00C 0C032E54 */  jal        __osSiGetAccess
    /* 89810 800CF010 00000000 */   nop
    /* 89814 800CF014 240F0003 */  addiu      $t7, $zero, 0x3
    /* 89818 800CF018 3C01801E */  lui        $at, %hi(__osContLastCmd)
    /* 8981C 800CF01C 8FA60094 */  lw         $a2, 0x94($sp)
    /* 89820 800CF020 A02FABA0 */  sb         $t7, %lo(__osContLastCmd)($at)
    /* 89824 800CF024 02202025 */  or         $a0, $s1, $zero
    /* 89828 800CF028 0C033C71 */  jal        func_800CF1C4
    /* 8982C 800CF02C 3205FFFF */   andi      $a1, $s0, 0xFFFF
    /* 89830 800CF030 3C16801E */  lui        $s6, %hi(D_801DABF0)
    /* 89834 800CF034 26D6ABF0 */  addiu      $s6, $s6, %lo(D_801DABF0)
    /* 89838 800CF038 02C02825 */  or         $a1, $s6, $zero
    /* 8983C 800CF03C 0C032E70 */  jal        __osSiRawStartDma
    /* 89840 800CF040 24040001 */   addiu     $a0, $zero, 0x1
    /* 89844 800CF044 02E02025 */  or         $a0, $s7, $zero
    /* 89848 800CF048 00002825 */  or         $a1, $zero, $zero
    /* 8984C 800CF04C 0C031718 */  jal        osRecvMesg
    /* 89850 800CF050 24060001 */   addiu     $a2, $zero, 0x1
    /* 89854 800CF054 3C13801E */  lui        $s3, %hi(D_801DAC30)
    /* 89858 800CF058 2673AC30 */  addiu      $s3, $s3, %lo(D_801DAC30)
    /* 8985C 800CF05C 27BE0054 */  addiu      $fp, $sp, 0x54
    /* 89860 800CF060 241200FF */  addiu      $s2, $zero, 0xFF
  .L800CF064:
    /* 89864 800CF064 3C03801E */  lui        $v1, %hi(D_801DABF0)
    /* 89868 800CF068 2463ABF0 */  addiu      $v1, $v1, %lo(D_801DABF0)
    /* 8986C 800CF06C 02C08025 */  or         $s0, $s6, $zero
  .L800CF070:
    /* 89870 800CF070 24630004 */  addiu      $v1, $v1, 0x4
    /* 89874 800CF074 0073082B */  sltu       $at, $v1, $s3
    /* 89878 800CF078 1420FFFD */  bnez       $at, .L800CF070
    /* 8987C 800CF07C AC72FFFC */   sw        $s2, -0x4($v1)
    /* 89880 800CF080 AEC0003C */  sw         $zero, 0x3C($s6)
    /* 89884 800CF084 00002025 */  or         $a0, $zero, $zero
    /* 89888 800CF088 0C032E70 */  jal        __osSiRawStartDma
    /* 8988C 800CF08C 02C02825 */   or        $a1, $s6, $zero
    /* 89890 800CF090 02E02025 */  or         $a0, $s7, $zero
    /* 89894 800CF094 00002825 */  or         $a1, $zero, $zero
    /* 89898 800CF098 0C031718 */  jal        osRecvMesg
    /* 8989C 800CF09C 24060001 */   addiu     $a2, $zero, 0x1
    /* 898A0 800CF0A0 1220000D */  beqz       $s1, .L800CF0D8
    /* 898A4 800CF0A4 03C04825 */   or        $t1, $fp, $zero
    /* 898A8 800CF0A8 1A20000B */  blez       $s1, .L800CF0D8
    /* 898AC 800CF0AC 00001025 */   or        $v0, $zero, $zero
    /* 898B0 800CF0B0 32240003 */  andi       $a0, $s1, 0x3
    /* 898B4 800CF0B4 10800005 */  beqz       $a0, .L800CF0CC
    /* 898B8 800CF0B8 00801825 */   or        $v1, $a0, $zero
  .L800CF0BC:
    /* 898BC 800CF0BC 24420001 */  addiu      $v0, $v0, 0x1
    /* 898C0 800CF0C0 1462FFFE */  bne        $v1, $v0, .L800CF0BC
    /* 898C4 800CF0C4 26100001 */   addiu     $s0, $s0, 0x1
    /* 898C8 800CF0C8 10510003 */  beq        $v0, $s1, .L800CF0D8
  .L800CF0CC:
    /* 898CC 800CF0CC 24420004 */   addiu     $v0, $v0, 0x4
    /* 898D0 800CF0D0 1451FFFE */  bne        $v0, $s1, .L800CF0CC
    /* 898D4 800CF0D4 26100004 */   addiu     $s0, $s0, 0x4
  .L800CF0D8:
    /* 898D8 800CF0D8 02004025 */  or         $t0, $s0, $zero
    /* 898DC 800CF0DC 26190024 */  addiu      $t9, $s0, 0x24
  .L800CF0E0:
    /* 898E0 800CF0E0 89010000 */  lwl        $at, 0x0($t0)
    /* 898E4 800CF0E4 99010003 */  lwr        $at, 0x3($t0)
    /* 898E8 800CF0E8 2508000C */  addiu      $t0, $t0, 0xC
    /* 898EC 800CF0EC AD210000 */  sw         $at, 0x0($t1)
    /* 898F0 800CF0F0 8901FFF8 */  lwl        $at, -0x8($t0)
    /* 898F4 800CF0F4 9901FFFB */  lwr        $at, -0x5($t0)
    /* 898F8 800CF0F8 2529000C */  addiu      $t1, $t1, 0xC
    /* 898FC 800CF0FC AD21FFF8 */  sw         $at, -0x8($t1)
    /* 89900 800CF100 8901FFFC */  lwl        $at, -0x4($t0)
    /* 89904 800CF104 9901FFFF */  lwr        $at, -0x1($t0)
    /* 89908 800CF108 1519FFF5 */  bne        $t0, $t9, .L800CF0E0
    /* 8990C 800CF10C AD21FFFC */   sw        $at, -0x4($t1)
    /* 89910 800CF110 89010000 */  lwl        $at, 0x0($t0)
    /* 89914 800CF114 99010003 */  lwr        $at, 0x3($t0)
    /* 89918 800CF118 00000000 */  nop
    /* 8991C 800CF11C AD210000 */  sw         $at, 0x0($t1)
    /* 89920 800CF120 93A20056 */  lbu        $v0, 0x56($sp)
    /* 89924 800CF124 8FA40094 */  lw         $a0, 0x94($sp)
    /* 89928 800CF128 304A00C0 */  andi       $t2, $v0, 0xC0
    /* 8992C 800CF12C 000AA103 */  sra        $s4, $t2, 4
    /* 89930 800CF130 16800011 */  bnez       $s4, .L800CF178
    /* 89934 800CF134 24010004 */   addiu     $at, $zero, 0x4
    /* 89938 800CF138 0C0343C4 */  jal        func_800D0F10
    /* 8993C 800CF13C 00000000 */   nop
    /* 89940 800CF140 93AC007A */  lbu        $t4, 0x7A($sp)
    /* 89944 800CF144 02E02025 */  or         $a0, $s7, $zero
    /* 89948 800CF148 1182000B */  beq        $t4, $v0, .L800CF178
    /* 8994C 800CF14C 24010004 */   addiu     $at, $zero, 0x4
    /* 89950 800CF150 0C032262 */  jal        func_800C8988
    /* 89954 800CF154 02202825 */   or        $a1, $s1, $zero
    /* 89958 800CF158 10400005 */  beqz       $v0, .L800CF170
    /* 8995C 800CF15C 0040A025 */   or        $s4, $v0, $zero
    /* 89960 800CF160 0C032E65 */  jal        __osSiRelAccess
    /* 89964 800CF164 00000000 */   nop
    /* 89968 800CF168 1000000A */  b          .L800CF194
    /* 8996C 800CF16C 02801025 */   or        $v0, $s4, $zero
  .L800CF170:
    /* 89970 800CF170 24140004 */  addiu      $s4, $zero, 0x4
    /* 89974 800CF174 24010004 */  addiu      $at, $zero, 0x4
  .L800CF178:
    /* 89978 800CF178 16810003 */  bne        $s4, $at, .L800CF188
    /* 8997C 800CF17C 2AA20000 */   slti      $v0, $s5, 0x0
    /* 89980 800CF180 1040FFB8 */  beqz       $v0, .L800CF064
    /* 89984 800CF184 26B5FFFF */   addiu     $s5, $s5, -0x1
  .L800CF188:
    /* 89988 800CF188 0C032E65 */  jal        __osSiRelAccess
    /* 8998C 800CF18C 00000000 */   nop
    /* 89990 800CF190 02801025 */  or         $v0, $s4, $zero
  .L800CF194:
    /* 89994 800CF194 8FBF003C */  lw         $ra, 0x3C($sp)
    /* 89998 800CF198 8FB00018 */  lw         $s0, 0x18($sp)
    /* 8999C 800CF19C 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 899A0 800CF1A0 8FB20020 */  lw         $s2, 0x20($sp)
    /* 899A4 800CF1A4 8FB30024 */  lw         $s3, 0x24($sp)
    /* 899A8 800CF1A8 8FB40028 */  lw         $s4, 0x28($sp)
    /* 899AC 800CF1AC 8FB5002C */  lw         $s5, 0x2C($sp)
    /* 899B0 800CF1B0 8FB60030 */  lw         $s6, 0x30($sp)
    /* 899B4 800CF1B4 8FB70034 */  lw         $s7, 0x34($sp)
    /* 899B8 800CF1B8 8FBE0038 */  lw         $fp, 0x38($sp)
    /* 899BC 800CF1BC 03E00008 */  jr         $ra
    /* 899C0 800CF1C0 27BD0088 */   addiu     $sp, $sp, 0x88

glabel func_800CF1C4
    /* 899C4 800CF1C4 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* 899C8 800CF1C8 AFB00018 */  sw         $s0, 0x18($sp)
    /* 899CC 800CF1CC 00808025 */  or         $s0, $a0, $zero
    /* 899D0 800CF1D0 3C08801E */  lui        $t0, %hi(D_801DABF0)
    /* 899D4 800CF1D4 2508ABF0 */  addiu      $t0, $t0, %lo(D_801DABF0)
    /* 899D8 800CF1D8 3C04801E */  lui        $a0, %hi(D_801DAC30)
    /* 899DC 800CF1DC 3C02801E */  lui        $v0, %hi(D_801DABF0)
    /* 899E0 800CF1E0 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 899E4 800CF1E4 AFA5005C */  sw         $a1, 0x5C($sp)
    /* 899E8 800CF1E8 01001825 */  or         $v1, $t0, $zero
    /* 899EC 800CF1EC 2442ABF0 */  addiu      $v0, $v0, %lo(D_801DABF0)
    /* 899F0 800CF1F0 2484AC30 */  addiu      $a0, $a0, %lo(D_801DAC30)
  .L800CF1F4:
    /* 899F4 800CF1F4 24420004 */  addiu      $v0, $v0, 0x4
    /* 899F8 800CF1F8 0044082B */  sltu       $at, $v0, $a0
    /* 899FC 800CF1FC 1420FFFD */  bnez       $at, .L800CF1F4
    /* 89A00 800CF200 AC40FFFC */   sw        $zero, -0x4($v0)
    /* 89A04 800CF204 240E0001 */  addiu      $t6, $zero, 0x1
    /* 89A08 800CF208 240F00FF */  addiu      $t7, $zero, 0xFF
    /* 89A0C 800CF20C 24180023 */  addiu      $t8, $zero, 0x23
    /* 89A10 800CF210 24190001 */  addiu      $t9, $zero, 0x1
    /* 89A14 800CF214 24090003 */  addiu      $t1, $zero, 0x3
    /* 89A18 800CF218 97A4005E */  lhu        $a0, 0x5E($sp)
    /* 89A1C 800CF21C AD0E003C */  sw         $t6, 0x3C($t0)
    /* 89A20 800CF220 A3AF002C */  sb         $t7, 0x2C($sp)
    /* 89A24 800CF224 A3B8002D */  sb         $t8, 0x2D($sp)
    /* 89A28 800CF228 A3B9002E */  sb         $t9, 0x2E($sp)
    /* 89A2C 800CF22C A3A9002F */  sb         $t1, 0x2F($sp)
    /* 89A30 800CF230 AFA30054 */  sw         $v1, 0x54($sp)
    /* 89A34 800CF234 0C034398 */  jal        func_800D0E60
    /* 89A38 800CF238 AFA60060 */   sw        $a2, 0x60($sp)
    /* 89A3C 800CF23C 97AA005E */  lhu        $t2, 0x5E($sp)
    /* 89A40 800CF240 240D00FF */  addiu      $t5, $zero, 0xFF
    /* 89A44 800CF244 000A5940 */  sll        $t3, $t2, 5
    /* 89A48 800CF248 004B6025 */  or         $t4, $v0, $t3
    /* 89A4C 800CF24C 8FA30054 */  lw         $v1, 0x54($sp)
    /* 89A50 800CF250 8FA60060 */  lw         $a2, 0x60($sp)
    /* 89A54 800CF254 A7AC0030 */  sh         $t4, 0x30($sp)
    /* 89A58 800CF258 A3AD0052 */  sb         $t5, 0x52($sp)
    /* 89A5C 800CF25C 27A2004C */  addiu      $v0, $sp, 0x4C
    /* 89A60 800CF260 27A4002C */  addiu      $a0, $sp, 0x2C
  .L800CF264:
    /* 89A64 800CF264 90CE0000 */  lbu        $t6, 0x0($a2)
    /* 89A68 800CF268 24840001 */  addiu      $a0, $a0, 0x1
    /* 89A6C 800CF26C 0082082B */  sltu       $at, $a0, $v0
    /* 89A70 800CF270 24C60001 */  addiu      $a2, $a2, 0x1
    /* 89A74 800CF274 1420FFFB */  bnez       $at, .L800CF264
    /* 89A78 800CF278 A08E0005 */   sb        $t6, 0x5($a0)
    /* 89A7C 800CF27C 12000012 */  beqz       $s0, .L800CF2C8
    /* 89A80 800CF280 27AF002C */   addiu     $t7, $sp, 0x2C
    /* 89A84 800CF284 1A000010 */  blez       $s0, .L800CF2C8
    /* 89A88 800CF288 00003825 */   or        $a3, $zero, $zero
    /* 89A8C 800CF28C 32040003 */  andi       $a0, $s0, 0x3
    /* 89A90 800CF290 10800006 */  beqz       $a0, .L800CF2AC
    /* 89A94 800CF294 00801025 */   or        $v0, $a0, $zero
  .L800CF298:
    /* 89A98 800CF298 24E70001 */  addiu      $a3, $a3, 0x1
    /* 89A9C 800CF29C A0600000 */  sb         $zero, 0x0($v1)
    /* 89AA0 800CF2A0 1447FFFD */  bne        $v0, $a3, .L800CF298
    /* 89AA4 800CF2A4 24630001 */   addiu     $v1, $v1, 0x1
    /* 89AA8 800CF2A8 10F00007 */  beq        $a3, $s0, .L800CF2C8
  .L800CF2AC:
    /* 89AAC 800CF2AC 24E70004 */   addiu     $a3, $a3, 0x4
    /* 89AB0 800CF2B0 A0600001 */  sb         $zero, 0x1($v1)
    /* 89AB4 800CF2B4 A0600002 */  sb         $zero, 0x2($v1)
    /* 89AB8 800CF2B8 A0600003 */  sb         $zero, 0x3($v1)
    /* 89ABC 800CF2BC 24630004 */  addiu      $v1, $v1, 0x4
    /* 89AC0 800CF2C0 14F0FFFA */  bne        $a3, $s0, .L800CF2AC
    /* 89AC4 800CF2C4 A060FFFC */   sb        $zero, -0x4($v1)
  .L800CF2C8:
    /* 89AC8 800CF2C8 00604825 */  or         $t1, $v1, $zero
    /* 89ACC 800CF2CC 25F90024 */  addiu      $t9, $t7, 0x24
  .L800CF2D0:
    /* 89AD0 800CF2D0 8DE10000 */  lw         $at, 0x0($t7)
    /* 89AD4 800CF2D4 25EF000C */  addiu      $t7, $t7, 0xC
    /* 89AD8 800CF2D8 A9210000 */  swl        $at, 0x0($t1)
    /* 89ADC 800CF2DC B9210003 */  swr        $at, 0x3($t1)
    /* 89AE0 800CF2E0 8DE1FFF8 */  lw         $at, -0x8($t7)
    /* 89AE4 800CF2E4 2529000C */  addiu      $t1, $t1, 0xC
    /* 89AE8 800CF2E8 A921FFF8 */  swl        $at, -0x8($t1)
    /* 89AEC 800CF2EC B921FFFB */  swr        $at, -0x5($t1)
    /* 89AF0 800CF2F0 8DE1FFFC */  lw         $at, -0x4($t7)
    /* 89AF4 800CF2F4 00000000 */  nop
    /* 89AF8 800CF2F8 A921FFFC */  swl        $at, -0x4($t1)
    /* 89AFC 800CF2FC 15F9FFF4 */  bne        $t7, $t9, .L800CF2D0
    /* 89B00 800CF300 B921FFFF */   swr       $at, -0x1($t1)
    /* 89B04 800CF304 8DE10000 */  lw         $at, 0x0($t7)
    /* 89B08 800CF308 240A00FE */  addiu      $t2, $zero, 0xFE
    /* 89B0C 800CF30C A9210000 */  swl        $at, 0x0($t1)
    /* 89B10 800CF310 B9210003 */  swr        $at, 0x3($t1)
    /* 89B14 800CF314 A06A0028 */  sb         $t2, 0x28($v1)
    /* 89B18 800CF318 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 89B1C 800CF31C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 89B20 800CF320 24630028 */  addiu      $v1, $v1, 0x28
    /* 89B24 800CF324 03E00008 */  jr         $ra
    /* 89B28 800CF328 27BD0058 */   addiu     $sp, $sp, 0x58
    /* 89B2C 800CF32C 00000000 */  nop
