.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel _Printf
    /* 89B30 800CF330 27BDFF50 */  addiu      $sp, $sp, -0xB0
    /* 89B34 800CF334 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 89B38 800CF338 AFA400B0 */  sw         $a0, 0xB0($sp)
    /* 89B3C 800CF33C AFA500B4 */  sw         $a1, 0xB4($sp)
    /* 89B40 800CF340 AFA600B8 */  sw         $a2, 0xB8($sp)
    /* 89B44 800CF344 AFA700BC */  sw         $a3, 0xBC($sp)
    /* 89B48 800CF348 AFB00018 */  sw         $s0, 0x18($sp)
    /* 89B4C 800CF34C AFA000A4 */  sw         $zero, 0xA4($sp)
  .L800CF350:
    /* 89B50 800CF350 8FAE00B8 */  lw         $t6, 0xB8($sp)
    /* 89B54 800CF354 AFAE0074 */  sw         $t6, 0x74($sp)
    /* 89B58 800CF358 91CF0000 */  lbu        $t7, 0x0($t6)
    /* 89B5C 800CF35C 25D80001 */  addiu      $t8, $t6, 0x1
    /* 89B60 800CF360 AFB80074 */  sw         $t8, 0x74($sp)
    /* 89B64 800CF364 000F802A */  slt        $s0, $zero, $t7
    /* 89B68 800CF368 12000010 */  beqz       $s0, .L800CF3AC
    /* 89B6C 800CF36C A3AF0073 */   sb        $t7, 0x73($sp)
  .L800CF370:
    /* 89B70 800CF370 93B90073 */  lbu        $t9, 0x73($sp)
    /* 89B74 800CF374 24010025 */  addiu      $at, $zero, 0x25
    /* 89B78 800CF378 17210005 */  bne        $t9, $at, .L800CF390
    /* 89B7C 800CF37C 00000000 */   nop
    /* 89B80 800CF380 8FA80074 */  lw         $t0, 0x74($sp)
    /* 89B84 800CF384 2509FFFF */  addiu      $t1, $t0, -0x1
    /* 89B88 800CF388 10000008 */  b          .L800CF3AC
    /* 89B8C 800CF38C AFA90074 */   sw        $t1, 0x74($sp)
  .L800CF390:
    /* 89B90 800CF390 8FAA0074 */  lw         $t2, 0x74($sp)
    /* 89B94 800CF394 914B0000 */  lbu        $t3, 0x0($t2)
    /* 89B98 800CF398 254C0001 */  addiu      $t4, $t2, 0x1
    /* 89B9C 800CF39C AFAC0074 */  sw         $t4, 0x74($sp)
    /* 89BA0 800CF3A0 000B802A */  slt        $s0, $zero, $t3
    /* 89BA4 800CF3A4 1600FFF2 */  bnez       $s0, .L800CF370
    /* 89BA8 800CF3A8 A3AB0073 */   sb        $t3, 0x73($sp)
  .L800CF3AC:
    /* 89BAC 800CF3AC 8FAD0074 */  lw         $t5, 0x74($sp)
    /* 89BB0 800CF3B0 8FAF00B8 */  lw         $t7, 0xB8($sp)
    /* 89BB4 800CF3B4 01AF7023 */  subu       $t6, $t5, $t7
    /* 89BB8 800CF3B8 19C00013 */  blez       $t6, .L800CF408
    /* 89BBC 800CF3BC 00000000 */   nop
    /* 89BC0 800CF3C0 8FB900B0 */  lw         $t9, 0xB0($sp)
    /* 89BC4 800CF3C4 8FA400B4 */  lw         $a0, 0xB4($sp)
    /* 89BC8 800CF3C8 01E02825 */  or         $a1, $t7, $zero
    /* 89BCC 800CF3CC 0320F809 */  jalr       $t9
    /* 89BD0 800CF3D0 01C03025 */   or        $a2, $t6, $zero
    /* 89BD4 800CF3D4 AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 89BD8 800CF3D8 8FB800B4 */  lw         $t8, 0xB4($sp)
    /* 89BDC 800CF3DC 13000008 */  beqz       $t8, .L800CF400
    /* 89BE0 800CF3E0 00000000 */   nop
    /* 89BE4 800CF3E4 8FA80074 */  lw         $t0, 0x74($sp)
    /* 89BE8 800CF3E8 8FA900B8 */  lw         $t1, 0xB8($sp)
    /* 89BEC 800CF3EC 8FAA00A4 */  lw         $t2, 0xA4($sp)
    /* 89BF0 800CF3F0 01095823 */  subu       $t3, $t0, $t1
    /* 89BF4 800CF3F4 014B6021 */  addu       $t4, $t2, $t3
    /* 89BF8 800CF3F8 10000003 */  b          .L800CF408
    /* 89BFC 800CF3FC AFAC00A4 */   sw        $t4, 0xA4($sp)
  .L800CF400:
    /* 89C00 800CF400 100001D1 */  b          .L800CFB48
    /* 89C04 800CF404 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CF408:
    /* 89C08 800CF408 93AD0073 */  lbu        $t5, 0x73($sp)
    /* 89C0C 800CF40C 15A00003 */  bnez       $t5, .L800CF41C
    /* 89C10 800CF410 00000000 */   nop
    /* 89C14 800CF414 100001CC */  b          .L800CFB48
    /* 89C18 800CF418 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CF41C:
    /* 89C1C 800CF41C 8FAF0074 */  lw         $t7, 0x74($sp)
    /* 89C20 800CF420 AFA000A8 */  sw         $zero, 0xA8($sp)
    /* 89C24 800CF424 3C04800F */  lui        $a0, %hi(D_800EC654)
    /* 89C28 800CF428 25EE0001 */  addiu      $t6, $t7, 0x1
    /* 89C2C 800CF42C AFAE0074 */  sw         $t6, 0x74($sp)
    /* 89C30 800CF430 AFAE00B8 */  sw         $t6, 0xB8($sp)
    /* 89C34 800CF434 91C50000 */  lbu        $a1, 0x0($t6)
    /* 89C38 800CF438 0C034145 */  jal        func_800D0514
    /* 89C3C 800CF43C 2484C654 */   addiu     $a0, $a0, %lo(D_800EC654)
    /* 89C40 800CF440 AFA2006C */  sw         $v0, 0x6C($sp)
    /* 89C44 800CF444 8FB9006C */  lw         $t9, 0x6C($sp)
    /* 89C48 800CF448 13200017 */  beqz       $t9, .L800CF4A8
    /* 89C4C 800CF44C 00000000 */   nop
  .L800CF450:
    /* 89C50 800CF450 8FA8006C */  lw         $t0, 0x6C($sp)
    /* 89C54 800CF454 3C09800F */  lui        $t1, %hi(D_800EC654)
    /* 89C58 800CF458 2529C654 */  addiu      $t1, $t1, %lo(D_800EC654)
    /* 89C5C 800CF45C 01095023 */  subu       $t2, $t0, $t1
    /* 89C60 800CF460 000A5880 */  sll        $t3, $t2, 2
    /* 89C64 800CF464 3C0C800F */  lui        $t4, %hi(D_800EC65C)
    /* 89C68 800CF468 018B6021 */  addu       $t4, $t4, $t3
    /* 89C6C 800CF46C 8FAF0074 */  lw         $t7, 0x74($sp)
    /* 89C70 800CF470 8D8CC65C */  lw         $t4, %lo(D_800EC65C)($t4)
    /* 89C74 800CF474 8FB800A8 */  lw         $t8, 0xA8($sp)
    /* 89C78 800CF478 25EE0001 */  addiu      $t6, $t7, 0x1
    /* 89C7C 800CF47C AFAE0074 */  sw         $t6, 0x74($sp)
    /* 89C80 800CF480 030C6825 */  or         $t5, $t8, $t4
    /* 89C84 800CF484 3C04800F */  lui        $a0, %hi(D_800EC654)
    /* 89C88 800CF488 AFAD00A8 */  sw         $t5, 0xA8($sp)
    /* 89C8C 800CF48C 91C50000 */  lbu        $a1, 0x0($t6)
    /* 89C90 800CF490 0C034145 */  jal        func_800D0514
    /* 89C94 800CF494 2484C654 */   addiu     $a0, $a0, %lo(D_800EC654)
    /* 89C98 800CF498 AFA2006C */  sw         $v0, 0x6C($sp)
    /* 89C9C 800CF49C 8FB9006C */  lw         $t9, 0x6C($sp)
    /* 89CA0 800CF4A0 1720FFEB */  bnez       $t9, .L800CF450
    /* 89CA4 800CF4A4 00000000 */   nop
  .L800CF4A8:
    /* 89CA8 800CF4A8 8FA80074 */  lw         $t0, 0x74($sp)
    /* 89CAC 800CF4AC 2401002A */  addiu      $at, $zero, 0x2A
    /* 89CB0 800CF4B0 91090000 */  lbu        $t1, 0x0($t0)
    /* 89CB4 800CF4B4 15210013 */  bne        $t1, $at, .L800CF504
    /* 89CB8 800CF4B8 00000000 */   nop
    /* 89CBC 800CF4BC 8FAA00BC */  lw         $t2, 0xBC($sp)
    /* 89CC0 800CF4C0 2401FFFC */  addiu      $at, $zero, -0x4
    /* 89CC4 800CF4C4 254B0003 */  addiu      $t3, $t2, 0x3
    /* 89CC8 800CF4C8 0161C024 */  and        $t8, $t3, $at
    /* 89CCC 800CF4CC 270C0004 */  addiu      $t4, $t8, 0x4
    /* 89CD0 800CF4D0 AFAC00BC */  sw         $t4, 0xBC($sp)
    /* 89CD4 800CF4D4 8F0D0000 */  lw         $t5, 0x0($t8)
    /* 89CD8 800CF4D8 05A10006 */  bgez       $t5, .L800CF4F4
    /* 89CDC 800CF4DC AFAD00A0 */   sw        $t5, 0xA0($sp)
    /* 89CE0 800CF4E0 8FAE00A8 */  lw         $t6, 0xA8($sp)
    /* 89CE4 800CF4E4 000D7823 */  negu       $t7, $t5
    /* 89CE8 800CF4E8 AFAF00A0 */  sw         $t7, 0xA0($sp)
    /* 89CEC 800CF4EC 35D90004 */  ori        $t9, $t6, 0x4
    /* 89CF0 800CF4F0 AFB900A8 */  sw         $t9, 0xA8($sp)
  .L800CF4F4:
    /* 89CF4 800CF4F4 8FA80074 */  lw         $t0, 0x74($sp)
    /* 89CF8 800CF4F8 25090001 */  addiu      $t1, $t0, 0x1
    /* 89CFC 800CF4FC 1000001E */  b          .L800CF578
    /* 89D00 800CF500 AFA90074 */   sw        $t1, 0x74($sp)
  .L800CF504:
    /* 89D04 800CF504 8FAA0074 */  lw         $t2, 0x74($sp)
    /* 89D08 800CF508 AFA000A0 */  sw         $zero, 0xA0($sp)
    /* 89D0C 800CF50C 914B0000 */  lbu        $t3, 0x0($t2)
    /* 89D10 800CF510 29610030 */  slti       $at, $t3, 0x30
    /* 89D14 800CF514 14200018 */  bnez       $at, .L800CF578
    /* 89D18 800CF518 2961003A */   slti      $at, $t3, 0x3A
    /* 89D1C 800CF51C 10200016 */  beqz       $at, .L800CF578
    /* 89D20 800CF520 00000000 */   nop
  .L800CF524:
    /* 89D24 800CF524 8FAC00A0 */  lw         $t4, 0xA0($sp)
    /* 89D28 800CF528 298103E7 */  slti       $at, $t4, 0x3E7
    /* 89D2C 800CF52C 10200009 */  beqz       $at, .L800CF554
    /* 89D30 800CF530 00000000 */   nop
    /* 89D34 800CF534 8FB80074 */  lw         $t8, 0x74($sp)
    /* 89D38 800CF538 000C7880 */  sll        $t7, $t4, 2
    /* 89D3C 800CF53C 01EC7821 */  addu       $t7, $t7, $t4
    /* 89D40 800CF540 930D0000 */  lbu        $t5, 0x0($t8)
    /* 89D44 800CF544 000F7840 */  sll        $t7, $t7, 1
    /* 89D48 800CF548 01AF7021 */  addu       $t6, $t5, $t7
    /* 89D4C 800CF54C 25D9FFD0 */  addiu      $t9, $t6, -0x30
    /* 89D50 800CF550 AFB900A0 */  sw         $t9, 0xA0($sp)
  .L800CF554:
    /* 89D54 800CF554 8FA80074 */  lw         $t0, 0x74($sp)
    /* 89D58 800CF558 25090001 */  addiu      $t1, $t0, 0x1
    /* 89D5C 800CF55C AFA90074 */  sw         $t1, 0x74($sp)
    /* 89D60 800CF560 912A0000 */  lbu        $t2, 0x0($t1)
    /* 89D64 800CF564 29410030 */  slti       $at, $t2, 0x30
    /* 89D68 800CF568 14200003 */  bnez       $at, .L800CF578
    /* 89D6C 800CF56C 2941003A */   slti      $at, $t2, 0x3A
    /* 89D70 800CF570 1420FFEC */  bnez       $at, .L800CF524
    /* 89D74 800CF574 00000000 */   nop
  .L800CF578:
    /* 89D78 800CF578 8FAB0074 */  lw         $t3, 0x74($sp)
    /* 89D7C 800CF57C 2401002E */  addiu      $at, $zero, 0x2E
    /* 89D80 800CF580 91780000 */  lbu        $t8, 0x0($t3)
    /* 89D84 800CF584 13010004 */  beq        $t8, $at, .L800CF598
    /* 89D88 800CF588 00000000 */   nop
    /* 89D8C 800CF58C 240CFFFF */  addiu      $t4, $zero, -0x1
    /* 89D90 800CF590 10000030 */  b          .L800CF654
    /* 89D94 800CF594 AFAC009C */   sw        $t4, 0x9C($sp)
  .L800CF598:
    /* 89D98 800CF598 8FAD0074 */  lw         $t5, 0x74($sp)
    /* 89D9C 800CF59C 2401002A */  addiu      $at, $zero, 0x2A
    /* 89DA0 800CF5A0 25AF0001 */  addiu      $t7, $t5, 0x1
    /* 89DA4 800CF5A4 AFAF0074 */  sw         $t7, 0x74($sp)
    /* 89DA8 800CF5A8 91EE0000 */  lbu        $t6, 0x0($t7)
    /* 89DAC 800CF5AC 15C1000C */  bne        $t6, $at, .L800CF5E0
    /* 89DB0 800CF5B0 00000000 */   nop
    /* 89DB4 800CF5B4 8FB900BC */  lw         $t9, 0xBC($sp)
    /* 89DB8 800CF5B8 2401FFFC */  addiu      $at, $zero, -0x4
    /* 89DBC 800CF5BC 25F80001 */  addiu      $t8, $t7, 0x1
    /* 89DC0 800CF5C0 27280003 */  addiu      $t0, $t9, 0x3
    /* 89DC4 800CF5C4 01014824 */  and        $t1, $t0, $at
    /* 89DC8 800CF5C8 252A0004 */  addiu      $t2, $t1, 0x4
    /* 89DCC 800CF5CC AFAA00BC */  sw         $t2, 0xBC($sp)
    /* 89DD0 800CF5D0 8D2B0000 */  lw         $t3, 0x0($t1)
    /* 89DD4 800CF5D4 AFB80074 */  sw         $t8, 0x74($sp)
    /* 89DD8 800CF5D8 1000001E */  b          .L800CF654
    /* 89DDC 800CF5DC AFAB009C */   sw        $t3, 0x9C($sp)
  .L800CF5E0:
    /* 89DE0 800CF5E0 8FAC0074 */  lw         $t4, 0x74($sp)
    /* 89DE4 800CF5E4 AFA0009C */  sw         $zero, 0x9C($sp)
    /* 89DE8 800CF5E8 918D0000 */  lbu        $t5, 0x0($t4)
    /* 89DEC 800CF5EC 29A10030 */  slti       $at, $t5, 0x30
    /* 89DF0 800CF5F0 14200018 */  bnez       $at, .L800CF654
    /* 89DF4 800CF5F4 29A1003A */   slti      $at, $t5, 0x3A
    /* 89DF8 800CF5F8 10200016 */  beqz       $at, .L800CF654
    /* 89DFC 800CF5FC 00000000 */   nop
  .L800CF600:
    /* 89E00 800CF600 8FAE009C */  lw         $t6, 0x9C($sp)
    /* 89E04 800CF604 29C103E7 */  slti       $at, $t6, 0x3E7
    /* 89E08 800CF608 10200009 */  beqz       $at, .L800CF630
    /* 89E0C 800CF60C 00000000 */   nop
    /* 89E10 800CF610 8FB90074 */  lw         $t9, 0x74($sp)
    /* 89E14 800CF614 000E5080 */  sll        $t2, $t6, 2
    /* 89E18 800CF618 014E5021 */  addu       $t2, $t2, $t6
    /* 89E1C 800CF61C 93280000 */  lbu        $t0, 0x0($t9)
    /* 89E20 800CF620 000A5040 */  sll        $t2, $t2, 1
    /* 89E24 800CF624 010A4821 */  addu       $t1, $t0, $t2
    /* 89E28 800CF628 252BFFD0 */  addiu      $t3, $t1, -0x30
    /* 89E2C 800CF62C AFAB009C */  sw         $t3, 0x9C($sp)
  .L800CF630:
    /* 89E30 800CF630 8FAF0074 */  lw         $t7, 0x74($sp)
    /* 89E34 800CF634 25F80001 */  addiu      $t8, $t7, 0x1
    /* 89E38 800CF638 AFB80074 */  sw         $t8, 0x74($sp)
    /* 89E3C 800CF63C 930C0000 */  lbu        $t4, 0x0($t8)
    /* 89E40 800CF640 29810030 */  slti       $at, $t4, 0x30
    /* 89E44 800CF644 14200003 */  bnez       $at, .L800CF654
    /* 89E48 800CF648 2981003A */   slti      $at, $t4, 0x3A
    /* 89E4C 800CF64C 1420FFEC */  bnez       $at, .L800CF600
    /* 89E50 800CF650 00000000 */   nop
  .L800CF654:
    /* 89E54 800CF654 8FAD0074 */  lw         $t5, 0x74($sp)
    /* 89E58 800CF658 3C04800F */  lui        $a0, %hi(D_800EC650)
    /* 89E5C 800CF65C 2484C650 */  addiu      $a0, $a0, %lo(D_800EC650)
    /* 89E60 800CF660 0C034145 */  jal        func_800D0514
    /* 89E64 800CF664 91A50000 */   lbu       $a1, 0x0($t5)
    /* 89E68 800CF668 10400007 */  beqz       $v0, .L800CF688
    /* 89E6C 800CF66C 00000000 */   nop
    /* 89E70 800CF670 8FB90074 */  lw         $t9, 0x74($sp)
    /* 89E74 800CF674 932E0000 */  lbu        $t6, 0x0($t9)
    /* 89E78 800CF678 27280001 */  addiu      $t0, $t9, 0x1
    /* 89E7C 800CF67C AFA80074 */  sw         $t0, 0x74($sp)
    /* 89E80 800CF680 10000002 */  b          .L800CF68C
    /* 89E84 800CF684 A3AE00AC */   sb        $t6, 0xAC($sp)
  .L800CF688:
    /* 89E88 800CF688 A3A000AC */  sb         $zero, 0xAC($sp)
  .L800CF68C:
    /* 89E8C 800CF68C 93AA00AC */  lbu        $t2, 0xAC($sp)
    /* 89E90 800CF690 2401006C */  addiu      $at, $zero, 0x6C
    /* 89E94 800CF694 1541000A */  bne        $t2, $at, .L800CF6C0
    /* 89E98 800CF698 00000000 */   nop
    /* 89E9C 800CF69C 8FA90074 */  lw         $t1, 0x74($sp)
    /* 89EA0 800CF6A0 2401006C */  addiu      $at, $zero, 0x6C
    /* 89EA4 800CF6A4 912B0000 */  lbu        $t3, 0x0($t1)
    /* 89EA8 800CF6A8 15610005 */  bne        $t3, $at, .L800CF6C0
    /* 89EAC 800CF6AC 00000000 */   nop
    /* 89EB0 800CF6B0 240F004C */  addiu      $t7, $zero, 0x4C
    /* 89EB4 800CF6B4 25380001 */  addiu      $t8, $t1, 0x1
    /* 89EB8 800CF6B8 A3AF00AC */  sb         $t7, 0xAC($sp)
    /* 89EBC 800CF6BC AFB80074 */  sw         $t8, 0x74($sp)
  .L800CF6C0:
    /* 89EC0 800CF6C0 8FAC0074 */  lw         $t4, 0x74($sp)
    /* 89EC4 800CF6C4 27A40078 */  addiu      $a0, $sp, 0x78
    /* 89EC8 800CF6C8 27A500BC */  addiu      $a1, $sp, 0xBC
    /* 89ECC 800CF6CC 27A7004C */  addiu      $a3, $sp, 0x4C
    /* 89ED0 800CF6D0 0C033ED7 */  jal        func_800CFB5C
    /* 89ED4 800CF6D4 91860000 */   lbu       $a2, 0x0($t4)
    /* 89ED8 800CF6D8 8FAD0084 */  lw         $t5, 0x84($sp)
    /* 89EDC 800CF6DC 8FAE0088 */  lw         $t6, 0x88($sp)
    /* 89EE0 800CF6E0 8FA8008C */  lw         $t0, 0x8C($sp)
    /* 89EE4 800CF6E4 8FAB0090 */  lw         $t3, 0x90($sp)
    /* 89EE8 800CF6E8 01AEC821 */  addu       $t9, $t5, $t6
    /* 89EEC 800CF6EC 8FA90094 */  lw         $t1, 0x94($sp)
    /* 89EF0 800CF6F0 03285021 */  addu       $t2, $t9, $t0
    /* 89EF4 800CF6F4 8FAC0098 */  lw         $t4, 0x98($sp)
    /* 89EF8 800CF6F8 8FAE00A0 */  lw         $t6, 0xA0($sp)
    /* 89EFC 800CF6FC 8FA800A8 */  lw         $t0, 0xA8($sp)
    /* 89F00 800CF700 014B7821 */  addu       $t7, $t2, $t3
    /* 89F04 800CF704 01E9C021 */  addu       $t8, $t7, $t1
    /* 89F08 800CF708 030C6821 */  addu       $t5, $t8, $t4
    /* 89F0C 800CF70C 01CDC823 */  subu       $t9, $t6, $t5
    /* 89F10 800CF710 310A0004 */  andi       $t2, $t0, 0x4
    /* 89F14 800CF714 15400028 */  bnez       $t2, .L800CF7B8
    /* 89F18 800CF718 AFB900A0 */   sw        $t9, 0xA0($sp)
    /* 89F1C 800CF71C 0019582A */  slt        $t3, $zero, $t9
    /* 89F20 800CF720 11600025 */  beqz       $t3, .L800CF7B8
    /* 89F24 800CF724 00000000 */   nop
    /* 89F28 800CF728 11600023 */  beqz       $t3, .L800CF7B8
    /* 89F2C 800CF72C AFB90044 */   sw        $t9, 0x44($sp)
  .L800CF730:
    /* 89F30 800CF730 8FAF0044 */  lw         $t7, 0x44($sp)
    /* 89F34 800CF734 2DE10021 */  sltiu      $at, $t7, 0x21
    /* 89F38 800CF738 14200004 */  bnez       $at, .L800CF74C
    /* 89F3C 800CF73C 00000000 */   nop
    /* 89F40 800CF740 24090020 */  addiu      $t1, $zero, 0x20
    /* 89F44 800CF744 10000003 */  b          .L800CF754
    /* 89F48 800CF748 AFA90048 */   sw        $t1, 0x48($sp)
  .L800CF74C:
    /* 89F4C 800CF74C 8FB80044 */  lw         $t8, 0x44($sp)
    /* 89F50 800CF750 AFB80048 */  sw         $t8, 0x48($sp)
  .L800CF754:
    /* 89F54 800CF754 8FAC0048 */  lw         $t4, 0x48($sp)
    /* 89F58 800CF758 19800012 */  blez       $t4, .L800CF7A4
    /* 89F5C 800CF75C 00000000 */   nop
    /* 89F60 800CF760 8FB900B0 */  lw         $t9, 0xB0($sp)
    /* 89F64 800CF764 3C05800F */  lui        $a1, %hi(D_800E90E0)
    /* 89F68 800CF768 24A590E0 */  addiu      $a1, $a1, %lo(D_800E90E0)
    /* 89F6C 800CF76C 8FA400B4 */  lw         $a0, 0xB4($sp)
    /* 89F70 800CF770 0320F809 */  jalr       $t9
    /* 89F74 800CF774 01803025 */   or        $a2, $t4, $zero
    /* 89F78 800CF778 AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 89F7C 800CF77C 8FAE00B4 */  lw         $t6, 0xB4($sp)
    /* 89F80 800CF780 11C00006 */  beqz       $t6, .L800CF79C
    /* 89F84 800CF784 00000000 */   nop
    /* 89F88 800CF788 8FAD00A4 */  lw         $t5, 0xA4($sp)
    /* 89F8C 800CF78C 8FA80048 */  lw         $t0, 0x48($sp)
    /* 89F90 800CF790 01A85021 */  addu       $t2, $t5, $t0
    /* 89F94 800CF794 10000003 */  b          .L800CF7A4
    /* 89F98 800CF798 AFAA00A4 */   sw        $t2, 0xA4($sp)
  .L800CF79C:
    /* 89F9C 800CF79C 100000EA */  b          .L800CFB48
    /* 89FA0 800CF7A0 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CF7A4:
    /* 89FA4 800CF7A4 8FAB0044 */  lw         $t3, 0x44($sp)
    /* 89FA8 800CF7A8 8FAF0048 */  lw         $t7, 0x48($sp)
    /* 89FAC 800CF7AC 016F4823 */  subu       $t1, $t3, $t7
    /* 89FB0 800CF7B0 1D20FFDF */  bgtz       $t1, .L800CF730
    /* 89FB4 800CF7B4 AFA90044 */   sw        $t1, 0x44($sp)
  .L800CF7B8:
    /* 89FB8 800CF7B8 8FB80084 */  lw         $t8, 0x84($sp)
    /* 89FBC 800CF7BC 1B000011 */  blez       $t8, .L800CF804
    /* 89FC0 800CF7C0 00000000 */   nop
    /* 89FC4 800CF7C4 8FB900B0 */  lw         $t9, 0xB0($sp)
    /* 89FC8 800CF7C8 8FA400B4 */  lw         $a0, 0xB4($sp)
    /* 89FCC 800CF7CC 27A5004C */  addiu      $a1, $sp, 0x4C
    /* 89FD0 800CF7D0 0320F809 */  jalr       $t9
    /* 89FD4 800CF7D4 03003025 */   or        $a2, $t8, $zero
    /* 89FD8 800CF7D8 AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 89FDC 800CF7DC 8FAC00B4 */  lw         $t4, 0xB4($sp)
    /* 89FE0 800CF7E0 11800006 */  beqz       $t4, .L800CF7FC
    /* 89FE4 800CF7E4 00000000 */   nop
    /* 89FE8 800CF7E8 8FAE00A4 */  lw         $t6, 0xA4($sp)
    /* 89FEC 800CF7EC 8FAD0084 */  lw         $t5, 0x84($sp)
    /* 89FF0 800CF7F0 01CD4021 */  addu       $t0, $t6, $t5
    /* 89FF4 800CF7F4 10000003 */  b          .L800CF804
    /* 89FF8 800CF7F8 AFA800A4 */   sw        $t0, 0xA4($sp)
  .L800CF7FC:
    /* 89FFC 800CF7FC 100000D2 */  b          .L800CFB48
    /* 8A000 800CF800 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CF804:
    /* 8A004 800CF804 8FAA0088 */  lw         $t2, 0x88($sp)
    /* 8A008 800CF808 000A582A */  slt        $t3, $zero, $t2
    /* 8A00C 800CF80C 11600025 */  beqz       $t3, .L800CF8A4
    /* 8A010 800CF810 00000000 */   nop
    /* 8A014 800CF814 11600023 */  beqz       $t3, .L800CF8A4
    /* 8A018 800CF818 AFAA003C */   sw        $t2, 0x3C($sp)
  .L800CF81C:
    /* 8A01C 800CF81C 8FAF003C */  lw         $t7, 0x3C($sp)
    /* 8A020 800CF820 2DE10021 */  sltiu      $at, $t7, 0x21
    /* 8A024 800CF824 14200004 */  bnez       $at, .L800CF838
    /* 8A028 800CF828 00000000 */   nop
    /* 8A02C 800CF82C 24090020 */  addiu      $t1, $zero, 0x20
    /* 8A030 800CF830 10000003 */  b          .L800CF840
    /* 8A034 800CF834 AFA90040 */   sw        $t1, 0x40($sp)
  .L800CF838:
    /* 8A038 800CF838 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 8A03C 800CF83C AFB80040 */  sw         $t8, 0x40($sp)
  .L800CF840:
    /* 8A040 800CF840 8FB90040 */  lw         $t9, 0x40($sp)
    /* 8A044 800CF844 1B200012 */  blez       $t9, .L800CF890
    /* 8A048 800CF848 00000000 */   nop
    /* 8A04C 800CF84C 03203025 */  or         $a2, $t9, $zero
    /* 8A050 800CF850 8FB900B0 */  lw         $t9, 0xB0($sp)
    /* 8A054 800CF854 3C05800F */  lui        $a1, %hi(D_800E9104)
    /* 8A058 800CF858 24A59104 */  addiu      $a1, $a1, %lo(D_800E9104)
    /* 8A05C 800CF85C 0320F809 */  jalr       $t9
    /* 8A060 800CF860 8FA400B4 */   lw        $a0, 0xB4($sp)
    /* 8A064 800CF864 AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 8A068 800CF868 8FAC00B4 */  lw         $t4, 0xB4($sp)
    /* 8A06C 800CF86C 11800006 */  beqz       $t4, .L800CF888
    /* 8A070 800CF870 00000000 */   nop
    /* 8A074 800CF874 8FAE00A4 */  lw         $t6, 0xA4($sp)
    /* 8A078 800CF878 8FAD0040 */  lw         $t5, 0x40($sp)
    /* 8A07C 800CF87C 01CD4021 */  addu       $t0, $t6, $t5
    /* 8A080 800CF880 10000003 */  b          .L800CF890
    /* 8A084 800CF884 AFA800A4 */   sw        $t0, 0xA4($sp)
  .L800CF888:
    /* 8A088 800CF888 100000AF */  b          .L800CFB48
    /* 8A08C 800CF88C 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CF890:
    /* 8A090 800CF890 8FAA003C */  lw         $t2, 0x3C($sp)
    /* 8A094 800CF894 8FAB0040 */  lw         $t3, 0x40($sp)
    /* 8A098 800CF898 014B7823 */  subu       $t7, $t2, $t3
    /* 8A09C 800CF89C 1DE0FFDF */  bgtz       $t7, .L800CF81C
    /* 8A0A0 800CF8A0 AFAF003C */   sw        $t7, 0x3C($sp)
  .L800CF8A4:
    /* 8A0A4 800CF8A4 8FA9008C */  lw         $t1, 0x8C($sp)
    /* 8A0A8 800CF8A8 19200011 */  blez       $t1, .L800CF8F0
    /* 8A0AC 800CF8AC 00000000 */   nop
    /* 8A0B0 800CF8B0 8FB900B0 */  lw         $t9, 0xB0($sp)
    /* 8A0B4 800CF8B4 8FA400B4 */  lw         $a0, 0xB4($sp)
    /* 8A0B8 800CF8B8 8FA50080 */  lw         $a1, 0x80($sp)
    /* 8A0BC 800CF8BC 0320F809 */  jalr       $t9
    /* 8A0C0 800CF8C0 01203025 */   or        $a2, $t1, $zero
    /* 8A0C4 800CF8C4 AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 8A0C8 800CF8C8 8FB800B4 */  lw         $t8, 0xB4($sp)
    /* 8A0CC 800CF8CC 13000006 */  beqz       $t8, .L800CF8E8
    /* 8A0D0 800CF8D0 00000000 */   nop
    /* 8A0D4 800CF8D4 8FAC00A4 */  lw         $t4, 0xA4($sp)
    /* 8A0D8 800CF8D8 8FAE008C */  lw         $t6, 0x8C($sp)
    /* 8A0DC 800CF8DC 018E6821 */  addu       $t5, $t4, $t6
    /* 8A0E0 800CF8E0 10000003 */  b          .L800CF8F0
    /* 8A0E4 800CF8E4 AFAD00A4 */   sw        $t5, 0xA4($sp)
  .L800CF8E8:
    /* 8A0E8 800CF8E8 10000097 */  b          .L800CFB48
    /* 8A0EC 800CF8EC 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CF8F0:
    /* 8A0F0 800CF8F0 8FA80090 */  lw         $t0, 0x90($sp)
    /* 8A0F4 800CF8F4 0008502A */  slt        $t2, $zero, $t0
    /* 8A0F8 800CF8F8 11400025 */  beqz       $t2, .L800CF990
    /* 8A0FC 800CF8FC 00000000 */   nop
    /* 8A100 800CF900 11400023 */  beqz       $t2, .L800CF990
    /* 8A104 800CF904 AFA80034 */   sw        $t0, 0x34($sp)
  .L800CF908:
    /* 8A108 800CF908 8FAB0034 */  lw         $t3, 0x34($sp)
    /* 8A10C 800CF90C 2D610021 */  sltiu      $at, $t3, 0x21
    /* 8A110 800CF910 14200004 */  bnez       $at, .L800CF924
    /* 8A114 800CF914 00000000 */   nop
    /* 8A118 800CF918 240F0020 */  addiu      $t7, $zero, 0x20
    /* 8A11C 800CF91C 10000003 */  b          .L800CF92C
    /* 8A120 800CF920 AFAF0038 */   sw        $t7, 0x38($sp)
  .L800CF924:
    /* 8A124 800CF924 8FA90034 */  lw         $t1, 0x34($sp)
    /* 8A128 800CF928 AFA90038 */  sw         $t1, 0x38($sp)
  .L800CF92C:
    /* 8A12C 800CF92C 8FB90038 */  lw         $t9, 0x38($sp)
    /* 8A130 800CF930 1B200012 */  blez       $t9, .L800CF97C
    /* 8A134 800CF934 00000000 */   nop
    /* 8A138 800CF938 03203025 */  or         $a2, $t9, $zero
    /* 8A13C 800CF93C 8FB900B0 */  lw         $t9, 0xB0($sp)
    /* 8A140 800CF940 3C05800F */  lui        $a1, %hi(D_800E9104)
    /* 8A144 800CF944 24A59104 */  addiu      $a1, $a1, %lo(D_800E9104)
    /* 8A148 800CF948 0320F809 */  jalr       $t9
    /* 8A14C 800CF94C 8FA400B4 */   lw        $a0, 0xB4($sp)
    /* 8A150 800CF950 AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 8A154 800CF954 8FB800B4 */  lw         $t8, 0xB4($sp)
    /* 8A158 800CF958 13000006 */  beqz       $t8, .L800CF974
    /* 8A15C 800CF95C 00000000 */   nop
    /* 8A160 800CF960 8FAC00A4 */  lw         $t4, 0xA4($sp)
    /* 8A164 800CF964 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 8A168 800CF968 018E6821 */  addu       $t5, $t4, $t6
    /* 8A16C 800CF96C 10000003 */  b          .L800CF97C
    /* 8A170 800CF970 AFAD00A4 */   sw        $t5, 0xA4($sp)
  .L800CF974:
    /* 8A174 800CF974 10000074 */  b          .L800CFB48
    /* 8A178 800CF978 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CF97C:
    /* 8A17C 800CF97C 8FA80034 */  lw         $t0, 0x34($sp)
    /* 8A180 800CF980 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 8A184 800CF984 010A5823 */  subu       $t3, $t0, $t2
    /* 8A188 800CF988 1D60FFDF */  bgtz       $t3, .L800CF908
    /* 8A18C 800CF98C AFAB0034 */   sw        $t3, 0x34($sp)
  .L800CF990:
    /* 8A190 800CF990 8FAF0094 */  lw         $t7, 0x94($sp)
    /* 8A194 800CF994 19E00014 */  blez       $t7, .L800CF9E8
    /* 8A198 800CF998 00000000 */   nop
    /* 8A19C 800CF99C 8FA90080 */  lw         $t1, 0x80($sp)
    /* 8A1A0 800CF9A0 8FB9008C */  lw         $t9, 0x8C($sp)
    /* 8A1A4 800CF9A4 8FA400B4 */  lw         $a0, 0xB4($sp)
    /* 8A1A8 800CF9A8 01E03025 */  or         $a2, $t7, $zero
    /* 8A1AC 800CF9AC 01392821 */  addu       $a1, $t1, $t9
    /* 8A1B0 800CF9B0 8FB900B0 */  lw         $t9, 0xB0($sp)
    /* 8A1B4 800CF9B4 0320F809 */  jalr       $t9
    /* 8A1B8 800CF9B8 00000000 */   nop
    /* 8A1BC 800CF9BC AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 8A1C0 800CF9C0 8FB800B4 */  lw         $t8, 0xB4($sp)
    /* 8A1C4 800CF9C4 13000006 */  beqz       $t8, .L800CF9E0
    /* 8A1C8 800CF9C8 00000000 */   nop
    /* 8A1CC 800CF9CC 8FAC00A4 */  lw         $t4, 0xA4($sp)
    /* 8A1D0 800CF9D0 8FAE0094 */  lw         $t6, 0x94($sp)
    /* 8A1D4 800CF9D4 018E6821 */  addu       $t5, $t4, $t6
    /* 8A1D8 800CF9D8 10000003 */  b          .L800CF9E8
    /* 8A1DC 800CF9DC AFAD00A4 */   sw        $t5, 0xA4($sp)
  .L800CF9E0:
    /* 8A1E0 800CF9E0 10000059 */  b          .L800CFB48
    /* 8A1E4 800CF9E4 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CF9E8:
    /* 8A1E8 800CF9E8 8FA80098 */  lw         $t0, 0x98($sp)
    /* 8A1EC 800CF9EC 0008502A */  slt        $t2, $zero, $t0
    /* 8A1F0 800CF9F0 11400025 */  beqz       $t2, .L800CFA88
    /* 8A1F4 800CF9F4 00000000 */   nop
    /* 8A1F8 800CF9F8 11400023 */  beqz       $t2, .L800CFA88
    /* 8A1FC 800CF9FC AFA8002C */   sw        $t0, 0x2C($sp)
  .L800CFA00:
    /* 8A200 800CFA00 8FAB002C */  lw         $t3, 0x2C($sp)
    /* 8A204 800CFA04 2D610021 */  sltiu      $at, $t3, 0x21
    /* 8A208 800CFA08 14200004 */  bnez       $at, .L800CFA1C
    /* 8A20C 800CFA0C 00000000 */   nop
    /* 8A210 800CFA10 24090020 */  addiu      $t1, $zero, 0x20
    /* 8A214 800CFA14 10000003 */  b          .L800CFA24
    /* 8A218 800CFA18 AFA90030 */   sw        $t1, 0x30($sp)
  .L800CFA1C:
    /* 8A21C 800CFA1C 8FAF002C */  lw         $t7, 0x2C($sp)
    /* 8A220 800CFA20 AFAF0030 */  sw         $t7, 0x30($sp)
  .L800CFA24:
    /* 8A224 800CFA24 8FB90030 */  lw         $t9, 0x30($sp)
    /* 8A228 800CFA28 1B200012 */  blez       $t9, .L800CFA74
    /* 8A22C 800CFA2C 00000000 */   nop
    /* 8A230 800CFA30 03203025 */  or         $a2, $t9, $zero
    /* 8A234 800CFA34 8FB900B0 */  lw         $t9, 0xB0($sp)
    /* 8A238 800CFA38 3C05800F */  lui        $a1, %hi(D_800E9104)
    /* 8A23C 800CFA3C 24A59104 */  addiu      $a1, $a1, %lo(D_800E9104)
    /* 8A240 800CFA40 0320F809 */  jalr       $t9
    /* 8A244 800CFA44 8FA400B4 */   lw        $a0, 0xB4($sp)
    /* 8A248 800CFA48 AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 8A24C 800CFA4C 8FB800B4 */  lw         $t8, 0xB4($sp)
    /* 8A250 800CFA50 13000006 */  beqz       $t8, .L800CFA6C
    /* 8A254 800CFA54 00000000 */   nop
    /* 8A258 800CFA58 8FAC00A4 */  lw         $t4, 0xA4($sp)
    /* 8A25C 800CFA5C 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 8A260 800CFA60 018E6821 */  addu       $t5, $t4, $t6
    /* 8A264 800CFA64 10000003 */  b          .L800CFA74
    /* 8A268 800CFA68 AFAD00A4 */   sw        $t5, 0xA4($sp)
  .L800CFA6C:
    /* 8A26C 800CFA6C 10000036 */  b          .L800CFB48
    /* 8A270 800CFA70 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CFA74:
    /* 8A274 800CFA74 8FA8002C */  lw         $t0, 0x2C($sp)
    /* 8A278 800CFA78 8FAA0030 */  lw         $t2, 0x30($sp)
    /* 8A27C 800CFA7C 010A5823 */  subu       $t3, $t0, $t2
    /* 8A280 800CFA80 1D60FFDF */  bgtz       $t3, .L800CFA00
    /* 8A284 800CFA84 AFAB002C */   sw        $t3, 0x2C($sp)
  .L800CFA88:
    /* 8A288 800CFA88 8FA900A8 */  lw         $t1, 0xA8($sp)
    /* 8A28C 800CFA8C 312F0004 */  andi       $t7, $t1, 0x4
    /* 8A290 800CFA90 11E00029 */  beqz       $t7, .L800CFB38
    /* 8A294 800CFA94 00000000 */   nop
    /* 8A298 800CFA98 8FB900A0 */  lw         $t9, 0xA0($sp)
    /* 8A29C 800CFA9C 0019C02A */  slt        $t8, $zero, $t9
    /* 8A2A0 800CFAA0 13000025 */  beqz       $t8, .L800CFB38
    /* 8A2A4 800CFAA4 00000000 */   nop
    /* 8A2A8 800CFAA8 13000023 */  beqz       $t8, .L800CFB38
    /* 8A2AC 800CFAAC AFB90024 */   sw        $t9, 0x24($sp)
  .L800CFAB0:
    /* 8A2B0 800CFAB0 8FAC0024 */  lw         $t4, 0x24($sp)
    /* 8A2B4 800CFAB4 2D810021 */  sltiu      $at, $t4, 0x21
    /* 8A2B8 800CFAB8 14200004 */  bnez       $at, .L800CFACC
    /* 8A2BC 800CFABC 00000000 */   nop
    /* 8A2C0 800CFAC0 240E0020 */  addiu      $t6, $zero, 0x20
    /* 8A2C4 800CFAC4 10000003 */  b          .L800CFAD4
    /* 8A2C8 800CFAC8 AFAE0028 */   sw        $t6, 0x28($sp)
  .L800CFACC:
    /* 8A2CC 800CFACC 8FAD0024 */  lw         $t5, 0x24($sp)
    /* 8A2D0 800CFAD0 AFAD0028 */  sw         $t5, 0x28($sp)
  .L800CFAD4:
    /* 8A2D4 800CFAD4 8FA80028 */  lw         $t0, 0x28($sp)
    /* 8A2D8 800CFAD8 19000012 */  blez       $t0, .L800CFB24
    /* 8A2DC 800CFADC 00000000 */   nop
    /* 8A2E0 800CFAE0 8FB900B0 */  lw         $t9, 0xB0($sp)
    /* 8A2E4 800CFAE4 3C05800F */  lui        $a1, %hi(D_800E90E0)
    /* 8A2E8 800CFAE8 24A590E0 */  addiu      $a1, $a1, %lo(D_800E90E0)
    /* 8A2EC 800CFAEC 8FA400B4 */  lw         $a0, 0xB4($sp)
    /* 8A2F0 800CFAF0 0320F809 */  jalr       $t9
    /* 8A2F4 800CFAF4 01003025 */   or        $a2, $t0, $zero
    /* 8A2F8 800CFAF8 AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 8A2FC 800CFAFC 8FAA00B4 */  lw         $t2, 0xB4($sp)
    /* 8A300 800CFB00 11400006 */  beqz       $t2, .L800CFB1C
    /* 8A304 800CFB04 00000000 */   nop
    /* 8A308 800CFB08 8FAB00A4 */  lw         $t3, 0xA4($sp)
    /* 8A30C 800CFB0C 8FA90028 */  lw         $t1, 0x28($sp)
    /* 8A310 800CFB10 01697821 */  addu       $t7, $t3, $t1
    /* 8A314 800CFB14 10000003 */  b          .L800CFB24
    /* 8A318 800CFB18 AFAF00A4 */   sw        $t7, 0xA4($sp)
  .L800CFB1C:
    /* 8A31C 800CFB1C 1000000A */  b          .L800CFB48
    /* 8A320 800CFB20 8FA200A4 */   lw        $v0, 0xA4($sp)
  .L800CFB24:
    /* 8A324 800CFB24 8FB80024 */  lw         $t8, 0x24($sp)
    /* 8A328 800CFB28 8FAC0028 */  lw         $t4, 0x28($sp)
    /* 8A32C 800CFB2C 030C7023 */  subu       $t6, $t8, $t4
    /* 8A330 800CFB30 1DC0FFDF */  bgtz       $t6, .L800CFAB0
    /* 8A334 800CFB34 AFAE0024 */   sw        $t6, 0x24($sp)
  .L800CFB38:
    /* 8A338 800CFB38 8FAD0074 */  lw         $t5, 0x74($sp)
    /* 8A33C 800CFB3C 25A80001 */  addiu      $t0, $t5, 0x1
    /* 8A340 800CFB40 1000FE03 */  b          .L800CF350
    /* 8A344 800CFB44 AFA800B8 */   sw        $t0, 0xB8($sp)
  .L800CFB48:
    /* 8A348 800CFB48 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 8A34C 800CFB4C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 8A350 800CFB50 27BD00B0 */  addiu      $sp, $sp, 0xB0
    /* 8A354 800CFB54 03E00008 */  jr         $ra
    /* 8A358 800CFB58 00000000 */   nop

glabel func_800CFB5C
    /* 8A35C 800CFB5C 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 8A360 800CFB60 AFA40038 */  sw         $a0, 0x38($sp)
    /* 8A364 800CFB64 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 8A368 800CFB68 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 8A36C 800CFB6C AFA5003C */  sw         $a1, 0x3C($sp)
    /* 8A370 800CFB70 AFA60040 */  sw         $a2, 0x40($sp)
    /* 8A374 800CFB74 AFA70044 */  sw         $a3, 0x44($sp)
    /* 8A378 800CFB78 AFB30020 */  sw         $s3, 0x20($sp)
    /* 8A37C 800CFB7C AFB2001C */  sw         $s2, 0x1C($sp)
    /* 8A380 800CFB80 AFB10018 */  sw         $s1, 0x18($sp)
    /* 8A384 800CFB84 AFB00014 */  sw         $s0, 0x14($sp)
    /* 8A388 800CFB88 ADC00020 */  sw         $zero, 0x20($t6)
    /* 8A38C 800CFB8C 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 8A390 800CFB90 8DF30020 */  lw         $s3, 0x20($t7)
    /* 8A394 800CFB94 ADF3001C */  sw         $s3, 0x1C($t7)
    /* 8A398 800CFB98 8FB80038 */  lw         $t8, 0x38($sp)
    /* 8A39C 800CFB9C 02609025 */  or         $s2, $s3, $zero
    /* 8A3A0 800CFBA0 02408825 */  or         $s1, $s2, $zero
    /* 8A3A4 800CFBA4 AF120018 */  sw         $s2, 0x18($t8)
    /* 8A3A8 800CFBA8 8FB90038 */  lw         $t9, 0x38($sp)
    /* 8A3AC 800CFBAC 02208025 */  or         $s0, $s1, $zero
    /* 8A3B0 800CFBB0 AF310014 */  sw         $s1, 0x14($t9)
    /* 8A3B4 800CFBB4 8FA80038 */  lw         $t0, 0x38($sp)
    /* 8A3B8 800CFBB8 AD100010 */  sw         $s0, 0x10($t0)
    /* 8A3BC 800CFBBC 8FA90038 */  lw         $t1, 0x38($sp)
    /* 8A3C0 800CFBC0 AD30000C */  sw         $s0, 0xC($t1)
    /* 8A3C4 800CFBC4 93B00043 */  lbu        $s0, 0x43($sp)
    /* 8A3C8 800CFBC8 2A010026 */  slti       $at, $s0, 0x26
    /* 8A3CC 800CFBCC 1420000B */  bnez       $at, .L800CFBFC
    /* 8A3D0 800CFBD0 00000000 */   nop
    /* 8A3D4 800CFBD4 260AFFBB */  addiu      $t2, $s0, -0x45
    /* 8A3D8 800CFBD8 2D410034 */  sltiu      $at, $t2, 0x34
    /* 8A3DC 800CFBDC 10200224 */  beqz       $at, .L800D0470
    /* 8A3E0 800CFBE0 00000000 */   nop
    /* 8A3E4 800CFBE4 000A5080 */  sll        $t2, $t2, 2
    /* 8A3E8 800CFBE8 3C01800F */  lui        $at, %hi(jtbl_800EC674_main_segment)
    /* 8A3EC 800CFBEC 002A0821 */  addu       $at, $at, $t2
    /* 8A3F0 800CFBF0 8C2AC674 */  lw         $t2, %lo(jtbl_800EC674_main_segment)($at)
    /* 8A3F4 800CFBF4 01400008 */  jr         $t2
    /* 8A3F8 800CFBF8 00000000 */   nop
  .L800CFBFC:
    /* 8A3FC 800CFBFC 24010025 */  addiu      $at, $zero, 0x25
    /* 8A400 800CFC00 12010210 */  beq        $s0, $at, .L800D0444
    /* 8A404 800CFC04 00000000 */   nop
    /* 8A408 800CFC08 10000219 */  b          .L800D0470
    /* 8A40C 800CFC0C 00000000 */   nop
    /* 8A410 800CFC10 8FAB003C */  lw         $t3, 0x3C($sp)
    /* 8A414 800CFC14 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8A418 800CFC18 8D6C0000 */  lw         $t4, 0x0($t3)
    /* 8A41C 800CFC1C 258D0003 */  addiu      $t5, $t4, 0x3
    /* 8A420 800CFC20 01A17024 */  and        $t6, $t5, $at
    /* 8A424 800CFC24 25CF0004 */  addiu      $t7, $t6, 0x4
    /* 8A428 800CFC28 AD6F0000 */  sw         $t7, 0x0($t3)
    /* 8A42C 800CFC2C 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 8A430 800CFC30 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 8A434 800CFC34 8FA90044 */  lw         $t1, 0x44($sp)
    /* 8A438 800CFC38 8F190000 */  lw         $t9, 0x0($t8)
    /* 8A43C 800CFC3C 8D4C000C */  lw         $t4, 0xC($t2)
    /* 8A440 800CFC40 8F28FFFC */  lw         $t0, -0x4($t9)
    /* 8A444 800CFC44 012C6821 */  addu       $t5, $t1, $t4
    /* 8A448 800CFC48 A1A80000 */  sb         $t0, 0x0($t5)
    /* 8A44C 800CFC4C 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 8A450 800CFC50 8DCF000C */  lw         $t7, 0xC($t6)
    /* 8A454 800CFC54 25EB0001 */  addiu      $t3, $t7, 0x1
    /* 8A458 800CFC58 1000020F */  b          .L800D0498
    /* 8A45C 800CFC5C ADCB000C */   sw        $t3, 0xC($t6)
    /* 8A460 800CFC60 8FB80038 */  lw         $t8, 0x38($sp)
    /* 8A464 800CFC64 2401006C */  addiu      $at, $zero, 0x6C
    /* 8A468 800CFC68 93190034 */  lbu        $t9, 0x34($t8)
    /* 8A46C 800CFC6C 17210011 */  bne        $t9, $at, .L800CFCB4
    /* 8A470 800CFC70 00000000 */   nop
    /* 8A474 800CFC74 8FAA003C */  lw         $t2, 0x3C($sp)
    /* 8A478 800CFC78 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8A47C 800CFC7C 8D490000 */  lw         $t1, 0x0($t2)
    /* 8A480 800CFC80 252C0003 */  addiu      $t4, $t1, 0x3
    /* 8A484 800CFC84 01814024 */  and        $t0, $t4, $at
    /* 8A488 800CFC88 250D0004 */  addiu      $t5, $t0, 0x4
    /* 8A48C 800CFC8C AD4D0000 */  sw         $t5, 0x0($t2)
    /* 8A490 800CFC90 8FAF003C */  lw         $t7, 0x3C($sp)
    /* 8A494 800CFC94 8FA90038 */  lw         $t1, 0x38($sp)
    /* 8A498 800CFC98 8DEB0000 */  lw         $t3, 0x0($t7)
    /* 8A49C 800CFC9C 8D6EFFFC */  lw         $t6, -0x4($t3)
    /* 8A4A0 800CFCA0 01C0C825 */  or         $t9, $t6, $zero
    /* 8A4A4 800CFCA4 000EC7C3 */  sra        $t8, $t6, 31
    /* 8A4A8 800CFCA8 AD380000 */  sw         $t8, 0x0($t1)
    /* 8A4AC 800CFCAC 10000024 */  b          .L800CFD40
    /* 8A4B0 800CFCB0 AD390004 */   sw        $t9, 0x4($t1)
  .L800CFCB4:
    /* 8A4B4 800CFCB4 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 8A4B8 800CFCB8 2401004C */  addiu      $at, $zero, 0x4C
    /* 8A4BC 800CFCBC 91880034 */  lbu        $t0, 0x34($t4)
    /* 8A4C0 800CFCC0 15010010 */  bne        $t0, $at, .L800CFD04
    /* 8A4C4 800CFCC4 00000000 */   nop
    /* 8A4C8 800CFCC8 8FAD003C */  lw         $t5, 0x3C($sp)
    /* 8A4CC 800CFCCC 2401FFF8 */  addiu      $at, $zero, -0x8
    /* 8A4D0 800CFCD0 8DAA0000 */  lw         $t2, 0x0($t5)
    /* 8A4D4 800CFCD4 254F0007 */  addiu      $t7, $t2, 0x7
    /* 8A4D8 800CFCD8 01E15824 */  and        $t3, $t7, $at
    /* 8A4DC 800CFCDC 256E0008 */  addiu      $t6, $t3, 0x8
    /* 8A4E0 800CFCE0 ADAE0000 */  sw         $t6, 0x0($t5)
    /* 8A4E4 800CFCE4 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 8A4E8 800CFCE8 8FA90038 */  lw         $t1, 0x38($sp)
    /* 8A4EC 800CFCEC 8F190000 */  lw         $t9, 0x0($t8)
    /* 8A4F0 800CFCF0 8F2CFFF8 */  lw         $t4, -0x8($t9)
    /* 8A4F4 800CFCF4 8F2DFFFC */  lw         $t5, -0x4($t9)
    /* 8A4F8 800CFCF8 AD2C0000 */  sw         $t4, 0x0($t1)
    /* 8A4FC 800CFCFC 10000010 */  b          .L800CFD40
    /* 8A500 800CFD00 AD2D0004 */   sw        $t5, 0x4($t1)
  .L800CFD04:
    /* 8A504 800CFD04 8FA8003C */  lw         $t0, 0x3C($sp)
    /* 8A508 800CFD08 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8A50C 800CFD0C 8D0A0000 */  lw         $t2, 0x0($t0)
    /* 8A510 800CFD10 254F0003 */  addiu      $t7, $t2, 0x3
    /* 8A514 800CFD14 01E15824 */  and        $t3, $t7, $at
    /* 8A518 800CFD18 256E0004 */  addiu      $t6, $t3, 0x4
    /* 8A51C 800CFD1C AD0E0000 */  sw         $t6, 0x0($t0)
    /* 8A520 800CFD20 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 8A524 800CFD24 8FAD0038 */  lw         $t5, 0x38($sp)
    /* 8A528 800CFD28 8F190000 */  lw         $t9, 0x0($t8)
    /* 8A52C 800CFD2C 8F2CFFFC */  lw         $t4, -0x4($t9)
    /* 8A530 800CFD30 01805825 */  or         $t3, $t4, $zero
    /* 8A534 800CFD34 000C57C3 */  sra        $t2, $t4, 31
    /* 8A538 800CFD38 ADAA0000 */  sw         $t2, 0x0($t5)
    /* 8A53C 800CFD3C ADAB0004 */  sw         $t3, 0x4($t5)
  .L800CFD40:
    /* 8A540 800CFD40 8FA90038 */  lw         $t1, 0x38($sp)
    /* 8A544 800CFD44 24010068 */  addiu      $at, $zero, 0x68
    /* 8A548 800CFD48 912F0034 */  lbu        $t7, 0x34($t1)
    /* 8A54C 800CFD4C 15E1000A */  bne        $t7, $at, .L800CFD78
    /* 8A550 800CFD50 00000000 */   nop
    /* 8A554 800CFD54 8D2F0004 */  lw         $t7, 0x4($t1)
    /* 8A558 800CFD58 8D2E0000 */  lw         $t6, 0x0($t1)
    /* 8A55C 800CFD5C 01E04025 */  or         $t0, $t7, $zero
    /* 8A560 800CFD60 0008C400 */  sll        $t8, $t0, 16
    /* 8A564 800CFD64 0018CC03 */  sra        $t9, $t8, 16
    /* 8A568 800CFD68 03206825 */  or         $t5, $t9, $zero
    /* 8A56C 800CFD6C 001967C3 */  sra        $t4, $t9, 31
    /* 8A570 800CFD70 AD2C0000 */  sw         $t4, 0x0($t1)
    /* 8A574 800CFD74 AD2D0004 */  sw         $t5, 0x4($t1)
  .L800CFD78:
    /* 8A578 800CFD78 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 8A57C 800CFD7C 8D4E0000 */  lw         $t6, 0x0($t2)
    /* 8A580 800CFD80 8D4F0004 */  lw         $t7, 0x4($t2)
    /* 8A584 800CFD84 1DC0000F */  bgtz       $t6, .L800CFDC4
    /* 8A588 800CFD88 00000000 */   nop
    /* 8A58C 800CFD8C 05C00003 */  bltz       $t6, .L800CFD9C
    /* 8A590 800CFD90 00000000 */   nop
    /* 8A594 800CFD94 1000000B */  b          .L800CFDC4
    /* 8A598 800CFD98 00000000 */   nop
  .L800CFD9C:
    /* 8A59C 800CFD9C 8FA80044 */  lw         $t0, 0x44($sp)
    /* 8A5A0 800CFDA0 8D58000C */  lw         $t8, 0xC($t2)
    /* 8A5A4 800CFDA4 240B002D */  addiu      $t3, $zero, 0x2D
    /* 8A5A8 800CFDA8 0118C821 */  addu       $t9, $t0, $t8
    /* 8A5AC 800CFDAC A32B0000 */  sb         $t3, 0x0($t9)
    /* 8A5B0 800CFDB0 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 8A5B4 800CFDB4 8D8D000C */  lw         $t5, 0xC($t4)
    /* 8A5B8 800CFDB8 25A90001 */  addiu      $t1, $t5, 0x1
    /* 8A5BC 800CFDBC 1000001E */  b          .L800CFE38
    /* 8A5C0 800CFDC0 AD89000C */   sw        $t1, 0xC($t4)
  .L800CFDC4:
    /* 8A5C4 800CFDC4 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 8A5C8 800CFDC8 8DCF0030 */  lw         $t7, 0x30($t6)
    /* 8A5CC 800CFDCC 31EA0002 */  andi       $t2, $t7, 0x2
    /* 8A5D0 800CFDD0 1140000B */  beqz       $t2, .L800CFE00
    /* 8A5D4 800CFDD4 00000000 */   nop
    /* 8A5D8 800CFDD8 8FB80044 */  lw         $t8, 0x44($sp)
    /* 8A5DC 800CFDDC 8DCB000C */  lw         $t3, 0xC($t6)
    /* 8A5E0 800CFDE0 2408002B */  addiu      $t0, $zero, 0x2B
    /* 8A5E4 800CFDE4 030BC821 */  addu       $t9, $t8, $t3
    /* 8A5E8 800CFDE8 A3280000 */  sb         $t0, 0x0($t9)
    /* 8A5EC 800CFDEC 8FAD0038 */  lw         $t5, 0x38($sp)
    /* 8A5F0 800CFDF0 8DA9000C */  lw         $t1, 0xC($t5)
    /* 8A5F4 800CFDF4 252C0001 */  addiu      $t4, $t1, 0x1
    /* 8A5F8 800CFDF8 1000000F */  b          .L800CFE38
    /* 8A5FC 800CFDFC ADAC000C */   sw        $t4, 0xC($t5)
  .L800CFE00:
    /* 8A600 800CFE00 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 8A604 800CFE04 8DEA0030 */  lw         $t2, 0x30($t7)
    /* 8A608 800CFE08 314E0001 */  andi       $t6, $t2, 0x1
    /* 8A60C 800CFE0C 11C0000A */  beqz       $t6, .L800CFE38
    /* 8A610 800CFE10 00000000 */   nop
    /* 8A614 800CFE14 8FAB0044 */  lw         $t3, 0x44($sp)
    /* 8A618 800CFE18 8DE8000C */  lw         $t0, 0xC($t7)
    /* 8A61C 800CFE1C 24180020 */  addiu      $t8, $zero, 0x20
    /* 8A620 800CFE20 0168C821 */  addu       $t9, $t3, $t0
    /* 8A624 800CFE24 A3380000 */  sb         $t8, 0x0($t9)
    /* 8A628 800CFE28 8FA90038 */  lw         $t1, 0x38($sp)
    /* 8A62C 800CFE2C 8D2C000C */  lw         $t4, 0xC($t1)
    /* 8A630 800CFE30 258D0001 */  addiu      $t5, $t4, 0x1
    /* 8A634 800CFE34 AD2D000C */  sw         $t5, 0xC($t1)
  .L800CFE38:
    /* 8A638 800CFE38 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 8A63C 800CFE3C 8FAF0044 */  lw         $t7, 0x44($sp)
    /* 8A640 800CFE40 8D4E000C */  lw         $t6, 0xC($t2)
    /* 8A644 800CFE44 01CF5821 */  addu       $t3, $t6, $t7
    /* 8A648 800CFE48 AD4B0008 */  sw         $t3, 0x8($t2)
    /* 8A64C 800CFE4C 93A50043 */  lbu        $a1, 0x43($sp)
    /* 8A650 800CFE50 0C0343F8 */  jal        _Litob
    /* 8A654 800CFE54 8FA40038 */   lw        $a0, 0x38($sp)
    /* 8A658 800CFE58 1000018F */  b          .L800D0498
    /* 8A65C 800CFE5C 00000000 */   nop
    /* 8A660 800CFE60 8FA80038 */  lw         $t0, 0x38($sp)
    /* 8A664 800CFE64 2401006C */  addiu      $at, $zero, 0x6C
    /* 8A668 800CFE68 91180034 */  lbu        $t8, 0x34($t0)
    /* 8A66C 800CFE6C 17010011 */  bne        $t8, $at, .L800CFEB4
    /* 8A670 800CFE70 00000000 */   nop
    /* 8A674 800CFE74 8FB9003C */  lw         $t9, 0x3C($sp)
    /* 8A678 800CFE78 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8A67C 800CFE7C 8F2C0000 */  lw         $t4, 0x0($t9)
    /* 8A680 800CFE80 258D0003 */  addiu      $t5, $t4, 0x3
    /* 8A684 800CFE84 01A14824 */  and        $t1, $t5, $at
    /* 8A688 800CFE88 252E0004 */  addiu      $t6, $t1, 0x4
    /* 8A68C 800CFE8C AF2E0000 */  sw         $t6, 0x0($t9)
    /* 8A690 800CFE90 8FAF003C */  lw         $t7, 0x3C($sp)
    /* 8A694 800CFE94 8FB80038 */  lw         $t8, 0x38($sp)
    /* 8A698 800CFE98 8DEB0000 */  lw         $t3, 0x0($t7)
    /* 8A69C 800CFE9C 8D6AFFFC */  lw         $t2, -0x4($t3)
    /* 8A6A0 800CFEA0 01404825 */  or         $t1, $t2, $zero
    /* 8A6A4 800CFEA4 000A47C3 */  sra        $t0, $t2, 31
    /* 8A6A8 800CFEA8 AF080000 */  sw         $t0, 0x0($t8)
    /* 8A6AC 800CFEAC 10000024 */  b          .L800CFF40
    /* 8A6B0 800CFEB0 AF090004 */   sw        $t1, 0x4($t8)
  .L800CFEB4:
    /* 8A6B4 800CFEB4 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 8A6B8 800CFEB8 2401004C */  addiu      $at, $zero, 0x4C
    /* 8A6BC 800CFEBC 918D0034 */  lbu        $t5, 0x34($t4)
    /* 8A6C0 800CFEC0 15A10010 */  bne        $t5, $at, .L800CFF04
    /* 8A6C4 800CFEC4 00000000 */   nop
    /* 8A6C8 800CFEC8 8FAE003C */  lw         $t6, 0x3C($sp)
    /* 8A6CC 800CFECC 2401FFF8 */  addiu      $at, $zero, -0x8
    /* 8A6D0 800CFED0 8DD90000 */  lw         $t9, 0x0($t6)
    /* 8A6D4 800CFED4 272F0007 */  addiu      $t7, $t9, 0x7
    /* 8A6D8 800CFED8 01E15824 */  and        $t3, $t7, $at
    /* 8A6DC 800CFEDC 256A0008 */  addiu      $t2, $t3, 0x8
    /* 8A6E0 800CFEE0 ADCA0000 */  sw         $t2, 0x0($t6)
    /* 8A6E4 800CFEE4 8FA8003C */  lw         $t0, 0x3C($sp)
    /* 8A6E8 800CFEE8 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 8A6EC 800CFEEC 8D090000 */  lw         $t1, 0x0($t0)
    /* 8A6F0 800CFEF0 8D38FFF8 */  lw         $t8, -0x8($t1)
    /* 8A6F4 800CFEF4 8D39FFFC */  lw         $t9, -0x4($t1)
    /* 8A6F8 800CFEF8 AD980000 */  sw         $t8, 0x0($t4)
    /* 8A6FC 800CFEFC 10000010 */  b          .L800CFF40
    /* 8A700 800CFF00 AD990004 */   sw        $t9, 0x4($t4)
  .L800CFF04:
    /* 8A704 800CFF04 8FAD003C */  lw         $t5, 0x3C($sp)
    /* 8A708 800CFF08 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8A70C 800CFF0C 8DAF0000 */  lw         $t7, 0x0($t5)
    /* 8A710 800CFF10 25EB0003 */  addiu      $t3, $t7, 0x3
    /* 8A714 800CFF14 01615024 */  and        $t2, $t3, $at
    /* 8A718 800CFF18 254E0004 */  addiu      $t6, $t2, 0x4
    /* 8A71C 800CFF1C ADAE0000 */  sw         $t6, 0x0($t5)
    /* 8A720 800CFF20 8FA8003C */  lw         $t0, 0x3C($sp)
    /* 8A724 800CFF24 8FB90038 */  lw         $t9, 0x38($sp)
    /* 8A728 800CFF28 8D090000 */  lw         $t1, 0x0($t0)
    /* 8A72C 800CFF2C 8D38FFFC */  lw         $t8, -0x4($t1)
    /* 8A730 800CFF30 03006825 */  or         $t5, $t8, $zero
    /* 8A734 800CFF34 001867C3 */  sra        $t4, $t8, 31
    /* 8A738 800CFF38 AF2C0000 */  sw         $t4, 0x0($t9)
    /* 8A73C 800CFF3C AF2D0004 */  sw         $t5, 0x4($t9)
  .L800CFF40:
    /* 8A740 800CFF40 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 8A744 800CFF44 24010068 */  addiu      $at, $zero, 0x68
    /* 8A748 800CFF48 91EB0034 */  lbu        $t3, 0x34($t7)
    /* 8A74C 800CFF4C 1561000A */  bne        $t3, $at, .L800CFF78
    /* 8A750 800CFF50 00000000 */   nop
    /* 8A754 800CFF54 8DEB0004 */  lw         $t3, 0x4($t7)
    /* 8A758 800CFF58 8DEA0000 */  lw         $t2, 0x0($t7)
    /* 8A75C 800CFF5C 24180000 */  addiu      $t8, $zero, 0x0
    /* 8A760 800CFF60 01607025 */  or         $t6, $t3, $zero
    /* 8A764 800CFF64 31C8FFFF */  andi       $t0, $t6, 0xFFFF
    /* 8A768 800CFF68 0100C825 */  or         $t9, $t0, $zero
    /* 8A76C 800CFF6C ADF90004 */  sw         $t9, 0x4($t7)
    /* 8A770 800CFF70 1000000C */  b          .L800CFFA4
    /* 8A774 800CFF74 ADF80000 */   sw        $t8, 0x0($t7)
  .L800CFF78:
    /* 8A778 800CFF78 8FA90038 */  lw         $t1, 0x38($sp)
    /* 8A77C 800CFF7C 912C0034 */  lbu        $t4, 0x34($t1)
    /* 8A780 800CFF80 15800008 */  bnez       $t4, .L800CFFA4
    /* 8A784 800CFF84 00000000 */   nop
    /* 8A788 800CFF88 8D2B0004 */  lw         $t3, 0x4($t1)
    /* 8A78C 800CFF8C 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 8A790 800CFF90 240E0000 */  addiu      $t6, $zero, 0x0
    /* 8A794 800CFF94 01606825 */  or         $t5, $t3, $zero
    /* 8A798 800CFF98 01A07825 */  or         $t7, $t5, $zero
    /* 8A79C 800CFF9C AD2F0004 */  sw         $t7, 0x4($t1)
    /* 8A7A0 800CFFA0 AD2E0000 */  sw         $t6, 0x0($t1)
  .L800CFFA4:
    /* 8A7A4 800CFFA4 8FA80038 */  lw         $t0, 0x38($sp)
    /* 8A7A8 800CFFA8 8D180030 */  lw         $t8, 0x30($t0)
    /* 8A7AC 800CFFAC 33190008 */  andi       $t9, $t8, 0x8
    /* 8A7B0 800CFFB0 1320001A */  beqz       $t9, .L800D001C
    /* 8A7B4 800CFFB4 00000000 */   nop
    /* 8A7B8 800CFFB8 8FAA0044 */  lw         $t2, 0x44($sp)
    /* 8A7BC 800CFFBC 8D0B000C */  lw         $t3, 0xC($t0)
    /* 8A7C0 800CFFC0 240C0030 */  addiu      $t4, $zero, 0x30
    /* 8A7C4 800CFFC4 24010078 */  addiu      $at, $zero, 0x78
    /* 8A7C8 800CFFC8 014B6821 */  addu       $t5, $t2, $t3
    /* 8A7CC 800CFFCC A1AC0000 */  sb         $t4, 0x0($t5)
    /* 8A7D0 800CFFD0 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 8A7D4 800CFFD4 8DCF000C */  lw         $t7, 0xC($t6)
    /* 8A7D8 800CFFD8 25E90001 */  addiu      $t1, $t7, 0x1
    /* 8A7DC 800CFFDC ADC9000C */  sw         $t1, 0xC($t6)
    /* 8A7E0 800CFFE0 93B80043 */  lbu        $t8, 0x43($sp)
    /* 8A7E4 800CFFE4 13010003 */  beq        $t8, $at, .L800CFFF4
    /* 8A7E8 800CFFE8 24010058 */   addiu     $at, $zero, 0x58
    /* 8A7EC 800CFFEC 1701000B */  bne        $t8, $at, .L800D001C
    /* 8A7F0 800CFFF0 00000000 */   nop
  .L800CFFF4:
    /* 8A7F4 800CFFF4 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 8A7F8 800CFFF8 8FA80044 */  lw         $t0, 0x44($sp)
    /* 8A7FC 800CFFFC 93B90043 */  lbu        $t9, 0x43($sp)
    /* 8A800 800D0000 8D4B000C */  lw         $t3, 0xC($t2)
    /* 8A804 800D0004 010B6021 */  addu       $t4, $t0, $t3
    /* 8A808 800D0008 A1990000 */  sb         $t9, 0x0($t4)
    /* 8A80C 800D000C 8FAD0038 */  lw         $t5, 0x38($sp)
    /* 8A810 800D0010 8DAF000C */  lw         $t7, 0xC($t5)
    /* 8A814 800D0014 25E90001 */  addiu      $t1, $t7, 0x1
    /* 8A818 800D0018 ADA9000C */  sw         $t1, 0xC($t5)
  .L800D001C:
    /* 8A81C 800D001C 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 8A820 800D0020 8FAA0044 */  lw         $t2, 0x44($sp)
    /* 8A824 800D0024 8DD8000C */  lw         $t8, 0xC($t6)
    /* 8A828 800D0028 030A4021 */  addu       $t0, $t8, $t2
    /* 8A82C 800D002C ADC80008 */  sw         $t0, 0x8($t6)
    /* 8A830 800D0030 93A50043 */  lbu        $a1, 0x43($sp)
    /* 8A834 800D0034 0C0343F8 */  jal        _Litob
    /* 8A838 800D0038 8FA40038 */   lw        $a0, 0x38($sp)
    /* 8A83C 800D003C 10000116 */  b          .L800D0498
    /* 8A840 800D0040 00000000 */   nop
    /* 8A844 800D0044 8FAB0038 */  lw         $t3, 0x38($sp)
    /* 8A848 800D0048 2401004C */  addiu      $at, $zero, 0x4C
    /* 8A84C 800D004C 91790034 */  lbu        $t9, 0x34($t3)
    /* 8A850 800D0050 17210025 */  bne        $t9, $at, .L800D00E8
    /* 8A854 800D0054 00000000 */   nop
    /* 8A858 800D0058 8FAC003C */  lw         $t4, 0x3C($sp)
    /* 8A85C 800D005C 8D8F0000 */  lw         $t7, 0x0($t4)
    /* 8A860 800D0060 31E90001 */  andi       $t1, $t7, 0x1
    /* 8A864 800D0064 11200007 */  beqz       $t1, .L800D0084
    /* 8A868 800D0068 00000000 */   nop
    /* 8A86C 800D006C 25ED0007 */  addiu      $t5, $t7, 0x7
    /* 8A870 800D0070 AD8D0000 */  sw         $t5, 0x0($t4)
    /* 8A874 800D0074 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 8A878 800D0078 8F100000 */  lw         $s0, 0x0($t8)
    /* 8A87C 800D007C 10000016 */  b          .L800D00D8
    /* 8A880 800D0080 2610FFEA */   addiu     $s0, $s0, -0x16
  .L800D0084:
    /* 8A884 800D0084 8FAA003C */  lw         $t2, 0x3C($sp)
    /* 8A888 800D0088 8D480000 */  lw         $t0, 0x0($t2)
    /* 8A88C 800D008C 310E0002 */  andi       $t6, $t0, 0x2
    /* 8A890 800D0090 11C00007 */  beqz       $t6, .L800D00B0
    /* 8A894 800D0094 00000000 */   nop
    /* 8A898 800D0098 250B000A */  addiu      $t3, $t0, 0xA
    /* 8A89C 800D009C AD4B0000 */  sw         $t3, 0x0($t2)
    /* 8A8A0 800D00A0 8FB9003C */  lw         $t9, 0x3C($sp)
    /* 8A8A4 800D00A4 8F310000 */  lw         $s1, 0x0($t9)
    /* 8A8A8 800D00A8 1000000A */  b          .L800D00D4
    /* 8A8AC 800D00AC 2631FFD8 */   addiu     $s1, $s1, -0x28
  .L800D00B0:
    /* 8A8B0 800D00B0 8FA9003C */  lw         $t1, 0x3C($sp)
    /* 8A8B4 800D00B4 2401FFF8 */  addiu      $at, $zero, -0x8
    /* 8A8B8 800D00B8 8D2F0000 */  lw         $t7, 0x0($t1)
    /* 8A8BC 800D00BC 25ED0007 */  addiu      $t5, $t7, 0x7
    /* 8A8C0 800D00C0 01A16024 */  and        $t4, $t5, $at
    /* 8A8C4 800D00C4 25980008 */  addiu      $t8, $t4, 0x8
    /* 8A8C8 800D00C8 AD380000 */  sw         $t8, 0x0($t1)
    /* 8A8CC 800D00CC 8FAE003C */  lw         $t6, 0x3C($sp)
    /* 8A8D0 800D00D0 8DD10000 */  lw         $s1, 0x0($t6)
  .L800D00D4:
    /* 8A8D4 800D00D4 02208025 */  or         $s0, $s1, $zero
  .L800D00D8:
    /* 8A8D8 800D00D8 D604FFF8 */  ldc1       $f4, -0x8($s0)
    /* 8A8DC 800D00DC 8FA80038 */  lw         $t0, 0x38($sp)
    /* 8A8E0 800D00E0 10000024 */  b          .L800D0174
    /* 8A8E4 800D00E4 F5040000 */   sdc1      $f4, 0x0($t0)
  .L800D00E8:
    /* 8A8E8 800D00E8 8FAB003C */  lw         $t3, 0x3C($sp)
    /* 8A8EC 800D00EC 8D6A0000 */  lw         $t2, 0x0($t3)
    /* 8A8F0 800D00F0 31590001 */  andi       $t9, $t2, 0x1
    /* 8A8F4 800D00F4 13200007 */  beqz       $t9, .L800D0114
    /* 8A8F8 800D00F8 00000000 */   nop
    /* 8A8FC 800D00FC 254F0007 */  addiu      $t7, $t2, 0x7
    /* 8A900 800D0100 AD6F0000 */  sw         $t7, 0x0($t3)
    /* 8A904 800D0104 8FAD003C */  lw         $t5, 0x3C($sp)
    /* 8A908 800D0108 8DB20000 */  lw         $s2, 0x0($t5)
    /* 8A90C 800D010C 10000016 */  b          .L800D0168
    /* 8A910 800D0110 2652FFEA */   addiu     $s2, $s2, -0x16
  .L800D0114:
    /* 8A914 800D0114 8FAC003C */  lw         $t4, 0x3C($sp)
    /* 8A918 800D0118 8D980000 */  lw         $t8, 0x0($t4)
    /* 8A91C 800D011C 33090002 */  andi       $t1, $t8, 0x2
    /* 8A920 800D0120 11200007 */  beqz       $t1, .L800D0140
    /* 8A924 800D0124 00000000 */   nop
    /* 8A928 800D0128 270E000A */  addiu      $t6, $t8, 0xA
    /* 8A92C 800D012C AD8E0000 */  sw         $t6, 0x0($t4)
    /* 8A930 800D0130 8FA8003C */  lw         $t0, 0x3C($sp)
    /* 8A934 800D0134 8D130000 */  lw         $s3, 0x0($t0)
    /* 8A938 800D0138 1000000A */  b          .L800D0164
    /* 8A93C 800D013C 2673FFD8 */   addiu     $s3, $s3, -0x28
  .L800D0140:
    /* 8A940 800D0140 8FB9003C */  lw         $t9, 0x3C($sp)
    /* 8A944 800D0144 2401FFF8 */  addiu      $at, $zero, -0x8
    /* 8A948 800D0148 8F2A0000 */  lw         $t2, 0x0($t9)
    /* 8A94C 800D014C 254F0007 */  addiu      $t7, $t2, 0x7
    /* 8A950 800D0150 01E15824 */  and        $t3, $t7, $at
    /* 8A954 800D0154 256D0008 */  addiu      $t5, $t3, 0x8
    /* 8A958 800D0158 AF2D0000 */  sw         $t5, 0x0($t9)
    /* 8A95C 800D015C 8FA9003C */  lw         $t1, 0x3C($sp)
    /* 8A960 800D0160 8D330000 */  lw         $s3, 0x0($t1)
  .L800D0164:
    /* 8A964 800D0164 02609025 */  or         $s2, $s3, $zero
  .L800D0168:
    /* 8A968 800D0168 D646FFF8 */  ldc1       $f6, -0x8($s2)
    /* 8A96C 800D016C 8FB80038 */  lw         $t8, 0x38($sp)
    /* 8A970 800D0170 F7060000 */  sdc1       $f6, 0x0($t8)
  .L800D0174:
    /* 8A974 800D0174 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 8A978 800D0178 95CC0000 */  lhu        $t4, 0x0($t6)
    /* 8A97C 800D017C 31888000 */  andi       $t0, $t4, 0x8000
    /* 8A980 800D0180 1100000B */  beqz       $t0, .L800D01B0
    /* 8A984 800D0184 00000000 */   nop
    /* 8A988 800D0188 8FAF0044 */  lw         $t7, 0x44($sp)
    /* 8A98C 800D018C 8DCB000C */  lw         $t3, 0xC($t6)
    /* 8A990 800D0190 240A002D */  addiu      $t2, $zero, 0x2D
    /* 8A994 800D0194 01EB6821 */  addu       $t5, $t7, $t3
    /* 8A998 800D0198 A1AA0000 */  sb         $t2, 0x0($t5)
    /* 8A99C 800D019C 8FB90038 */  lw         $t9, 0x38($sp)
    /* 8A9A0 800D01A0 8F29000C */  lw         $t1, 0xC($t9)
    /* 8A9A4 800D01A4 25380001 */  addiu      $t8, $t1, 0x1
    /* 8A9A8 800D01A8 1000001E */  b          .L800D0224
    /* 8A9AC 800D01AC AF38000C */   sw        $t8, 0xC($t9)
  .L800D01B0:
    /* 8A9B0 800D01B0 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 8A9B4 800D01B4 8D880030 */  lw         $t0, 0x30($t4)
    /* 8A9B8 800D01B8 310E0002 */  andi       $t6, $t0, 0x2
    /* 8A9BC 800D01BC 11C0000B */  beqz       $t6, .L800D01EC
    /* 8A9C0 800D01C0 00000000 */   nop
    /* 8A9C4 800D01C4 8FAB0044 */  lw         $t3, 0x44($sp)
    /* 8A9C8 800D01C8 8D8A000C */  lw         $t2, 0xC($t4)
    /* 8A9CC 800D01CC 240F002B */  addiu      $t7, $zero, 0x2B
    /* 8A9D0 800D01D0 016A6821 */  addu       $t5, $t3, $t2
    /* 8A9D4 800D01D4 A1AF0000 */  sb         $t7, 0x0($t5)
    /* 8A9D8 800D01D8 8FA90038 */  lw         $t1, 0x38($sp)
    /* 8A9DC 800D01DC 8D38000C */  lw         $t8, 0xC($t1)
    /* 8A9E0 800D01E0 27190001 */  addiu      $t9, $t8, 0x1
    /* 8A9E4 800D01E4 1000000F */  b          .L800D0224
    /* 8A9E8 800D01E8 AD39000C */   sw        $t9, 0xC($t1)
  .L800D01EC:
    /* 8A9EC 800D01EC 8FA80038 */  lw         $t0, 0x38($sp)
    /* 8A9F0 800D01F0 8D0E0030 */  lw         $t6, 0x30($t0)
    /* 8A9F4 800D01F4 31CC0001 */  andi       $t4, $t6, 0x1
    /* 8A9F8 800D01F8 1180000A */  beqz       $t4, .L800D0224
    /* 8A9FC 800D01FC 00000000 */   nop
    /* 8AA00 800D0200 8FAA0044 */  lw         $t2, 0x44($sp)
    /* 8AA04 800D0204 8D0F000C */  lw         $t7, 0xC($t0)
    /* 8AA08 800D0208 240B0020 */  addiu      $t3, $zero, 0x20
    /* 8AA0C 800D020C 014F6821 */  addu       $t5, $t2, $t7
    /* 8AA10 800D0210 A1AB0000 */  sb         $t3, 0x0($t5)
    /* 8AA14 800D0214 8FB80038 */  lw         $t8, 0x38($sp)
    /* 8AA18 800D0218 8F19000C */  lw         $t9, 0xC($t8)
    /* 8AA1C 800D021C 27290001 */  addiu      $t1, $t9, 0x1
    /* 8AA20 800D0220 AF09000C */  sw         $t1, 0xC($t8)
  .L800D0224:
    /* 8AA24 800D0224 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 8AA28 800D0228 8FA80044 */  lw         $t0, 0x44($sp)
    /* 8AA2C 800D022C 8DCC000C */  lw         $t4, 0xC($t6)
    /* 8AA30 800D0230 01885021 */  addu       $t2, $t4, $t0
    /* 8AA34 800D0234 ADCA0008 */  sw         $t2, 0x8($t6)
    /* 8AA38 800D0238 93A50043 */  lbu        $a1, 0x43($sp)
    /* 8AA3C 800D023C 0C0344B8 */  jal        _Ldtob
    /* 8AA40 800D0240 8FA40038 */   lw        $a0, 0x38($sp)
    /* 8AA44 800D0244 10000094 */  b          .L800D0498
    /* 8AA48 800D0248 00000000 */   nop
    /* 8AA4C 800D024C 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 8AA50 800D0250 24010068 */  addiu      $at, $zero, 0x68
    /* 8AA54 800D0254 91EB0034 */  lbu        $t3, 0x34($t7)
    /* 8AA58 800D0258 1561000F */  bne        $t3, $at, .L800D0298
    /* 8AA5C 800D025C 00000000 */   nop
    /* 8AA60 800D0260 8FAD003C */  lw         $t5, 0x3C($sp)
    /* 8AA64 800D0264 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8AA68 800D0268 8DB90000 */  lw         $t9, 0x0($t5)
    /* 8AA6C 800D026C 27290003 */  addiu      $t1, $t9, 0x3
    /* 8AA70 800D0270 0121C024 */  and        $t8, $t1, $at
    /* 8AA74 800D0274 270C0004 */  addiu      $t4, $t8, 0x4
    /* 8AA78 800D0278 ADAC0000 */  sw         $t4, 0x0($t5)
    /* 8AA7C 800D027C 8FA8003C */  lw         $t0, 0x3C($sp)
    /* 8AA80 800D0280 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 8AA84 800D0284 8D100000 */  lw         $s0, 0x0($t0)
    /* 8AA88 800D0288 8D4E002C */  lw         $t6, 0x2C($t2)
    /* 8AA8C 800D028C 8E0FFFFC */  lw         $t7, -0x4($s0)
    /* 8AA90 800D0290 10000081 */  b          .L800D0498
    /* 8AA94 800D0294 A5EE0000 */   sh        $t6, 0x0($t7)
  .L800D0298:
    /* 8AA98 800D0298 8FAB0038 */  lw         $t3, 0x38($sp)
    /* 8AA9C 800D029C 2401006C */  addiu      $at, $zero, 0x6C
    /* 8AAA0 800D02A0 91790034 */  lbu        $t9, 0x34($t3)
    /* 8AAA4 800D02A4 1721000F */  bne        $t9, $at, .L800D02E4
    /* 8AAA8 800D02A8 00000000 */   nop
    /* 8AAAC 800D02AC 8FA9003C */  lw         $t1, 0x3C($sp)
    /* 8AAB0 800D02B0 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8AAB4 800D02B4 8D380000 */  lw         $t8, 0x0($t1)
    /* 8AAB8 800D02B8 270C0003 */  addiu      $t4, $t8, 0x3
    /* 8AABC 800D02BC 01816824 */  and        $t5, $t4, $at
    /* 8AAC0 800D02C0 25A80004 */  addiu      $t0, $t5, 0x4
    /* 8AAC4 800D02C4 AD280000 */  sw         $t0, 0x0($t1)
    /* 8AAC8 800D02C8 8FAA003C */  lw         $t2, 0x3C($sp)
    /* 8AACC 800D02CC 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 8AAD0 800D02D0 8D500000 */  lw         $s0, 0x0($t2)
    /* 8AAD4 800D02D4 8DCF002C */  lw         $t7, 0x2C($t6)
    /* 8AAD8 800D02D8 8E0BFFFC */  lw         $t3, -0x4($s0)
    /* 8AADC 800D02DC 1000006E */  b          .L800D0498
    /* 8AAE0 800D02E0 AD6F0000 */   sw        $t7, 0x0($t3)
  .L800D02E4:
    /* 8AAE4 800D02E4 8FB90038 */  lw         $t9, 0x38($sp)
    /* 8AAE8 800D02E8 2401004C */  addiu      $at, $zero, 0x4C
    /* 8AAEC 800D02EC 93380034 */  lbu        $t8, 0x34($t9)
    /* 8AAF0 800D02F0 17010012 */  bne        $t8, $at, .L800D033C
    /* 8AAF4 800D02F4 00000000 */   nop
    /* 8AAF8 800D02F8 8FAC003C */  lw         $t4, 0x3C($sp)
    /* 8AAFC 800D02FC 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8AB00 800D0300 24180000 */  addiu      $t8, $zero, 0x0
    /* 8AB04 800D0304 8D8D0000 */  lw         $t5, 0x0($t4)
    /* 8AB08 800D0308 25A80003 */  addiu      $t0, $t5, 0x3
    /* 8AB0C 800D030C 01014824 */  and        $t1, $t0, $at
    /* 8AB10 800D0310 252A0004 */  addiu      $t2, $t1, 0x4
    /* 8AB14 800D0314 AD8A0000 */  sw         $t2, 0x0($t4)
    /* 8AB18 800D0318 8FAE003C */  lw         $t6, 0x3C($sp)
    /* 8AB1C 800D031C 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 8AB20 800D0320 8DD00000 */  lw         $s0, 0x0($t6)
    /* 8AB24 800D0324 8DEB002C */  lw         $t3, 0x2C($t7)
    /* 8AB28 800D0328 8E0DFFFC */  lw         $t5, -0x4($s0)
    /* 8AB2C 800D032C 0160C825 */  or         $t9, $t3, $zero
    /* 8AB30 800D0330 ADB90004 */  sw         $t9, 0x4($t5)
    /* 8AB34 800D0334 10000058 */  b          .L800D0498
    /* 8AB38 800D0338 ADB80000 */   sw        $t8, 0x0($t5)
  .L800D033C:
    /* 8AB3C 800D033C 8FA8003C */  lw         $t0, 0x3C($sp)
    /* 8AB40 800D0340 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8AB44 800D0344 8D090000 */  lw         $t1, 0x0($t0)
    /* 8AB48 800D0348 252A0003 */  addiu      $t2, $t1, 0x3
    /* 8AB4C 800D034C 01416024 */  and        $t4, $t2, $at
    /* 8AB50 800D0350 258E0004 */  addiu      $t6, $t4, 0x4
    /* 8AB54 800D0354 AD0E0000 */  sw         $t6, 0x0($t0)
    /* 8AB58 800D0358 8FAF003C */  lw         $t7, 0x3C($sp)
    /* 8AB5C 800D035C 8FAB0038 */  lw         $t3, 0x38($sp)
    /* 8AB60 800D0360 8DF00000 */  lw         $s0, 0x0($t7)
    /* 8AB64 800D0364 8D78002C */  lw         $t8, 0x2C($t3)
    /* 8AB68 800D0368 8E19FFFC */  lw         $t9, -0x4($s0)
    /* 8AB6C 800D036C 1000004A */  b          .L800D0498
    /* 8AB70 800D0370 AF380000 */   sw        $t8, 0x0($t9)
    /* 8AB74 800D0374 8FAD003C */  lw         $t5, 0x3C($sp)
    /* 8AB78 800D0378 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8AB7C 800D037C 24050078 */  addiu      $a1, $zero, 0x78
    /* 8AB80 800D0380 8DA90000 */  lw         $t1, 0x0($t5)
    /* 8AB84 800D0384 252A0003 */  addiu      $t2, $t1, 0x3
    /* 8AB88 800D0388 01416024 */  and        $t4, $t2, $at
    /* 8AB8C 800D038C 258E0004 */  addiu      $t6, $t4, 0x4
    /* 8AB90 800D0390 ADAE0000 */  sw         $t6, 0x0($t5)
    /* 8AB94 800D0394 8FA8003C */  lw         $t0, 0x3C($sp)
    /* 8AB98 800D0398 8FA90038 */  lw         $t1, 0x38($sp)
    /* 8AB9C 800D039C 8D0F0000 */  lw         $t7, 0x0($t0)
    /* 8ABA0 800D03A0 8DEBFFFC */  lw         $t3, -0x4($t7)
    /* 8ABA4 800D03A4 0160C825 */  or         $t9, $t3, $zero
    /* 8ABA8 800D03A8 000BC7C3 */  sra        $t8, $t3, 31
    /* 8ABAC 800D03AC AD380000 */  sw         $t8, 0x0($t1)
    /* 8ABB0 800D03B0 AD390004 */  sw         $t9, 0x4($t1)
    /* 8ABB4 800D03B4 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 8ABB8 800D03B8 8FAE0044 */  lw         $t6, 0x44($sp)
    /* 8ABBC 800D03BC 8D4C000C */  lw         $t4, 0xC($t2)
    /* 8ABC0 800D03C0 018E6821 */  addu       $t5, $t4, $t6
    /* 8ABC4 800D03C4 AD4D0008 */  sw         $t5, 0x8($t2)
    /* 8ABC8 800D03C8 0C0343F8 */  jal        _Litob
    /* 8ABCC 800D03CC 8FA40038 */   lw        $a0, 0x38($sp)
    /* 8ABD0 800D03D0 10000031 */  b          .L800D0498
    /* 8ABD4 800D03D4 00000000 */   nop
    /* 8ABD8 800D03D8 8FA8003C */  lw         $t0, 0x3C($sp)
    /* 8ABDC 800D03DC 2401FFFC */  addiu      $at, $zero, -0x4
    /* 8ABE0 800D03E0 8D0F0000 */  lw         $t7, 0x0($t0)
    /* 8ABE4 800D03E4 25EB0003 */  addiu      $t3, $t7, 0x3
    /* 8ABE8 800D03E8 0161C024 */  and        $t8, $t3, $at
    /* 8ABEC 800D03EC 27190004 */  addiu      $t9, $t8, 0x4
    /* 8ABF0 800D03F0 AD190000 */  sw         $t9, 0x0($t0)
    /* 8ABF4 800D03F4 8FA9003C */  lw         $t1, 0x3C($sp)
    /* 8ABF8 800D03F8 8FAD0038 */  lw         $t5, 0x38($sp)
    /* 8ABFC 800D03FC 8D2C0000 */  lw         $t4, 0x0($t1)
    /* 8AC00 800D0400 8D8EFFFC */  lw         $t6, -0x4($t4)
    /* 8AC04 800D0404 ADAE0008 */  sw         $t6, 0x8($t5)
    /* 8AC08 800D0408 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 8AC0C 800D040C 0C03413B */  jal        strlen
    /* 8AC10 800D0410 8D440008 */   lw        $a0, 0x8($t2)
    /* 8AC14 800D0414 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 8AC18 800D0418 ADE20014 */  sw         $v0, 0x14($t7)
    /* 8AC1C 800D041C 8FAB0038 */  lw         $t3, 0x38($sp)
    /* 8AC20 800D0420 8D780024 */  lw         $t8, 0x24($t3)
    /* 8AC24 800D0424 0700001C */  bltz       $t8, .L800D0498
    /* 8AC28 800D0428 00000000 */   nop
    /* 8AC2C 800D042C 8D790014 */  lw         $t9, 0x14($t3)
    /* 8AC30 800D0430 0319082A */  slt        $at, $t8, $t9
    /* 8AC34 800D0434 10200018 */  beqz       $at, .L800D0498
    /* 8AC38 800D0438 00000000 */   nop
    /* 8AC3C 800D043C 10000016 */  b          .L800D0498
    /* 8AC40 800D0440 AD780014 */   sw        $t8, 0x14($t3)
  .L800D0444:
    /* 8AC44 800D0444 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 8AC48 800D0448 8FA90044 */  lw         $t1, 0x44($sp)
    /* 8AC4C 800D044C 24080025 */  addiu      $t0, $zero, 0x25
    /* 8AC50 800D0450 8D8E000C */  lw         $t6, 0xC($t4)
    /* 8AC54 800D0454 012E6821 */  addu       $t5, $t1, $t6
    /* 8AC58 800D0458 A1A80000 */  sb         $t0, 0x0($t5)
    /* 8AC5C 800D045C 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 8AC60 800D0460 8D4F000C */  lw         $t7, 0xC($t2)
    /* 8AC64 800D0464 25F90001 */  addiu      $t9, $t7, 0x1
    /* 8AC68 800D0468 1000000B */  b          .L800D0498
    /* 8AC6C 800D046C AD59000C */   sw        $t9, 0xC($t2)
  .L800D0470:
    /* 8AC70 800D0470 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 8AC74 800D0474 8FAB0044 */  lw         $t3, 0x44($sp)
    /* 8AC78 800D0478 93B80043 */  lbu        $t8, 0x43($sp)
    /* 8AC7C 800D047C 8D89000C */  lw         $t1, 0xC($t4)
    /* 8AC80 800D0480 01697021 */  addu       $t6, $t3, $t1
    /* 8AC84 800D0484 A1D80000 */  sb         $t8, 0x0($t6)
    /* 8AC88 800D0488 8FA80038 */  lw         $t0, 0x38($sp)
    /* 8AC8C 800D048C 8D0D000C */  lw         $t5, 0xC($t0)
    /* 8AC90 800D0490 25AF0001 */  addiu      $t7, $t5, 0x1
    /* 8AC94 800D0494 AD0F000C */  sw         $t7, 0xC($t0)
  .L800D0498:
    /* 8AC98 800D0498 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 8AC9C 800D049C 8FB00014 */  lw         $s0, 0x14($sp)
    /* 8ACA0 800D04A0 8FB10018 */  lw         $s1, 0x18($sp)
    /* 8ACA4 800D04A4 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 8ACA8 800D04A8 8FB30020 */  lw         $s3, 0x20($sp)
    /* 8ACAC 800D04AC 03E00008 */  jr         $ra
    /* 8ACB0 800D04B0 27BD0038 */   addiu     $sp, $sp, 0x38
    /* 8ACB4 800D04B4 00000000 */  nop
    /* 8ACB8 800D04B8 00000000 */  nop
    /* 8ACBC 800D04BC 00000000 */  nop
