.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel memcpy
    /* 8ACC0 800D04C0 00801025 */  or         $v0, $a0, $zero
    /* 8ACC4 800D04C4 10C00007 */  beqz       $a2, .L800D04E4
    /* 8ACC8 800D04C8 00A01825 */   or        $v1, $a1, $zero
  .L800D04CC:
    /* 8ACCC 800D04CC 906E0000 */  lbu        $t6, 0x0($v1)
    /* 8ACD0 800D04D0 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 8ACD4 800D04D4 24420001 */  addiu      $v0, $v0, 0x1
    /* 8ACD8 800D04D8 24630001 */  addiu      $v1, $v1, 0x1
    /* 8ACDC 800D04DC 14C0FFFB */  bnez       $a2, .L800D04CC
    /* 8ACE0 800D04E0 A04EFFFF */   sb        $t6, -0x1($v0)
  .L800D04E4:
    /* 8ACE4 800D04E4 03E00008 */  jr         $ra
    /* 8ACE8 800D04E8 00801025 */   or        $v0, $a0, $zero

glabel strlen
    /* 8ACEC 800D04EC 908E0000 */  lbu        $t6, 0x0($a0)
    /* 8ACF0 800D04F0 00801825 */  or         $v1, $a0, $zero
    /* 8ACF4 800D04F4 11C00005 */  beqz       $t6, .L800D050C
    /* 8ACF8 800D04F8 00000000 */   nop
    /* 8ACFC 800D04FC 906F0001 */  lbu        $t7, 0x1($v1)
  .L800D0500:
    /* 8AD00 800D0500 24630001 */  addiu      $v1, $v1, 0x1
    /* 8AD04 800D0504 55E0FFFE */  bnel       $t7, $zero, .L800D0500
    /* 8AD08 800D0508 906F0001 */   lbu       $t7, 0x1($v1)
  .L800D050C:
    /* 8AD0C 800D050C 03E00008 */  jr         $ra
    /* 8AD10 800D0510 00641023 */   subu      $v0, $v1, $a0

glabel func_800D0514
    /* 8AD14 800D0514 90830000 */  lbu        $v1, 0x0($a0)
    /* 8AD18 800D0518 30AE00FF */  andi       $t6, $a1, 0xFF
    /* 8AD1C 800D051C 30A200FF */  andi       $v0, $a1, 0xFF
    /* 8AD20 800D0520 51C3000A */  beql       $t6, $v1, .L800D054C
    /* 8AD24 800D0524 00801025 */   or        $v0, $a0, $zero
  .L800D0528:
    /* 8AD28 800D0528 54600004 */  bnel       $v1, $zero, .L800D053C
    /* 8AD2C 800D052C 90830001 */   lbu       $v1, 0x1($a0)
    /* 8AD30 800D0530 03E00008 */  jr         $ra
    /* 8AD34 800D0534 00001025 */   or        $v0, $zero, $zero
    /* 8AD38 800D0538 90830001 */  lbu        $v1, 0x1($a0)
  .L800D053C:
    /* 8AD3C 800D053C 24840001 */  addiu      $a0, $a0, 0x1
    /* 8AD40 800D0540 1443FFF9 */  bne        $v0, $v1, .L800D0528
    /* 8AD44 800D0544 00000000 */   nop
    /* 8AD48 800D0548 00801025 */  or         $v0, $a0, $zero
  .L800D054C:
    /* 8AD4C 800D054C 03E00008 */  jr         $ra
    /* 8AD50 800D0550 00000000 */   nop
    /* 8AD54 800D0554 00000000 */  nop
    /* 8AD58 800D0558 00000000 */  nop
    /* 8AD5C 800D055C 00000000 */  nop
