.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel __osAiDeviceBusy
    /* 8AEE0 800D06E0 3C0EA450 */  lui        $t6, %hi(D_A450000C)
    /* 8AEE4 800D06E4 8DC4000C */  lw         $a0, %lo(D_A450000C)($t6)
    /* 8AEE8 800D06E8 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 8AEEC 800D06EC 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 8AEF0 800D06F0 00817824 */  and        $t7, $a0, $at
    /* 8AEF4 800D06F4 11E00003 */  beqz       $t7, .L800D0704
    /* 8AEF8 800D06F8 00000000 */   nop
    /* 8AEFC 800D06FC 10000002 */  b          .L800D0708
    /* 8AF00 800D0700 24020001 */   addiu     $v0, $zero, 0x1
  .L800D0704:
    /* 8AF04 800D0704 00001025 */  or         $v0, $zero, $zero
  .L800D0708:
    /* 8AF08 800D0708 03E00008 */  jr         $ra
    /* 8AF0C 800D070C 27BD0008 */   addiu     $sp, $sp, 0x8

glabel func_800D0710
    /* 8AF10 800D0710 00047602 */  srl        $t6, $a0, 24
    /* 8AF14 800D0714 0004C402 */  srl        $t8, $a0, 16
    /* 8AF18 800D0718 00044202 */  srl        $t0, $a0, 8
    /* 8AF1C 800D071C 31CF00FF */  andi       $t7, $t6, 0xFF
    /* 8AF20 800D0720 331900FF */  andi       $t9, $t8, 0xFF
    /* 8AF24 800D0724 310900FF */  andi       $t1, $t0, 0xFF
    /* 8AF28 800D0728 308A00FF */  andi       $t2, $a0, 0xFF
    /* 8AF2C 800D072C A0AF0000 */  sb         $t7, 0x0($a1)
    /* 8AF30 800D0730 A0B90001 */  sb         $t9, 0x1($a1)
    /* 8AF34 800D0734 A0A90002 */  sb         $t1, 0x2($a1)
    /* 8AF38 800D0738 03E00008 */  jr         $ra
    /* 8AF3C 800D073C A0AA0003 */   sb        $t2, 0x3($a1)

glabel func_800D0740
    /* 8AF40 800D0740 908E0000 */  lbu        $t6, 0x0($a0)
    /* 8AF44 800D0744 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 8AF48 800D0748 31CF00FF */  andi       $t7, $t6, 0xFF
    /* 8AF4C 800D074C 000FC600 */  sll        $t8, $t7, 24
    /* 8AF50 800D0750 AFB80004 */  sw         $t8, 0x4($sp)
    /* 8AF54 800D0754 90990001 */  lbu        $t9, 0x1($a0)
    /* 8AF58 800D0758 332800FF */  andi       $t0, $t9, 0xFF
    /* 8AF5C 800D075C 00084C00 */  sll        $t1, $t0, 16
    /* 8AF60 800D0760 03095025 */  or         $t2, $t8, $t1
    /* 8AF64 800D0764 AFAA0004 */  sw         $t2, 0x4($sp)
    /* 8AF68 800D0768 908B0002 */  lbu        $t3, 0x2($a0)
    /* 8AF6C 800D076C 316C00FF */  andi       $t4, $t3, 0xFF
    /* 8AF70 800D0770 000C6A00 */  sll        $t5, $t4, 8
    /* 8AF74 800D0774 014D7025 */  or         $t6, $t2, $t5
    /* 8AF78 800D0778 AFAE0004 */  sw         $t6, 0x4($sp)
    /* 8AF7C 800D077C 908F0003 */  lbu        $t7, 0x3($a0)
    /* 8AF80 800D0780 31F900FF */  andi       $t9, $t7, 0xFF
    /* 8AF84 800D0784 01D94025 */  or         $t0, $t6, $t9
    /* 8AF88 800D0788 AFA80004 */  sw         $t0, 0x4($sp)
    /* 8AF8C 800D078C 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 8AF90 800D0790 03E00008 */  jr         $ra
    /* 8AF94 800D0794 01001025 */   or        $v0, $t0, $zero

glabel func_800D0798
    /* 8AF98 800D0798 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 8AF9C 800D079C 93AE001C */  lbu        $t6, 0x1C($sp)
    /* 8AFA0 800D07A0 AFA50024 */  sw         $a1, 0x24($sp)
    /* 8AFA4 800D07A4 8FB90024 */  lw         $t9, 0x24($sp)
    /* 8AFA8 800D07A8 31CFFF3F */  andi       $t7, $t6, 0xFF3F
    /* 8AFAC 800D07AC 35F80080 */  ori        $t8, $t7, 0x80
    /* 8AFB0 800D07B0 330A00FF */  andi       $t2, $t8, 0xFF
    /* 8AFB4 800D07B4 33280003 */  andi       $t0, $t9, 0x3
    /* 8AFB8 800D07B8 31090003 */  andi       $t1, $t0, 0x3
    /* 8AFBC 800D07BC 314BFFFC */  andi       $t3, $t2, 0xFFFC
    /* 8AFC0 800D07C0 A3B8001C */  sb         $t8, 0x1C($sp)
    /* 8AFC4 800D07C4 012B6025 */  or         $t4, $t1, $t3
    /* 8AFC8 800D07C8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8AFCC 800D07CC AFA40020 */  sw         $a0, 0x20($sp)
    /* 8AFD0 800D07D0 A3AC001C */  sb         $t4, 0x1C($sp)
    /* 8AFD4 800D07D4 1B20000D */  blez       $t9, .L800D080C
    /* 8AFD8 800D07D8 AFA00018 */   sw        $zero, 0x18($sp)
  .L800D07DC:
    /* 8AFDC 800D07DC 8FAD0020 */  lw         $t5, 0x20($sp)
    /* 8AFE0 800D07E0 8FAE0018 */  lw         $t6, 0x18($sp)
    /* 8AFE4 800D07E4 01AE7821 */  addu       $t7, $t5, $t6
    /* 8AFE8 800D07E8 91E80000 */  lbu        $t0, 0x0($t7)
    /* 8AFEC 800D07EC 03AEC021 */  addu       $t8, $sp, $t6
    /* 8AFF0 800D07F0 A308001D */  sb         $t0, 0x1D($t8)
    /* 8AFF4 800D07F4 8FAA0018 */  lw         $t2, 0x18($sp)
    /* 8AFF8 800D07F8 8FAB0024 */  lw         $t3, 0x24($sp)
    /* 8AFFC 800D07FC 25490001 */  addiu      $t1, $t2, 0x1
    /* 8B000 800D0800 012B082A */  slt        $at, $t1, $t3
    /* 8B004 800D0804 1420FFF5 */  bnez       $at, .L800D07DC
    /* 8B008 800D0808 AFA90018 */   sw        $t1, 0x18($sp)
  .L800D080C:
    /* 8B00C 800D080C 27AC001C */  addiu      $t4, $sp, 0x1C
    /* 8B010 800D0810 8D990000 */  lw         $t9, 0x0($t4)
    /* 8B014 800D0814 3C0DC000 */  lui        $t5, (0xC0000000 >> 16)
    /* 8B018 800D0818 0C03482C */  jal        func_800D20B0
    /* 8B01C 800D081C ADB90000 */   sw        $t9, (0xC0000000 & 0xFFFF)($t5)
    /* 8B020 800D0820 304F2000 */  andi       $t7, $v0, 0x2000
    /* 8B024 800D0824 15E00006 */  bnez       $t7, .L800D0840
    /* 8B028 800D0828 00000000 */   nop
  .L800D082C:
    /* 8B02C 800D082C 0C03482C */  jal        func_800D20B0
    /* 8B030 800D0830 00000000 */   nop
    /* 8B034 800D0834 30482000 */  andi       $t0, $v0, 0x2000
    /* 8B038 800D0838 1100FFFC */  beqz       $t0, .L800D082C
    /* 8B03C 800D083C 00000000 */   nop
  .L800D0840:
    /* 8B040 800D0840 3C0EC000 */  lui        $t6, (0xC000000C >> 16)
    /* 8B044 800D0844 ADC0000C */  sw         $zero, (0xC000000C & 0xFFFF)($t6)
    /* 8B048 800D0848 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 8B04C 800D084C 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 8B050 800D0850 03E00008 */  jr         $ra
    /* 8B054 800D0854 00000000 */   nop

glabel func_800D0858
    /* 8B058 800D0858 3C0E800F */  lui        $t6, %hi(D_800E9144)
    /* 8B05C 800D085C 8DCE9144 */  lw         $t6, %lo(D_800E9144)($t6)
    /* 8B060 800D0860 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 8B064 800D0864 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8B068 800D0868 AFA40028 */  sw         $a0, 0x28($sp)
    /* 8B06C 800D086C 15C00010 */  bnez       $t6, .L800D08B0
    /* 8B070 800D0870 AFA5002C */   sw        $a1, 0x2C($sp)
    /* 8B074 800D0874 0C03482C */  jal        func_800D20B0
    /* 8B078 800D0878 00000000 */   nop
    /* 8B07C 800D087C 304F2000 */  andi       $t7, $v0, 0x2000
    /* 8B080 800D0880 15E00006 */  bnez       $t7, .L800D089C
    /* 8B084 800D0884 00000000 */   nop
  .L800D0888:
    /* 8B088 800D0888 0C03482C */  jal        func_800D20B0
    /* 8B08C 800D088C 00000000 */   nop
    /* 8B090 800D0890 30582000 */  andi       $t8, $v0, 0x2000
    /* 8B094 800D0894 1300FFFC */  beqz       $t8, .L800D0888
    /* 8B098 800D0898 00000000 */   nop
  .L800D089C:
    /* 8B09C 800D089C 3C19C000 */  lui        $t9, (0xC000000C >> 16)
    /* 8B0A0 800D08A0 AF20000C */  sw         $zero, (0xC000000C & 0xFFFF)($t9)
    /* 8B0A4 800D08A4 24080001 */  addiu      $t0, $zero, 0x1
    /* 8B0A8 800D08A8 3C01800F */  lui        $at, %hi(D_800E9144)
    /* 8B0AC 800D08AC AC289144 */  sw         $t0, %lo(D_800E9144)($at)
  .L800D08B0:
    /* 8B0B0 800D08B0 8FA9002C */  lw         $t1, 0x2C($sp)
    /* 8B0B4 800D08B4 24010003 */  addiu      $at, $zero, 0x3
    /* 8B0B8 800D08B8 AFA00024 */  sw         $zero, 0x24($sp)
    /* 8B0BC 800D08BC 0121001A */  div        $zero, $t1, $at
    /* 8B0C0 800D08C0 00005010 */  mfhi       $t2
    /* 8B0C4 800D08C4 012A5823 */  subu       $t3, $t1, $t2
    /* 8B0C8 800D08C8 AFAA001C */  sw         $t2, 0x1C($sp)
    /* 8B0CC 800D08CC 1960000C */  blez       $t3, .L800D0900
    /* 8B0D0 800D08D0 AFAB0020 */   sw        $t3, 0x20($sp)
  .L800D08D4:
    /* 8B0D4 800D08D4 8FAC0028 */  lw         $t4, 0x28($sp)
    /* 8B0D8 800D08D8 8FAD0024 */  lw         $t5, 0x24($sp)
    /* 8B0DC 800D08DC 24050003 */  addiu      $a1, $zero, 0x3
    /* 8B0E0 800D08E0 0C0341E6 */  jal        func_800D0798
    /* 8B0E4 800D08E4 018D2021 */   addu      $a0, $t4, $t5
    /* 8B0E8 800D08E8 8FAE0024 */  lw         $t6, 0x24($sp)
    /* 8B0EC 800D08EC 8FB80020 */  lw         $t8, 0x20($sp)
    /* 8B0F0 800D08F0 25CF0003 */  addiu      $t7, $t6, 0x3
    /* 8B0F4 800D08F4 01F8082A */  slt        $at, $t7, $t8
    /* 8B0F8 800D08F8 1420FFF6 */  bnez       $at, .L800D08D4
    /* 8B0FC 800D08FC AFAF0024 */   sw        $t7, 0x24($sp)
  .L800D0900:
    /* 8B100 800D0900 8FB9001C */  lw         $t9, 0x1C($sp)
    /* 8B104 800D0904 1B200006 */  blez       $t9, .L800D0920
    /* 8B108 800D0908 00000000 */   nop
    /* 8B10C 800D090C 8FA80028 */  lw         $t0, 0x28($sp)
    /* 8B110 800D0910 8FA90020 */  lw         $t1, 0x20($sp)
    /* 8B114 800D0914 03202825 */  or         $a1, $t9, $zero
    /* 8B118 800D0918 0C0341E6 */  jal        func_800D0798
    /* 8B11C 800D091C 01092021 */   addu      $a0, $t0, $t1
  .L800D0920:
    /* 8B120 800D0920 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 8B124 800D0924 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 8B128 800D0928 03E00008 */  jr         $ra
    /* 8B12C 800D092C 00000000 */   nop

glabel func_800D0930
    /* 8B130 800D0930 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 8B134 800D0934 3C04801E */  lui        $a0, %hi(kdebugserver_bss_0000)
    /* 8B138 800D0938 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8B13C 800D093C 2484ACF0 */  addiu      $a0, $a0, %lo(kdebugserver_bss_0000)
    /* 8B140 800D0940 0C0341D0 */  jal        func_800D0740
    /* 8B144 800D0944 24840001 */   addiu     $a0, $a0, 0x1
    /* 8B148 800D0948 3C04801E */  lui        $a0, %hi(kdebugserver_bss_0000)
    /* 8B14C 800D094C 2484ACF0 */  addiu      $a0, $a0, %lo(kdebugserver_bss_0000)
    /* 8B150 800D0950 AFA2001C */  sw         $v0, 0x1C($sp)
    /* 8B154 800D0954 0C0341D0 */  jal        func_800D0740
    /* 8B158 800D0958 24840005 */   addiu     $a0, $a0, 0x5
    /* 8B15C 800D095C AFA20018 */  sw         $v0, 0x18($sp)
    /* 8B160 800D0960 8FA50018 */  lw         $a1, 0x18($sp)
    /* 8B164 800D0964 0C034216 */  jal        func_800D0858
    /* 8B168 800D0968 8FA4001C */   lw        $a0, 0x1C($sp)
    /* 8B16C 800D096C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 8B170 800D0970 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 8B174 800D0974 03E00008 */  jr         $ra
    /* 8B178 800D0978 00000000 */   nop

glabel func_800D097C
    /* 8B17C 800D097C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 8B180 800D0980 3C04801E */  lui        $a0, %hi(D_801DADF0)
    /* 8B184 800D0984 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8B188 800D0988 2484ADF0 */  addiu      $a0, $a0, %lo(D_801DADF0)
    /* 8B18C 800D098C 24840020 */  addiu      $a0, $a0, 0x20
    /* 8B190 800D0990 0C034216 */  jal        func_800D0858
    /* 8B194 800D0994 24050190 */   addiu     $a1, $zero, 0x190
    /* 8B198 800D0998 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 8B19C 800D099C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 8B1A0 800D09A0 03E00008 */  jr         $ra
    /* 8B1A4 800D09A4 00000000 */   nop

glabel func_800D09A8
    /* 8B1A8 800D09A8 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 8B1AC 800D09AC AFA40030 */  sw         $a0, 0x30($sp)
    /* 8B1B0 800D09B0 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 8B1B4 800D09B4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 8B1B8 800D09B8 AFB00018 */  sw         $s0, 0x18($sp)
    /* 8B1BC 800D09BC 27AF0028 */  addiu      $t7, $sp, 0x28
    /* 8B1C0 800D09C0 ADEE0000 */  sw         $t6, 0x0($t7)
    /* 8B1C4 800D09C4 93B80028 */  lbu        $t8, 0x28($sp)
    /* 8B1C8 800D09C8 AFA0002C */  sw         $zero, 0x2C($sp)
    /* 8B1CC 800D09CC 33190003 */  andi       $t9, $t8, 0x3
    /* 8B1D0 800D09D0 13200015 */  beqz       $t9, .L800D0A28
    /* 8B1D4 800D09D4 00000000 */   nop
  .L800D09D8:
    /* 8B1D8 800D09D8 8FA8002C */  lw         $t0, 0x2C($sp)
    /* 8B1DC 800D09DC 3C0A800F */  lui        $t2, %hi(D_800E9134)
    /* 8B1E0 800D09E0 8D4A9134 */  lw         $t2, %lo(D_800E9134)($t2)
    /* 8B1E4 800D09E4 03A84821 */  addu       $t1, $sp, $t0
    /* 8B1E8 800D09E8 91290029 */  lbu        $t1, 0x29($t1)
    /* 8B1EC 800D09EC 3C0B800F */  lui        $t3, %hi(D_800E9134)
    /* 8B1F0 800D09F0 8D6B9134 */  lw         $t3, %lo(D_800E9134)($t3)
    /* 8B1F4 800D09F4 3C01801E */  lui        $at, %hi(kdebugserver_bss_0000)
    /* 8B1F8 800D09F8 8FAD002C */  lw         $t5, 0x2C($sp)
    /* 8B1FC 800D09FC 93AF0028 */  lbu        $t7, 0x28($sp)
    /* 8B200 800D0A00 002A0821 */  addu       $at, $at, $t2
    /* 8B204 800D0A04 A029ACF0 */  sb         $t1, %lo(kdebugserver_bss_0000)($at)
    /* 8B208 800D0A08 3C01800F */  lui        $at, %hi(D_800E9134)
    /* 8B20C 800D0A0C 256C0001 */  addiu      $t4, $t3, 0x1
    /* 8B210 800D0A10 AC2C9134 */  sw         $t4, %lo(D_800E9134)($at)
    /* 8B214 800D0A14 25AE0001 */  addiu      $t6, $t5, 0x1
    /* 8B218 800D0A18 31F80003 */  andi       $t8, $t7, 0x3
    /* 8B21C 800D0A1C 01D8082B */  sltu       $at, $t6, $t8
    /* 8B220 800D0A20 1420FFED */  bnez       $at, .L800D09D8
    /* 8B224 800D0A24 AFAE002C */   sw        $t6, 0x2C($sp)
  .L800D0A28:
    /* 8B228 800D0A28 93A80028 */  lbu        $t0, 0x28($sp)
    /* 8B22C 800D0A2C 3C19800F */  lui        $t9, %hi(D_800E9138)
    /* 8B230 800D0A30 8F399138 */  lw         $t9, %lo(D_800E9138)($t9)
    /* 8B234 800D0A34 3C10800F */  lui        $s0, %hi(D_800E9130)
    /* 8B238 800D0A38 8E109130 */  lw         $s0, %lo(D_800E9130)($s0)
    /* 8B23C 800D0A3C 31090003 */  andi       $t1, $t0, 0x3
    /* 8B240 800D0A40 3C01800F */  lui        $at, %hi(D_800E9138)
    /* 8B244 800D0A44 03295023 */  subu       $t2, $t9, $t1
    /* 8B248 800D0A48 12000006 */  beqz       $s0, .L800D0A64
    /* 8B24C 800D0A4C AC2A9138 */   sw        $t2, %lo(D_800E9138)($at)
    /* 8B250 800D0A50 24010001 */  addiu      $at, $zero, 0x1
    /* 8B254 800D0A54 12010026 */  beq        $s0, $at, .L800D0AF0
    /* 8B258 800D0A58 00000000 */   nop
    /* 8B25C 800D0A5C 1000003E */  b          .L800D0B58
    /* 8B260 800D0A60 00000000 */   nop
  .L800D0A64:
    /* 8B264 800D0A64 27AB0028 */  addiu      $t3, $sp, 0x28
    /* 8B268 800D0A68 91700001 */  lbu        $s0, 0x1($t3)
    /* 8B26C 800D0A6C 24010001 */  addiu      $at, $zero, 0x1
    /* 8B270 800D0A70 12010005 */  beq        $s0, $at, .L800D0A88
    /* 8B274 800D0A74 24010002 */   addiu     $at, $zero, 0x2
    /* 8B278 800D0A78 1201000D */  beq        $s0, $at, .L800D0AB0
    /* 8B27C 800D0A7C 00000000 */   nop
    /* 8B280 800D0A80 10000014 */  b          .L800D0AD4
    /* 8B284 800D0A84 00000000 */   nop
  .L800D0A88:
    /* 8B288 800D0A88 93AD0028 */  lbu        $t5, 0x28($sp)
    /* 8B28C 800D0A8C 240C0001 */  addiu      $t4, $zero, 0x1
    /* 8B290 800D0A90 3C01800F */  lui        $at, %hi(D_800E9130)
    /* 8B294 800D0A94 AC2C9130 */  sw         $t4, %lo(D_800E9130)($at)
    /* 8B298 800D0A98 240E0009 */  addiu      $t6, $zero, 0x9
    /* 8B29C 800D0A9C 31AF0003 */  andi       $t7, $t5, 0x3
    /* 8B2A0 800D0AA0 01CFC023 */  subu       $t8, $t6, $t7
    /* 8B2A4 800D0AA4 3C01800F */  lui        $at, %hi(D_800E9138)
    /* 8B2A8 800D0AA8 10000031 */  b          .L800D0B70
    /* 8B2AC 800D0AAC AC389138 */   sw        $t8, %lo(D_800E9138)($at)
  .L800D0AB0:
    /* 8B2B0 800D0AB0 0C03425F */  jal        func_800D097C
    /* 8B2B4 800D0AB4 00000000 */   nop
    /* 8B2B8 800D0AB8 3C01800F */  lui        $at, %hi(D_800E9130)
    /* 8B2BC 800D0ABC AC209130 */  sw         $zero, %lo(D_800E9130)($at)
    /* 8B2C0 800D0AC0 3C01800F */  lui        $at, %hi(D_800E9134)
    /* 8B2C4 800D0AC4 AC209134 */  sw         $zero, %lo(D_800E9134)($at)
    /* 8B2C8 800D0AC8 3C01800F */  lui        $at, %hi(D_800E9138)
    /* 8B2CC 800D0ACC 10000028 */  b          .L800D0B70
    /* 8B2D0 800D0AD0 AC209138 */   sw        $zero, %lo(D_800E9138)($at)
  .L800D0AD4:
    /* 8B2D4 800D0AD4 3C01800F */  lui        $at, %hi(D_800E9130)
    /* 8B2D8 800D0AD8 AC209130 */  sw         $zero, %lo(D_800E9130)($at)
    /* 8B2DC 800D0ADC 3C01800F */  lui        $at, %hi(D_800E9134)
    /* 8B2E0 800D0AE0 AC209134 */  sw         $zero, %lo(D_800E9134)($at)
    /* 8B2E4 800D0AE4 3C01800F */  lui        $at, %hi(D_800E9138)
    /* 8B2E8 800D0AE8 10000021 */  b          .L800D0B70
    /* 8B2EC 800D0AEC AC209138 */   sw        $zero, %lo(D_800E9138)($at)
  .L800D0AF0:
    /* 8B2F0 800D0AF0 3C08800F */  lui        $t0, %hi(D_800E9138)
    /* 8B2F4 800D0AF4 8D089138 */  lw         $t0, %lo(D_800E9138)($t0)
    /* 8B2F8 800D0AF8 1D00001D */  bgtz       $t0, .L800D0B70
    /* 8B2FC 800D0AFC 00000000 */   nop
    /* 8B300 800D0B00 3C19801E */  lui        $t9, %hi(kdebugserver_bss_0000)
    /* 8B304 800D0B04 2739ACF0 */  addiu      $t9, $t9, %lo(kdebugserver_bss_0000)
    /* 8B308 800D0B08 93290000 */  lbu        $t1, 0x0($t9)
    /* 8B30C 800D0B0C 24010001 */  addiu      $at, $zero, 0x1
    /* 8B310 800D0B10 1521000A */  bne        $t1, $at, .L800D0B3C
    /* 8B314 800D0B14 00000000 */   nop
    /* 8B318 800D0B18 0C03424C */  jal        func_800D0930
    /* 8B31C 800D0B1C 00000000 */   nop
    /* 8B320 800D0B20 3C01800F */  lui        $at, %hi(D_800E9130)
    /* 8B324 800D0B24 AC209130 */  sw         $zero, %lo(D_800E9130)($at)
    /* 8B328 800D0B28 3C01800F */  lui        $at, %hi(D_800E9134)
    /* 8B32C 800D0B2C AC209134 */  sw         $zero, %lo(D_800E9134)($at)
    /* 8B330 800D0B30 3C01800F */  lui        $at, %hi(D_800E9138)
    /* 8B334 800D0B34 1000000E */  b          .L800D0B70
    /* 8B338 800D0B38 AC209138 */   sw        $zero, %lo(D_800E9138)($at)
  .L800D0B3C:
    /* 8B33C 800D0B3C 3C01800F */  lui        $at, %hi(D_800E9130)
    /* 8B340 800D0B40 AC209130 */  sw         $zero, %lo(D_800E9130)($at)
    /* 8B344 800D0B44 3C01800F */  lui        $at, %hi(D_800E9134)
    /* 8B348 800D0B48 AC209134 */  sw         $zero, %lo(D_800E9134)($at)
    /* 8B34C 800D0B4C 3C01800F */  lui        $at, %hi(D_800E9138)
    /* 8B350 800D0B50 10000007 */  b          .L800D0B70
    /* 8B354 800D0B54 AC209138 */   sw        $zero, %lo(D_800E9138)($at)
  .L800D0B58:
    /* 8B358 800D0B58 3C01800F */  lui        $at, %hi(D_800E9130)
    /* 8B35C 800D0B5C AC209130 */  sw         $zero, %lo(D_800E9130)($at)
    /* 8B360 800D0B60 3C01800F */  lui        $at, %hi(D_800E9134)
    /* 8B364 800D0B64 AC209134 */  sw         $zero, %lo(D_800E9134)($at)
    /* 8B368 800D0B68 3C01800F */  lui        $at, %hi(D_800E9138)
    /* 8B36C 800D0B6C AC209138 */  sw         $zero, %lo(D_800E9138)($at)
  .L800D0B70:
    /* 8B370 800D0B70 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 8B374 800D0B74 8FB00018 */  lw         $s0, 0x18($sp)
    /* 8B378 800D0B78 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 8B37C 800D0B7C 03E00008 */  jr         $ra
    /* 8B380 800D0B80 00000000 */   nop
    /* 8B384 800D0B84 00000000 */  nop
    /* 8B388 800D0B88 00000000 */  nop
    /* 8B38C 800D0B8C 00000000 */  nop
