.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800D0B90
    /* 8B390 800D0B90 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 8B394 800D0B94 AFA40028 */  sw         $a0, 0x28($sp)
    /* 8B398 800D0B98 8FAE0028 */  lw         $t6, 0x28($sp)
    /* 8B39C 800D0B9C 93A80024 */  lbu        $t0, 0x24($sp)
    /* 8B3A0 800D0BA0 AFA5002C */  sw         $a1, 0x2C($sp)
    /* 8B3A4 800D0BA4 31CF0003 */  andi       $t7, $t6, 0x3
    /* 8B3A8 800D0BA8 8FAB002C */  lw         $t3, 0x2C($sp)
    /* 8B3AC 800D0BAC 000FC180 */  sll        $t8, $t7, 6
    /* 8B3B0 800D0BB0 331900C0 */  andi       $t9, $t8, 0xC0
    /* 8B3B4 800D0BB4 3109FF3F */  andi       $t1, $t0, 0xFF3F
    /* 8B3B8 800D0BB8 03295025 */  or         $t2, $t9, $t1
    /* 8B3BC 800D0BBC 314E00FF */  andi       $t6, $t2, 0xFF
    /* 8B3C0 800D0BC0 316C0003 */  andi       $t4, $t3, 0x3
    /* 8B3C4 800D0BC4 318D0003 */  andi       $t5, $t4, 0x3
    /* 8B3C8 800D0BC8 31CFFFFC */  andi       $t7, $t6, 0xFFFC
    /* 8B3CC 800D0BCC A3AA0024 */  sb         $t2, 0x24($sp)
    /* 8B3D0 800D0BD0 01AFC025 */  or         $t8, $t5, $t7
    /* 8B3D4 800D0BD4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8B3D8 800D0BD8 AFA60030 */  sw         $a2, 0x30($sp)
    /* 8B3DC 800D0BDC A3B80024 */  sb         $t8, 0x24($sp)
    /* 8B3E0 800D0BE0 1960000D */  blez       $t3, .L800D0C18
    /* 8B3E4 800D0BE4 AFA00020 */   sw        $zero, 0x20($sp)
  .L800D0BE8:
    /* 8B3E8 800D0BE8 8FA80030 */  lw         $t0, 0x30($sp)
    /* 8B3EC 800D0BEC 8FB90020 */  lw         $t9, 0x20($sp)
    /* 8B3F0 800D0BF0 01194821 */  addu       $t1, $t0, $t9
    /* 8B3F4 800D0BF4 912C0000 */  lbu        $t4, 0x0($t1)
    /* 8B3F8 800D0BF8 03B95021 */  addu       $t2, $sp, $t9
    /* 8B3FC 800D0BFC A14C0025 */  sb         $t4, 0x25($t2)
    /* 8B400 800D0C00 8FAE0020 */  lw         $t6, 0x20($sp)
    /* 8B404 800D0C04 8FAF002C */  lw         $t7, 0x2C($sp)
    /* 8B408 800D0C08 25CD0001 */  addiu      $t5, $t6, 0x1
    /* 8B40C 800D0C0C 01AF082A */  slt        $at, $t5, $t7
    /* 8B410 800D0C10 1420FFF5 */  bnez       $at, .L800D0BE8
    /* 8B414 800D0C14 AFAD0020 */   sw        $t5, 0x20($sp)
  .L800D0C18:
    /* 8B418 800D0C18 3C04800F */  lui        $a0, %hi(D_800E9144)
    /* 8B41C 800D0C1C 0C034830 */  jal        __osAtomicDec
    /* 8B420 800D0C20 24849144 */   addiu     $a0, $a0, %lo(D_800E9144)
    /* 8B424 800D0C24 14400006 */  bnez       $v0, .L800D0C40
    /* 8B428 800D0C28 00000000 */   nop
  .L800D0C2C:
    /* 8B42C 800D0C2C 3C04800F */  lui        $a0, %hi(D_800E9144)
    /* 8B430 800D0C30 0C034830 */  jal        __osAtomicDec
    /* 8B434 800D0C34 24849144 */   addiu     $a0, $a0, %lo(D_800E9144)
    /* 8B438 800D0C38 1040FFFC */  beqz       $v0, .L800D0C2C
    /* 8B43C 800D0C3C 00000000 */   nop
  .L800D0C40:
    /* 8B440 800D0C40 0C032AB4 */  jal        __osDisableInt
    /* 8B444 800D0C44 00000000 */   nop
    /* 8B448 800D0C48 AFA2001C */  sw         $v0, 0x1C($sp)
    /* 8B44C 800D0C4C 27B80024 */  addiu      $t8, $sp, 0x24
    /* 8B450 800D0C50 8F0B0000 */  lw         $t3, 0x0($t8)
    /* 8B454 800D0C54 3C08C000 */  lui        $t0, (0xC0000000 >> 16)
    /* 8B458 800D0C58 0C03482C */  jal        func_800D20B0
    /* 8B45C 800D0C5C AD0B0000 */   sw        $t3, (0xC0000000 & 0xFFFF)($t0)
    /* 8B460 800D0C60 30492000 */  andi       $t1, $v0, 0x2000
    /* 8B464 800D0C64 15200006 */  bnez       $t1, .L800D0C80
    /* 8B468 800D0C68 00000000 */   nop
  .L800D0C6C:
    /* 8B46C 800D0C6C 0C03482C */  jal        func_800D20B0
    /* 8B470 800D0C70 00000000 */   nop
    /* 8B474 800D0C74 304C2000 */  andi       $t4, $v0, 0x2000
    /* 8B478 800D0C78 1180FFFC */  beqz       $t4, .L800D0C6C
    /* 8B47C 800D0C7C 00000000 */   nop
  .L800D0C80:
    /* 8B480 800D0C80 3C19C000 */  lui        $t9, (0xC000000C >> 16)
    /* 8B484 800D0C84 AF20000C */  sw         $zero, (0xC000000C & 0xFFFF)($t9)
    /* 8B488 800D0C88 3C0A800F */  lui        $t2, %hi(D_800E9144)
    /* 8B48C 800D0C8C 8D4A9144 */  lw         $t2, %lo(D_800E9144)($t2)
    /* 8B490 800D0C90 3C01800F */  lui        $at, %hi(D_800E9144)
    /* 8B494 800D0C94 8FA4001C */  lw         $a0, 0x1C($sp)
    /* 8B498 800D0C98 254E0001 */  addiu      $t6, $t2, 0x1
    /* 8B49C 800D0C9C 0C032ABC */  jal        __osRestoreInt
    /* 8B4A0 800D0CA0 AC2E9144 */   sw        $t6, %lo(D_800E9144)($at)
    /* 8B4A4 800D0CA4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 8B4A8 800D0CA8 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 8B4AC 800D0CAC 03E00008 */  jr         $ra
    /* 8B4B0 800D0CB0 00000000 */   nop
    /* 8B4B4 800D0CB4 00000000 */  nop
    /* 8B4B8 800D0CB8 00000000 */  nop
    /* 8B4BC 800D0CBC 00000000 */  nop
