.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel __osSiDeviceBusy
    /* 8B630 800D0E30 3C0EA480 */  lui        $t6, %hi(D_A4800018)
    /* 8B634 800D0E34 8DC40018 */  lw         $a0, %lo(D_A4800018)($t6)
    /* 8B638 800D0E38 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 8B63C 800D0E3C 308F0003 */  andi       $t7, $a0, 0x3
    /* 8B640 800D0E40 11E00003 */  beqz       $t7, .L800D0E50
    /* 8B644 800D0E44 00000000 */   nop
    /* 8B648 800D0E48 10000002 */  b          .L800D0E54
    /* 8B64C 800D0E4C 24020001 */   addiu     $v0, $zero, 0x1
  .L800D0E50:
    /* 8B650 800D0E50 00001025 */  or         $v0, $zero, $zero
  .L800D0E54:
    /* 8B654 800D0E54 03E00008 */  jr         $ra
    /* 8B658 800D0E58 27BD0008 */   addiu     $sp, $sp, 0x8
    /* 8B65C 800D0E5C 00000000 */  nop
