.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_800D0E60
    /* 8B660 800D0E60 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 8B664 800D0E64 3084FFFF */  andi       $a0, $a0, 0xFFFF
    /* 8B668 800D0E68 A3A0000F */  sb         $zero, 0xF($sp)
    /* 8B66C 800D0E6C AFA00008 */  sw         $zero, 0x8($sp)
  .L800D0E70:
    /* 8B670 800D0E70 93AE000F */  lbu        $t6, 0xF($sp)
    /* 8B674 800D0E74 31CF0010 */  andi       $t7, $t6, 0x10
    /* 8B678 800D0E78 11E00004 */  beqz       $t7, .L800D0E8C
    /* 8B67C 800D0E7C 00000000 */   nop
    /* 8B680 800D0E80 24180015 */  addiu      $t8, $zero, 0x15
    /* 8B684 800D0E84 10000002 */  b          .L800D0E90
    /* 8B688 800D0E88 A3B8000E */   sb        $t8, 0xE($sp)
  .L800D0E8C:
    /* 8B68C 800D0E8C A3A0000E */  sb         $zero, 0xE($sp)
  .L800D0E90:
    /* 8B690 800D0E90 93B9000F */  lbu        $t9, 0xF($sp)
    /* 8B694 800D0E94 30890400 */  andi       $t1, $a0, 0x400
    /* 8B698 800D0E98 00194040 */  sll        $t0, $t9, 1
    /* 8B69C 800D0E9C 11200003 */  beqz       $t1, .L800D0EAC
    /* 8B6A0 800D0EA0 A3A8000F */   sb        $t0, 0xF($sp)
    /* 8B6A4 800D0EA4 10000002 */  b          .L800D0EB0
    /* 8B6A8 800D0EA8 24050001 */   addiu     $a1, $zero, 0x1
  .L800D0EAC:
    /* 8B6AC 800D0EAC 00002825 */  or         $a1, $zero, $zero
  .L800D0EB0:
    /* 8B6B0 800D0EB0 93AA000F */  lbu        $t2, 0xF($sp)
    /* 8B6B4 800D0EB4 8FA80008 */  lw         $t0, 0x8($sp)
    /* 8B6B8 800D0EB8 93AF000E */  lbu        $t7, 0xE($sp)
    /* 8B6BC 800D0EBC 30AB00FF */  andi       $t3, $a1, 0xFF
    /* 8B6C0 800D0EC0 00046840 */  sll        $t5, $a0, 1
    /* 8B6C4 800D0EC4 014B6025 */  or         $t4, $t2, $t3
    /* 8B6C8 800D0EC8 01A02025 */  or         $a0, $t5, $zero
    /* 8B6CC 800D0ECC 319800FF */  andi       $t8, $t4, 0xFF
    /* 8B6D0 800D0ED0 25090001 */  addiu      $t1, $t0, 0x1
    /* 8B6D4 800D0ED4 29210010 */  slti       $at, $t1, 0x10
    /* 8B6D8 800D0ED8 A3AC000F */  sb         $t4, 0xF($sp)
    /* 8B6DC 800D0EDC 308EFFFF */  andi       $t6, $a0, 0xFFFF
    /* 8B6E0 800D0EE0 030FC826 */  xor        $t9, $t8, $t7
    /* 8B6E4 800D0EE4 AFA90008 */  sw         $t1, 0x8($sp)
    /* 8B6E8 800D0EE8 01C02025 */  or         $a0, $t6, $zero
    /* 8B6EC 800D0EEC 1420FFE0 */  bnez       $at, .L800D0E70
    /* 8B6F0 800D0EF0 A3B9000F */   sb        $t9, 0xF($sp)
    /* 8B6F4 800D0EF4 93A2000F */  lbu        $v0, 0xF($sp)
    /* 8B6F8 800D0EF8 27BD0010 */  addiu      $sp, $sp, 0x10
    /* 8B6FC 800D0EFC 304A001F */  andi       $t2, $v0, 0x1F
    /* 8B700 800D0F00 01401025 */  or         $v0, $t2, $zero
    /* 8B704 800D0F04 304B00FF */  andi       $t3, $v0, 0xFF
    /* 8B708 800D0F08 03E00008 */  jr         $ra
    /* 8B70C 800D0F0C 01601025 */   or        $v0, $t3, $zero

glabel func_800D0F10
    /* 8B710 800D0F10 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 8B714 800D0F14 A3A0000F */  sb         $zero, 0xF($sp)
    /* 8B718 800D0F18 AFA00008 */  sw         $zero, 0x8($sp)
  .L800D0F1C:
    /* 8B71C 800D0F1C 240E0007 */  addiu      $t6, $zero, 0x7
    /* 8B720 800D0F20 AFAE0004 */  sw         $t6, 0x4($sp)
  .L800D0F24:
    /* 8B724 800D0F24 93AF000F */  lbu        $t7, 0xF($sp)
    /* 8B728 800D0F28 31F80080 */  andi       $t8, $t7, 0x80
    /* 8B72C 800D0F2C 13000004 */  beqz       $t8, .L800D0F40
    /* 8B730 800D0F30 00000000 */   nop
    /* 8B734 800D0F34 24190085 */  addiu      $t9, $zero, 0x85
    /* 8B738 800D0F38 10000002 */  b          .L800D0F44
    /* 8B73C 800D0F3C A3B9000E */   sb        $t9, 0xE($sp)
  .L800D0F40:
    /* 8B740 800D0F40 A3A0000E */  sb         $zero, 0xE($sp)
  .L800D0F44:
    /* 8B744 800D0F44 93A8000F */  lbu        $t0, 0xF($sp)
    /* 8B748 800D0F48 8FAA0008 */  lw         $t2, 0x8($sp)
    /* 8B74C 800D0F4C 24010020 */  addiu      $at, $zero, 0x20
    /* 8B750 800D0F50 00084840 */  sll        $t1, $t0, 1
    /* 8B754 800D0F54 15410004 */  bne        $t2, $at, .L800D0F68
    /* 8B758 800D0F58 A3A9000F */   sb        $t1, 0xF($sp)
    /* 8B75C 800D0F5C 312B00FF */  andi       $t3, $t1, 0xFF
    /* 8B760 800D0F60 1000000E */  b          .L800D0F9C
    /* 8B764 800D0F64 A3AB000F */   sb        $t3, 0xF($sp)
  .L800D0F68:
    /* 8B768 800D0F68 8FAD0004 */  lw         $t5, 0x4($sp)
    /* 8B76C 800D0F6C 908C0000 */  lbu        $t4, 0x0($a0)
    /* 8B770 800D0F70 240E0001 */  addiu      $t6, $zero, 0x1
    /* 8B774 800D0F74 01AE7804 */  sllv       $t7, $t6, $t5
    /* 8B778 800D0F78 018FC024 */  and        $t8, $t4, $t7
    /* 8B77C 800D0F7C 13000003 */  beqz       $t8, .L800D0F8C
    /* 8B780 800D0F80 00000000 */   nop
    /* 8B784 800D0F84 10000002 */  b          .L800D0F90
    /* 8B788 800D0F88 24050001 */   addiu     $a1, $zero, 0x1
  .L800D0F8C:
    /* 8B78C 800D0F8C 00002825 */  or         $a1, $zero, $zero
  .L800D0F90:
    /* 8B790 800D0F90 93B9000F */  lbu        $t9, 0xF($sp)
    /* 8B794 800D0F94 03254025 */  or         $t0, $t9, $a1
    /* 8B798 800D0F98 A3A8000F */  sb         $t0, 0xF($sp)
  .L800D0F9C:
    /* 8B79C 800D0F9C 8FAE0004 */  lw         $t6, 0x4($sp)
    /* 8B7A0 800D0FA0 93AA000F */  lbu        $t2, 0xF($sp)
    /* 8B7A4 800D0FA4 93A9000E */  lbu        $t1, 0xE($sp)
    /* 8B7A8 800D0FA8 25CDFFFF */  addiu      $t5, $t6, -0x1
    /* 8B7AC 800D0FAC AFAD0004 */  sw         $t5, 0x4($sp)
    /* 8B7B0 800D0FB0 01495826 */  xor        $t3, $t2, $t1
    /* 8B7B4 800D0FB4 05A1FFDB */  bgez       $t5, .L800D0F24
    /* 8B7B8 800D0FB8 A3AB000F */   sb        $t3, 0xF($sp)
    /* 8B7BC 800D0FBC 8FAC0008 */  lw         $t4, 0x8($sp)
    /* 8B7C0 800D0FC0 24840001 */  addiu      $a0, $a0, 0x1
    /* 8B7C4 800D0FC4 258F0001 */  addiu      $t7, $t4, 0x1
    /* 8B7C8 800D0FC8 29E10021 */  slti       $at, $t7, 0x21
    /* 8B7CC 800D0FCC 1420FFD3 */  bnez       $at, .L800D0F1C
    /* 8B7D0 800D0FD0 AFAF0008 */   sw        $t7, 0x8($sp)
    /* 8B7D4 800D0FD4 93A2000F */  lbu        $v0, 0xF($sp)
    /* 8B7D8 800D0FD8 03E00008 */  jr         $ra
    /* 8B7DC 800D0FDC 27BD0010 */   addiu     $sp, $sp, 0x10
