.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_80046800
    /* 1000 80046800 3C08800F */  lui        $t0, %hi(D_800EEDD0)
    /* 1004 80046804 3C09000E */  lui        $t1, (0xEC1D0 >> 16)
    /* 1008 80046808 2508EDD0 */  addiu      $t0, $t0, %lo(D_800EEDD0)
    /* 100C 8004680C 3529C1D0 */  ori        $t1, $t1, (0xEC1D0 & 0xFFFF)
  .L80046810:
    /* 1010 80046810 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1014 80046814 AD000000 */  sw         $zero, 0x0($t0)
    /* 1018 80046818 AD000004 */  sw         $zero, 0x4($t0)
    /* 101C 8004681C 1520FFFC */  bnez       $t1, .L80046810
    /* 1020 80046820 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1024 80046824 3C0A8004 */  lui        $t2, %hi(func_80047AA4)
    /* 1028 80046828 3C1D8015 */  lui        $sp, %hi(D_80151BE0)
    /* 102C 8004682C 254A7AA4 */  addiu      $t2, $t2, %lo(func_80047AA4)
    /* 1030 80046830 01400008 */  jr         $t2
    /* 1034 80046834 27BD1BE0 */   addiu     $sp, $sp, %lo(D_80151BE0)
.size func_80046800, . - func_80046800
    /* 1038 80046838 00000000 */  nop
    /* 103C 8004683C 00000000 */  nop
    /* 1040 80046840 00000000 */  nop
    /* 1044 80046844 00000000 */  nop
    /* 1048 80046848 00000000 */  nop
    /* 104C 8004684C 00000000 */  nop
