.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel fast3d_800D22B0
    /* 8CAB0 800D22B0 34210001 */  ori        $at, $at, 0x1
    /* 8CAB4 800D22B4 0900041A */  j          func_84001068
    /* 8CAB8 800D22B8 20010FC0 */   addi      $at, $zero, 0xFC0 /* handwritten instruction */

/* Handwritten function */
glabel func_800D22BC
    /* 8CABC 800D22BC 8C220010 */  lw         $v0, 0x10($at)
    /* 8CAC0 800D22C0 20030F7F */  addi       $v1, $zero, 0xF7F /* handwritten instruction */
    /* 8CAC4 800D22C4 20071080 */  addi       $a3, $zero, 0x1080 /* handwritten instruction */
    /* 8CAC8 800D22C8 40870000 */  mtc0       $a3, $0 /* handwritten instruction */
    /* 8CACC 800D22CC 40820800 */  mtc0       $v0, $1 /* handwritten instruction */
    /* 8CAD0 800D22D0 40831000 */  mtc0       $v1, $2 /* handwritten instruction */
  .L800D22D4:
    /* 8CAD4 800D22D4 40043000 */  mfc0       $a0, $6 /* handwritten instruction */
    /* 8CAD8 800D22D8 1480FFFE */  bnez       $a0, .L800D22D4
    /* 8CADC 800D22DC 00000000 */   nop
    /* 8CAE0 800D22E0 0D000410 */  jal        func_84001040
    /* 8CAE4 800D22E4 00000000 */   nop
    /* 8CAE8 800D22E8 00E00008 */  jr         $a3
    /* 8CAEC 800D22EC 40803800 */   mtc0      $zero, $7 /* handwritten instruction */
  .L800D22F0:
    /* 8CAF0 800D22F0 40082000 */  mfc0       $t0, $4 /* handwritten instruction */
    /* 8CAF4 800D22F4 31080080 */  andi       $t0, $t0, 0x80
    /* 8CAF8 800D22F8 15000002 */  bnez       $t0, .L800D2304
    /* 8CAFC 800D22FC 00000000 */   nop
    /* 8CB00 800D2300 03E00008 */  jr         $ra
  .L800D2304:
    /* 8CB04 800D2304 40803800 */   mtc0      $zero, $7 /* handwritten instruction */
    /* 8CB08 800D2308 34085200 */  ori        $t0, $zero, 0x5200
    /* 8CB0C 800D230C 40882000 */  mtc0       $t0, $4 /* handwritten instruction */
    /* 8CB10 800D2310 0000000D */  break      0
    /* 8CB14 800D2314 00000000 */  nop
    /* 8CB18 800D2318 8C220004 */  lw         $v0, 0x4($at)
    /* 8CB1C 800D231C 30420002 */  andi       $v0, $v0, 0x2
    /* 8CB20 800D2320 10400007 */  beqz       $v0, .L800D2340
    /* 8CB24 800D2324 00000000 */   nop
    /* 8CB28 800D2328 0D000410 */  jal        func_84001040
    /* 8CB2C 800D232C 00000000 */   nop
    /* 8CB30 800D2330 40025800 */  mfc0       $v0, $11 /* handwritten instruction */
    /* 8CB34 800D2334 30420100 */  andi       $v0, $v0, 0x100
    /* 8CB38 800D2338 1C40FFED */  bgtz       $v0, .L800D22F0
    /* 8CB3C 800D233C 00000000 */   nop
  .L800D2340:
    /* 8CB40 800D2340 8C220018 */  lw         $v0, 0x18($at)
    /* 8CB44 800D2344 8C23001C */  lw         $v1, 0x1C($at)
    /* 8CB48 800D2348 2063FFFF */  addi       $v1, $v1, -0x1 /* handwritten instruction */
  .L800D234C:
    /* 8CB4C 800D234C 401E2800 */  mfc0       $fp, $5 /* handwritten instruction */
    /* 8CB50 800D2350 17C0FFFE */  bnez       $fp, .L800D234C
    /* 8CB54 800D2354 00000000 */   nop
    /* 8CB58 800D2358 40800000 */  mtc0       $zero, $0 /* handwritten instruction */
    /* 8CB5C 800D235C 40820800 */  mtc0       $v0, $1 /* handwritten instruction */
    /* 8CB60 800D2360 40831000 */  mtc0       $v1, $2 /* handwritten instruction */
  .L800D2364:
    /* 8CB64 800D2364 40043000 */  mfc0       $a0, $6 /* handwritten instruction */
    /* 8CB68 800D2368 1480FFFE */  bnez       $a0, .L800D2364
    /* 8CB6C 800D236C 00000000 */   nop
    /* 8CB70 800D2370 0D000410 */  jal        func_84001040
    /* 8CB74 800D2374 00000000 */   nop
    /* 8CB78 800D2378 09000403 */  j          func_8400100C
    /* 8CB7C 800D237C 00000000 */   nop
