.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_1C370_802094B0
    /* 1C3CB0 802094B0 00000000 */  nop
    /* 1C3CB4 802094B4 00000000 */  nop

/* Handwritten function */
glabel func_1C370_802094B8
    /* 1C3CB8 802094B8 0000000C */  syscall    0 /* handwritten instruction */
    /* 1C3CBC 802094BC FFFFFFF8 */  sd         $ra, -0x8($ra)
    /* 1C3CC0 802094C0 0000000C */  syscall    0 /* handwritten instruction */
    /* 1C3CC4 802094C4 00000014 */  dsllv      $zero, $zero, $zero
    /* 1C3CC8 802094C8 00000000 */  nop
    /* 1C3CCC 802094CC 00000004 */  sllv       $zero, $zero, $zero
    /* 1C3CD0 802094D0 FFFFFFF8 */  sd         $ra, -0x8($ra)
    /* 1C3CD4 802094D4 00000000 */  nop
    /* 1C3CD8 802094D8 00000000 */  nop
    /* 1C3CDC 802094DC 00000000 */  nop
    /* 1C3CE0 802094E0 802C5C10 */  lb         $t4, 0x5C10($at)
    /* 1C3CE4 802094E4 802C5C1C */  lb         $t4, 0x5C1C($at)
    /* 1C3CE8 802094E8 802C5C4C */  lb         $t4, 0x5C4C($at)
    /* 1C3CEC 802094EC 802C5C6C */  lb         $t4, 0x5C6C($at)
    /* 1C3CF0 802094F0 802C5CF0 */  lb         $t4, 0x5CF0($at)
    /* 1C3CF4 802094F4 802C5CF0 */  lb         $t4, 0x5CF0($at)
    /* 1C3CF8 802094F8 802C5CF0 */  lb         $t4, 0x5CF0($at)
    /* 1C3CFC 802094FC 802C5CA8 */  lb         $t4, 0x5CA8($at)
