.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel bzero
    /* 84D00 800CA500 28A1000C */  slti       $at, $a1, 0xC
    /* 84D04 800CA504 1420001D */  bnez       $at, .L800CA57C
    /* 84D08 800CA508 00041823 */   negu      $v1, $a0
    /* 84D0C 800CA50C 30630003 */  andi       $v1, $v1, 0x3
    /* 84D10 800CA510 10600003 */  beqz       $v1, .L800CA520
    /* 84D14 800CA514 00A32823 */   subu      $a1, $a1, $v1
    /* 84D18 800CA518 A8800000 */  swl        $zero, 0x0($a0)
    /* 84D1C 800CA51C 00832021 */  addu       $a0, $a0, $v1
  .L800CA520:
    /* 84D20 800CA520 2401FFE0 */  addiu      $at, $zero, -0x20
    /* 84D24 800CA524 00A13824 */  and        $a3, $a1, $at
    /* 84D28 800CA528 10E0000C */  beqz       $a3, .L800CA55C
    /* 84D2C 800CA52C 00A72823 */   subu      $a1, $a1, $a3
    /* 84D30 800CA530 00E43821 */  addu       $a3, $a3, $a0
  .L800CA534:
    /* 84D34 800CA534 24840020 */  addiu      $a0, $a0, 0x20
    /* 84D38 800CA538 AC80FFE0 */  sw         $zero, -0x20($a0)
    /* 84D3C 800CA53C AC80FFE4 */  sw         $zero, -0x1C($a0)
    /* 84D40 800CA540 AC80FFE8 */  sw         $zero, -0x18($a0)
    /* 84D44 800CA544 AC80FFEC */  sw         $zero, -0x14($a0)
    /* 84D48 800CA548 AC80FFF0 */  sw         $zero, -0x10($a0)
    /* 84D4C 800CA54C AC80FFF4 */  sw         $zero, -0xC($a0)
    /* 84D50 800CA550 AC80FFF8 */  sw         $zero, -0x8($a0)
    /* 84D54 800CA554 1487FFF7 */  bne        $a0, $a3, .L800CA534
    /* 84D58 800CA558 AC80FFFC */   sw        $zero, -0x4($a0)
  .L800CA55C:
    /* 84D5C 800CA55C 2401FFFC */  addiu      $at, $zero, -0x4
    /* 84D60 800CA560 00A13824 */  and        $a3, $a1, $at
    /* 84D64 800CA564 10E00005 */  beqz       $a3, .L800CA57C
    /* 84D68 800CA568 00A72823 */   subu      $a1, $a1, $a3
    /* 84D6C 800CA56C 00E43821 */  addu       $a3, $a3, $a0
  .L800CA570:
    /* 84D70 800CA570 24840004 */  addiu      $a0, $a0, 0x4
    /* 84D74 800CA574 1487FFFE */  bne        $a0, $a3, .L800CA570
    /* 84D78 800CA578 AC80FFFC */   sw        $zero, -0x4($a0)
  .L800CA57C:
    /* 84D7C 800CA57C 18A00005 */  blez       $a1, .L800CA594
    /* 84D80 800CA580 00000000 */   nop
    /* 84D84 800CA584 00A42821 */  addu       $a1, $a1, $a0
  .L800CA588:
    /* 84D88 800CA588 24840001 */  addiu      $a0, $a0, 0x1
    /* 84D8C 800CA58C 1485FFFE */  bne        $a0, $a1, .L800CA588
    /* 84D90 800CA590 A080FFFF */   sb        $zero, -0x1($a0)
  .L800CA594:
    /* 84D94 800CA594 03E00008 */  jr         $ra
    /* 84D98 800CA598 00000000 */   nop
.size bzero, . - bzero
    /* 84D9C 800CA59C 00000000 */  nop
