.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_800D20B0
    /* 8C8B0 800D20B0 40026800 */  mfc0       $v0, $13 /* handwritten instruction */
    /* 8C8B4 800D20B4 03E00008 */  jr         $ra
    /* 8C8B8 800D20B8 00000000 */   nop
.size func_800D20B0, . - func_800D20B0
    /* 8C8BC 800D20BC 00000000 */  nop
