.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osDisableInt
    /* 852D0 800CAAD0 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 852D4 800CAAD4 2401FFFE */  addiu      $at, $zero, -0x2
    /* 852D8 800CAAD8 01014824 */  and        $t1, $t0, $at
    /* 852DC 800CAADC 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 852E0 800CAAE0 31020001 */  andi       $v0, $t0, 0x1
    /* 852E4 800CAAE4 00000000 */  nop
    /* 852E8 800CAAE8 03E00008 */  jr         $ra
    /* 852EC 800CAAEC 00000000 */   nop
.size __osDisableInt, . - __osDisableInt

/* Handwritten function */
glabel __osRestoreInt
    /* 852F0 800CAAF0 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 852F4 800CAAF4 01044025 */  or         $t0, $t0, $a0
    /* 852F8 800CAAF8 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 852FC 800CAAFC 00000000 */  nop
    /* 85300 800CAB00 00000000 */  nop
    /* 85304 800CAB04 03E00008 */  jr         $ra
    /* 85308 800CAB08 00000000 */   nop
.size __osRestoreInt, . - __osRestoreInt
    /* 8530C 800CAB0C 00000000 */  nop
