.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_800CA480
    /* 84C80 800CA480 18A00011 */  blez       $a1, .L800CA4C8
    /* 84C84 800CA484 00000000 */   nop
    /* 84C88 800CA488 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 84C8C 800CA48C 00AB082B */  sltu       $at, $a1, $t3
    /* 84C90 800CA490 1020000F */  beqz       $at, .L800CA4D0
    /* 84C94 800CA494 00000000 */   nop
    /* 84C98 800CA498 00804025 */  or         $t0, $a0, $zero
    /* 84C9C 800CA49C 00854821 */  addu       $t1, $a0, $a1
    /* 84CA0 800CA4A0 0109082B */  sltu       $at, $t0, $t1
    /* 84CA4 800CA4A4 10200008 */  beqz       $at, .L800CA4C8
    /* 84CA8 800CA4A8 00000000 */   nop
    /* 84CAC 800CA4AC 310A001F */  andi       $t2, $t0, 0x1F
    /* 84CB0 800CA4B0 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* 84CB4 800CA4B4 010A4023 */  subu       $t0, $t0, $t2
  .L800CA4B8:
    /* 84CB8 800CA4B8 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* 84CBC 800CA4BC 0109082B */  sltu       $at, $t0, $t1
    /* 84CC0 800CA4C0 1420FFFD */  bnez       $at, .L800CA4B8
    /* 84CC4 800CA4C4 25080020 */   addiu     $t0, $t0, 0x20
  .L800CA4C8:
    /* 84CC8 800CA4C8 03E00008 */  jr         $ra
    /* 84CCC 800CA4CC 00000000 */   nop
  .L800CA4D0:
    /* 84CD0 800CA4D0 3C088000 */  lui        $t0, 0x8000
    /* 84CD4 800CA4D4 010B4821 */  addu       $t1, $t0, $t3
    /* 84CD8 800CA4D8 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L800CA4DC:
    /* 84CDC 800CA4DC BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* 84CE0 800CA4E0 0109082B */  sltu       $at, $t0, $t1
    /* 84CE4 800CA4E4 1420FFFD */  bnez       $at, .L800CA4DC
    /* 84CE8 800CA4E8 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* 84CEC 800CA4EC 03E00008 */  jr         $ra
    /* 84CF0 800CA4F0 00000000 */   nop
.size func_800CA480, . - func_800CA480
    /* 84CF4 800CA4F4 00000000 */  nop
    /* 84CF8 800CA4F8 00000000 */  nop
    /* 84CFC 800CA4FC 00000000 */  nop
