.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osGetCount
    /* 85BC0 800CB3C0 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* 85BC4 800CB3C4 03E00008 */  jr         $ra
    /* 85BC8 800CB3C8 00000000 */   nop
    /* 85BCC 800CB3CC 00000000 */  nop
