.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osProbeTLB
    /* 85210 800CAA10 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 85214 800CAA14 310900FF */  andi       $t1, $t0, 0xFF
    /* 85218 800CAA18 2401E000 */  addiu      $at, $zero, -0x2000
    /* 8521C 800CAA1C 00815024 */  and        $t2, $a0, $at
    /* 85220 800CAA20 012A4825 */  or         $t1, $t1, $t2
    /* 85224 800CAA24 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 85228 800CAA28 00000000 */  nop
    /* 8522C 800CAA2C 00000000 */  nop
    /* 85230 800CAA30 00000000 */  nop
    /* 85234 800CAA34 42000008 */  tlbp /* handwritten instruction */
    /* 85238 800CAA38 00000000 */  nop
    /* 8523C 800CAA3C 00000000 */  nop
    /* 85240 800CAA40 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* 85244 800CAA44 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 85248 800CAA48 01615824 */  and        $t3, $t3, $at
    /* 8524C 800CAA4C 1560001A */  bnez       $t3, .L800CAAB8
    /* 85250 800CAA50 00000000 */   nop
    /* 85254 800CAA54 42000001 */  tlbr /* handwritten instruction */
    /* 85258 800CAA58 00000000 */  nop
    /* 8525C 800CAA5C 00000000 */  nop
    /* 85260 800CAA60 00000000 */  nop
    /* 85264 800CAA64 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* 85268 800CAA68 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* 8526C 800CAA6C 000B5842 */  srl        $t3, $t3, 1
    /* 85270 800CAA70 01646024 */  and        $t4, $t3, $a0
    /* 85274 800CAA74 15800004 */  bnez       $t4, .L800CAA88
    /* 85278 800CAA78 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* 8527C 800CAA7C 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* 85280 800CAA80 10000002 */  b          .L800CAA8C
    /* 85284 800CAA84 00000000 */   nop
  .L800CAA88:
    /* 85288 800CAA88 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .L800CAA8C:
    /* 8528C 800CAA8C 304D0002 */  andi       $t5, $v0, 0x2
    /* 85290 800CAA90 11A00009 */  beqz       $t5, .L800CAAB8
    /* 85294 800CAA94 00000000 */   nop
    /* 85298 800CAA98 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* 8529C 800CAA9C 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* 852A0 800CAAA0 00411024 */  and        $v0, $v0, $at
    /* 852A4 800CAAA4 00021180 */  sll        $v0, $v0, 6
    /* 852A8 800CAAA8 008B6824 */  and        $t5, $a0, $t3
    /* 852AC 800CAAAC 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* 852B0 800CAAB0 10000002 */  b          .L800CAABC
    /* 852B4 800CAAB4 00000000 */   nop
  .L800CAAB8:
    /* 852B8 800CAAB8 2402FFFF */  addiu      $v0, $zero, -0x1
  .L800CAABC:
    /* 852BC 800CAABC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 852C0 800CAAC0 03E00008 */  jr         $ra
    /* 852C4 800CAAC4 00000000 */   nop
.size __osProbeTLB, . - __osProbeTLB
    /* 852C8 800CAAC8 00000000 */  nop
    /* 852CC 800CAACC 00000000 */  nop
