.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osSetCompare
    /* 8B620 800D0E20 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
    /* 8B624 800D0E24 03E00008 */  jr         $ra
    /* 8B628 800D0E28 00000000 */   nop
.size __osSetCompare, . - __osSetCompare
    /* 8B62C 800D0E2C 00000000 */  nop
