.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_800CC5E0
    /* 86DE0 800CC5E0 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 86DE4 800CC5E4 03E00008 */  jr         $ra
    /* 86DE8 800CC5E8 00000000 */   nop
    /* 86DEC 800CC5EC 00000000 */  nop
