.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_800CC5D0
    /* 86DD0 800CC5D0 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
    /* 86DD4 800CC5D4 00000000 */  nop
    /* 86DD8 800CC5D8 03E00008 */  jr         $ra
    /* 86DDC 800CC5DC 00000000 */   nop
