.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_800CC6A0
    /* 86EA0 800CC6A0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 86EA4 800CC6A4 2409001F */  addiu      $t1, $zero, 0x1F
    /* 86EA8 800CC6A8 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 86EAC 800CC6AC 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* 86EB0 800CC6B0 240A0017 */  addiu      $t2, $zero, 0x17
    /* 86EB4 800CC6B4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* 86EB8 800CC6B8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 86EBC 800CC6BC 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* 86EC0 800CC6C0 00095982 */  srl        $t3, $t1, 6
    /* 86EC4 800CC6C4 016A5825 */  or         $t3, $t3, $t2
    /* 86EC8 800CC6C8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* 86ECC 800CC6CC 24090001 */  addiu      $t1, $zero, 0x1
    /* 86ED0 800CC6D0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* 86ED4 800CC6D4 00000000 */  nop
    /* 86ED8 800CC6D8 42000002 */  tlbwi /* handwritten instruction */
    /* 86EDC 800CC6DC 00000000 */  nop
    /* 86EE0 800CC6E0 00000000 */  nop
    /* 86EE4 800CC6E4 00000000 */  nop
    /* 86EE8 800CC6E8 00000000 */  nop
    /* 86EEC 800CC6EC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 86EF0 800CC6F0 03E00008 */  jr         $ra
    /* 86EF4 800CC6F4 00000000 */   nop
    /* 86EF8 800CC6F8 00000000 */  nop
    /* 86EFC 800CC6FC 00000000 */  nop
