.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_800C6740
    /* 80F40 800C6740 3C088000 */  lui        $t0, 0x8000
    /* 80F44 800C6744 240A2000 */  addiu      $t2, $zero, 0x2000
    /* 80F48 800C6748 010A4821 */  addu       $t1, $t0, $t2
    /* 80F4C 800C674C 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800C6750:
    /* 80F50 800C6750 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 80F54 800C6754 0109082B */  sltu       $at, $t0, $t1
    /* 80F58 800C6758 1420FFFD */  bnez       $at, .L800C6750
    /* 80F5C 800C675C 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 80F60 800C6760 03E00008 */  jr         $ra
    /* 80F64 800C6764 00000000 */   nop
.size func_800C6740, . - func_800C6740
    /* 80F68 800C6768 00000000 */  nop
    /* 80F6C 800C676C 00000000 */  nop
