#ifndef OVL_H
#define OVL_H

typedef enum OverlayId {
    OVL_BOOT_UP,
    OVL_TITLE_SCREEN,
    OVL_RIDER_SELECT,
    OVL_COURSE_OVERVIEW,
    OVL_COURSE_SELECT,
    OVL_RACE_RESULTS,
    OVL_6,
    OVL_TIME_TRIALS_RESULTS,
    OVL_STUNT_MODE_RESULTS,
    OVL_OPTIONS_MENU,
    OVL_OPTIONS_CHANGE_NAMES,
    OVL_OPTIONS_VIEW_RECORDS,
    OVL_OPTIONS_CHANGE_CONDITIONS,
    OVL_OPTIONS_AUDIO,
    OVL_OPTIONS_ERASE_COURSE_RECORDS,
    OVL_OPTIONS_SAVE_AND_LOAD,
    OVL_16,
    OVL_CEREMONY,
    OVL_DEMO,
    OVL_TIME_TRIAL
} OverlayId;
#endif /* OVL_H */
