#ifndef WR64_OVL_H
#define WR64_OVL_H

typedef enum OverlayId_e {
    OVL_BOOT_UP,
    OVL_TITLE_SCREEN,
    OVL_RIDER_SELECT,
    OVL_COURSE_OVERVIEW,
    OVL_COURSE_SELECT,
    OVL_RACE_RESULTS,
    OVL_6,
    OVL_TIME_TRIALS_RESULTS,
    OVL_STUNT_MODE_RESULTS,
    OVL_OPTIONS_MENU,
    OVL_OPTIONS_CHANGE_NAMES,
    OVL_OPTIONS_VIEW_RECORDS,
    OVL_OPTIONS_CHANGE_CONDITIONS,
    OVL_OPTIONS_AUDIO,
    OVL_OPTIONS_ERASE_COURSE_RECORDS,
    OVL_OPTIONS_SAVE_AND_LOAD,
    OVL_16,
    OVL_CEREMONY,
    OVL_DEMO = 18, // Apparently these two share the same overlay
    OVL_TIME_TRIAL = 18
} OverlayId;

#endif
