name: Check Format

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  build:
    name: Check format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v4

    - name: Install package requirements
      run: sudo apt-get install -y python3 python3-pip clang-format-14 clang-tidy-14

    - name: Check format
      run: ./tools/check_format.sh
