name: regress-internal
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
jobs:
  build:
    if: github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name
    uses: ./.github/workflows/regress-validate.yaml
    secrets: inherit
    
