name: regress-validate
on:
  workflow_call:
    secrets:
      SECRET_PASSPHRASE: { required: true }
      SECRET_REPO: { required: true }
      SECRET_TOKEN: { required: true }
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ us ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - name: Update Submodules
      run: git submodule update --init --recursive
    - name: Fetch Secrets
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.SECRET_REPO }}
        token: ${{ secrets.SECRET_TOKEN }}
        path: secret_repo
    - name: Decrypt Secrets
      working-directory: secret_repo
      run: ./decrypt_secret.sh
      env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
          SECRET_BASENAME: baserom.us.z64
          SECRET_VERSION: us
    - name: Install Packages
      run: sudo apt-get install -y git make git build-essential binutils-mips-linux-gnu python3 python3-pip
    - name: Build Dependencies
      run: make dependencies
    - name: Build
      run: make extract; make
    - name: Generate Progress Report
      run: python3 -m mapfile_parser objdiff_report --version ${{ matrix.version }}
    - name: Upload Progress Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/progress.json
    - name: Discord Progress
      if: ${{ github.event_name == 'push' }}
      run: python3 tools/discord_progress.py --discord_url ${{ secrets.DISCORD_URL }} --version ${{ matrix.version }}
    - name: Cleanup
      run: rm -f baserom.us.z64
